Sonar bug and code smell cleanup
constellation-app/constellation pull request #1053
Opened 2021-05-20 02:30 UTC by aldebaran30701

This PR fixes most sonar bugs and some code smells.

Major Bugs (null pointer possibility, regex, )
Cast one operand to float
Compare using class rather than instance of
cast one operand to float
method intentionally blank
static used within an instance method
make finalize method protected
string literal duplication
if else constructs should have an else case

This is a partial cleanup as part of #1022 
The issues above have not been completely eradicated. I have done my best to clear up any cases that have a solution which is easy enough to not break any code.

**NOTE:**
If the reviewer could please pay close attention to JSONImportFileParser.java as I am not exactly sure it has the same behaviour as previous. The sonar warning was to make it explicit that we want to match the start or the end of a string. IE. I added braces around the internal part of the regex to show grouping. 
```
// Before
line[columnMap.get(prefix + entry.getKey())] = entry.getValue().toString().replaceAll("^\"|\"$", "");

// After
line[columnMap.get(prefix + entry.getKey())] = entry.getValue().toString().replaceAll("(^\")|(\"$)", "");
```

2021-05-24 02:31 UTC, antares1470 requested changes

2021-05-24 02:31 UTC, antares1470 commented on CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/InfoMapPanel.java
> +            // Default case added per S126
I would change this comment to "Do nothing" as this comment doesn't make much sense outside the sonar context. Similarly for other comments like this one

2021-05-24 02:31 UTC, antares1470 commented on CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/infomap/InfoMapPanel.java
> +     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
I assume there was some auto-formatting here or similar just looking at the rest of the PR but I would move the warning part to a new line

2021-05-24 02:31 UTC, antares1470 commented on CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/paths/SP2Traverse.java
> +                // Ignore nodes with no neighbour
In these instances, I would just remove the first (sonar) comment

2021-05-24 02:31 UTC, antares1470 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/grid/GridArranger.java
> +        if (null == gc) {
Don't know if this was a sonar suggestion or not but I think I prefer the null on the right of an comparison

2021-05-24 02:31 UTC, antares1470 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/grid/GridArranger.java
> +                    return new Dimension(0, 0);
Since this code is the same as the default case, you can probably omit this case

2021-05-24 02:31 UTC, antares1470 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/pendants/PendantsArranger.java
> +        // Method intentionally left blank - S1186
omit the sonar code at the end. Similarly for other places this is done

2021-05-24 02:31 UTC, antares1470 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/spectral/GraphSpectrumEmbedder.java
> +                                break;// Default case added per S126
omit the sonar comment. Similarly in other places this occurs

2021-05-24 23:33 UTC, antares1470 approved these changes

2021-05-24 23:36 UTC, aldebaran30701 commented
@antares1470 thoughts on the major bugs sonar has just picked up?

2021-05-24 23:40 UTC, antares1470 commented
> @antares1470 thoughts on the major bugs sonar has just picked up?

Yep I jumped the gun on the approval. Looking at other equals implementations, that start with the following code block which I think could be added
'''
if (obj == null) {
  return false;
}
'''

2021-05-25 20:04 UTC, arcturus2 approved these changes
Approving this PR but going forward I would like to discuss the formatting. I would prefer we just keep the formatting to the default width in NetBeans. The Javadoc lines being changed make it very difficult to see the actual changes.

2021-05-25 20:04 UTC, merged