Create Default Font Settings Suggestions
constellation-app/constellation pull request #1061
Opened 2021-05-24 23:09 UTC by arcturus2

### Description of the Change

* The font settings get set by the JavaFX Top Component instead of  having to make changes in each top component.
* Buttons and Labels no longer need to be set individually
* The font and family settings take affect without requiring a restart.

I've tested all the views that are in scope and they work pretty well. The only one not working properly is the attribute editor and I was unable to make the attribute titles font update properly so I have put that code back to how it was. The buttons on the attribute editor do update but the attribute title and value don't.

### Alternate Designs

### Why Should This Be In Core?

### Benefits

### Possible Drawbacks

### Verification Process

### Applicable Issues

2021-05-24 23:21 UTC, antares1470 requested changes

2021-05-24 23:21 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/javafx/JavafxStyleManager.java
> +        } catch (IOException ex) {
final

2021-05-24 23:21 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/javafx/JavafxStyleManager.java
> +            try ( PrintWriter printWriter = new PrintWriter(tempStyleClass)) {
think this can be final as well?

2021-05-24 23:21 UTC, antares1470 commented on CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewTopComponent.java
> +                        };
Not sure if it is the case but the formatting seems a little out of place here

2021-05-24 23:22 UTC, Delphinus8821 commented
On the branch for my PR the attribute editor displays like this (using my test font of Impact at font size 20):
![image](https://user-images.githubusercontent.com/73083035/119418067-582a8f80-bd36-11eb-8896-1dfbc622f282.png)

2021-06-02 00:16 UTC, antares1470 requested changes
I was testing it and noted that I don't think this is working quite as expected. 

Firstly, not sure if it was intentional but the default has changed from Arial 12 to Arial 14 which definitely threw me off when I first loaded.

Secondly, I think some bits still rely on a Constellation restart before being applied. The following 2 images show Constellation after changing the font size:
- Immediately after changing font size from 14 to 12
![FontChange1](https://user-images.githubusercontent.com/62311243/120404985-e2a06e00-c38a-11eb-8360-07ab951938d4.png)
- After a restart
![FontChange2](https://user-images.githubusercontent.com/62311243/120404994-e502c800-c38a-11eb-814c-21a8c6b9a063.png)

Note that the global parameters font didn't update until after the restart. Similarly, the size of the boxes containing the Data Access Plugins didn't update to fit the font until after the restart

2021-06-03 04:44 UTC, arcturus2 reviewed
I can't approve this because I originally raised the PR but I'm happy with it based on testing @Delphinus8821 @antares1470.

2021-06-03 04:44 UTC, arcturus2 commented on CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
> +        //showAllToggle.setMaxSize(60, 12);
can you delete this line?

2021-06-03 04:44 UTC, arcturus2 commented on CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
> +       // addMenu.setMaxSize(18, 12);
can you delete this line?

2021-06-03 04:52 UTC, arcturus2 commented
@Delphinus8821 I added caching for the dynamic style sheet 1ecd79b. Please review.

2021-06-03 05:00 UTC, Delphinus8821 approved these changes

2021-06-03 05:17 UTC, antares1470 approved these changes

2021-06-03 05:17 UTC, merged