Update DAV Select All Plugin to include Transactions
constellation-app/constellation pull request #1085
Opened 2021-06-04 00:39 UTC by Delphinus8821

### Description of the Change
Updated the Data Access View Select All Plugin to select both vertices and transactions when used. 

### Alternate Designs
N/A

### Why Should This Be In Core?
The description of the Select All Plugin stats that it will select everything on the current graph which would indicate it would select vertices and transactions. Updated the functionality to match the description. 

### Benefits

### Possible Drawbacks
None realised

### Verification Process

### Applicable Issues
#1025

2021-06-04 02:02 UTC, antares1470 requested changes
If you're able to add a whatsnew entry as well, that would be great

2021-06-04 02:02 UTC, antares1470 commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/utility/SelectAllPlugin.java
> +        int transactionCount = graph.getTransactionCount();
these 2 can be final

2021-06-04 02:02 UTC, antares1470 commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/utility/SelectAllPlugin.java
> +            int transaction = graph.getTransaction(transactionPosition);
same here

2021-06-04 02:30 UTC, antares1470 requested changes

2021-06-04 02:30 UTC, antares1470 commented on CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
> +<p>The Select All Plugin in the Data Access View now selects everything on the graph including transactions as well as vertices.</p>
omit "as well as vertices" from the end of the sentence.

2021-06-04 02:30 UTC, antares1470 commented on CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
> +== 2021-06-04 Select All Plugin now selects Transactions
I would omit "now selects Transactions" since this is explained in the description

2021-06-04 03:27 UTC, antares1470 approved these changes

2021-06-09 11:41 UTC, arcturus2 approved these changes

2021-06-09 11:42 UTC, merged