updated-ISSUE_TEMPLATE.md
constellation-app/constellation pull request #1104
Opened 2021-06-08 14:36 UTC by danger-ahead

### Description of the Change - **updated the ISSUE_TEMPLATE to include instructions in the requirements for filling out the steps to reproduce**

### Alternate Designs

### Why Should This Be In Core?

### Benefits

### Possible Drawbacks - **None**

### Verification Process

### Applicable Issues #1103

2021-06-16 01:36 UTC, aldebaran30701 commented
I believe the issue template should include a message hint in the sections of expected and actual behaviour. The hint should specify that if applicable, include the time something should execute within, and specify the actual time something took to execute. 
@danger-ahead does that sound like an improvement you could add to the PR ?

2021-06-16 05:42 UTC, danger-ahead commented
> I believe the issue template should include a message hint in the sections of expected and actual behaviour. The hint should specify that if applicable, include the time something should execute within, and specify the actual time something took to execute.
> @danger-ahead does that sound like an improvement you could add to the PR ?

@aldebaran30701 will do that

2021-06-29 22:51 UTC, antares1470 requested changes
To extend @aldebaran30701's comment, I'd suggest a comment including that the Expected and Actual behaviour should be measureable (which is more applicable for more issues than just time-related ones)

2021-06-29 22:51 UTC, antares1470 commented on ISSUE_TEMPLATE.md
> +* The "Steps to Reproduce" should outline the steps required to reproduce the issue. The rest should filled out accordingly.
I would possibly move this point to immediately after the first point in the Requirements section as I think this follows on from that point

2021-07-21 04:41 UTC, antares1470 commented
Closing as this has been done in #1139

2021-07-21 04:41 UTC, closed without merging