🐛 Layers view null pointer fix
constellation-app/constellation pull request #1113
Opened 2021-06-17 06:05 UTC by aldebaran30701

### Description of the Change
A few noted null pointers to finish off #1002 
Returning a boolean as false instead of null made sense.

Tested by having no graph open.
Use the hotkeys ctrl + alt + L
ctrl + alt +1

The error should occur at that point.

With the fix, there is no null pointer and no drawbacks because nothing should  be occurring without a graph or the Layers View opened.

2021-06-17 22:12 UTC, antares1470 requested changes

2021-06-17 22:12 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewController.java
> +        return parent != null ? parent.getVisibility() : false;
this can be changed to `return parent != null && parent.getVisibility()`

2021-06-17 22:42 UTC, antares1470 approved these changes

2021-06-21 02:41 UTC, arcturus2 approved these changes

2021-06-21 02:41 UTC, merged