Create Link between Notes to Nodes and Transactions
constellation-app/constellation pull request #1138
Opened 2021-07-09 05:25 UTC by Delphinus8821

### Description of the Change
User Notes now store which nodes and transactions were selected when the note was created if the user chooses to apply the note to the current graph selection. 

![Selected notes fom graph selection](https://user-images.githubusercontent.com/73083035/125026590-16765e00-e0c4-11eb-938a-dabc6847bb56.PNG)

Also added the ability for users to change the selection for a specific note from the edit dialog. 3 radio buttons have been added to the bottom of the edit dialog window where the user is able to choose to keep the original selection, add what is currently selected on the graph to the note selection, or remove what is currently selected on the graph from the note selection. 
If the note was applied to the entire graph and the user then edits the note and adds nodes and/or transactions to the selection then the note will no longer be applied to the entire graph and only to those nodes/transactions. Or, if the user were to remove all of the nodes and transactions the note was specifically applied to, the note would then be applied to the entire graph. 

![EditNote](https://user-images.githubusercontent.com/73083035/125026581-10807d00-e0c4-11eb-8cac-8e7e303f0913.PNG)

A right click menu added to user notes for users to select the related nodes and transactions on the graph for that note. This menu was only added to user notes for now as the only option is select on graph

A selection filter was also created so that when in the selection filter, notes relating to the graph elements currently selected appear. E.g. if nothing is selected, only the notes that are applied to the entire graph appear. If nodes and/or transactions are selected which are related to a user note that has been created that note appears as well as all of the graph notes. This only applies to user notes and the other filters are not able to be selected while the selected filter is. 

### Alternate Designs
None realised.

### Why Should This Be In Core?
Allows for users to assign nodes and transactions to a specific note. This lets users write notes about specific graph elements. 

### Possible Drawbacks
None realised. 

### Applicable Issues
#1004

2021-07-11 23:17 UTC, antares1470 requested changes
If you're able to include a whatsnew entry as well as some changelog entries for the edited function definitions, that would be great

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +    private Boolean applySelected;
change this to the primitive type `boolean`

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +            }
can reduce this if-else to `applySelected = applyToSelection.isSelected()`

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +                            List<Integer> selectedTransactions = new ArrayList();
both final + add diamond operator

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +                        for (int node : nodesSelected) {
final

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +                        for (int transaction : transactionsSelected) {
final

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +            for (int node : nodesSelected) {
final

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +            for (int transaction : transactionsSelected) {
final

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +            for (int node : nodesSelected) {
final

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +            for (int transaction : transactionsSelected) {
final

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewEntry.java
> +            this.transactionsSelected = new ArrayList();
diamond operators

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewEntry.java
> +    public NotesViewEntry(final String dateTime, final String noteTitle, final String noteContent, final Boolean userCreated, final Boolean graphAttribute) {
use primitive `boolean`

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewStateIoProvider.java
> +                            JsonNode nodesArrayNode = notesArray.get(i).get(5);
final

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewStateIoProvider.java
> +                                List<Integer> selectedNodes = new ArrayList();
final and diamond operator

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewStateIoProvider.java
> +                            JsonNode transactionsArrayNode = notesArray.get(i).get(6);
final

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewStateIoProvider.java
> +                                List<Integer> selectedTransactions = new ArrayList();
final and diamond operator

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewStateIoProvider.java
> +                                int[] nodesArray = new int[nodesLength];
final

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewStateIoProvider.java
> +                                Iterator<Integer> nodesIterator = nodesSelected.iterator();
final

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewStateIoProvider.java
> +                                int[] transactionsArray = new int[transactionsLength];
final

2021-07-11 23:17 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewStateIoProvider.java
> +                                Iterator<Integer> transactionsIterator = transactionsSelected.iterator();
final

2021-07-11 23:33 UTC, antares1470 requested changes
On top of the above, I tested the branch and encountered the following things:
- If I untick 'Apply note to graph selection', the note appears to be lost (can't see the note even with User Notes filter on)
- With 'Apply note to graph selection' ticked, it appears the note doesn't always apply to the selection. I created a note with just one node selected and sometimes the note was applied to the node but other times it applied to the whole graph and other times still applied to none of the graph
- I observed that if you choose the Selected filter that it deselects the other two. I'm ok with this but I noted that you can't then select any of the other filters until you untick the Selected filter which I don't think is intuitive. Maybe if you select one of the other filters it deselects the Selected filter?

2021-07-15 03:08 UTC, Delphinus8821 commented
Example of the added description for user notes about what graph elements are linked to the note (Line at the bottom of each note). 

![AddedDescription](https://user-images.githubusercontent.com/73083035/125721566-e822d75a-aadf-45ad-879a-2cf0e54abf54.PNG)

2021-07-15 16:10 UTC, arcturus2 approved these changes
Tested and works well. The issues @antares1470 mentioned seem to be fixed.

2021-07-15 23:59 UTC, antares1470 requested changes
Tested again and have a couple of things:
- If I have nothing selected on my graph and have the Apply to graph selection checkbox ticked, the note I create is applied to 0 nodes and 0 transactions and so can only be seen through the User Notes filter. While this behaviour is technically working, I think it would be cool to treat no selection the same as applying to the whole graph (similar to arrangements)

- I created a graph with 2 nodes and a transaction and then created 2 notes: one applied to the whole graph and one applied to just a single node. When I used the right-click context menu on the whole graph note, it selected the whole graph. When I then did the same for the other note, it deselected the transaction but not the node (that the note wasn't applied to). I think it should deselect everything on the graph that the note was applied to (similar to Select on graph in QCV)

2021-07-16 05:41 UTC, antares1470 approved these changes

2021-07-16 05:41 UTC, merged