Update ISSUE_TEMPLATE.md
constellation-app/constellation pull request #1139
Opened 2021-07-09 07:23 UTC by sol695510

### Description of the Change

Update the descriptions of fields to be filled in the Issue Template.

### Alternate Designs

N/A

### Why Should This Be In Core?

N/A

### Benefits

Provides clearer goals for fixing the issue.

### Possible Drawbacks

N/A

### Verification Process

N/A

### Applicable Issues

#1103

2021-07-11 23:30 UTC, aldebaran30701 requested changes
I'd maybe suggest writing it only once - like a section just above Expected Behaviour. This section could say
```
Strive to include measurable metrics that can be aimed for when describing behaviour.

e.g. action 'x' should take 5 seconds or less to finish, NOT action 'x' should finish faster.

e.g. action 'x' takes 4 clicks, NOT action 'x' multiple clicks to be accomplished.
```

Let me know your thoughts

2021-07-12 06:58 UTC, sol695510 commented
> I'd maybe suggest writing it only once - like a section just above Expected Behaviour. This section could say
> 
> ```
> Strive to include measurable metrics that can be aimed for when describing behaviour.
> 
> e.g. action 'x' should take 5 seconds or less to finish, NOT action 'x' should finish faster.
> 
> e.g. action 'x' takes 4 clicks, NOT action 'x' multiple clicks to be accomplished.
> ```
> 
> Let me know your thoughts

The "strive" part can be just written once, but the "e.g." parts are not all the same.

2021-07-12 22:52 UTC, aldebaran30701 commented
>The "strive" part can be just written once, but the "e.g." parts are not all the same.

Understood, that's why I worked in an example of each.

I'm thinking with the new changes made, it should only include one example for each heading. We don't want to make it a very cluttered PR template, and as such only one line should be suffice to get the point across.

2021-07-20 22:56 UTC, antares1470 requested changes

2021-07-20 22:56 UTC, antares1470 commented on ISSUE_TEMPLATE.md
> +or if its a workflow issue "should be accomplished in 2 or less clicks".
I would comment this out (i.e. surround it in \<!-- Try to include...  -->).

Also "it's a time" and "it's a workflow"

2021-07-21 01:49 UTC, antares1470 approved these changes

2021-07-21 04:06 UTC, arcturus2 approved these changes

2021-07-21 04:40 UTC, merged