Update Quality Control Category Names and Colours
constellation-app/constellation pull request #1144
Opened 2021-07-23 05:11 UTC by Delphinus8821

### Description of the Change
Updated the names of most of the Quality Control Categories and some of the colours to be more visible and less confusing. 
The category names have been changed from Default, Info, Warning, Severe and Fatal, which could be confusing, to Minor, Medium, Major, Severe and Critical. A category called OK has been added for when no Quality Control rules have been flagged. 

### Alternate Designs
None realised.

### Why Should This Be In Core?
Updates the Quality Control categories to be less confusing for users by providing more meaningful category names. The colours are now also more meaningful by being colours that are more representative of the category names (e.g. OK is Green, Minor is Blue, Medium is Yellow, Major is Orange, Severe is Red and Critical is Dark Red).

### Benefits
Makes the Quality Control view less confusing for users. 

### Possible Drawbacks
None realised.

### Verification Process
Tested that all of the new category names and colours appear correctly, see images below.

### Applicable Issues
#1136 

![OK](https://user-images.githubusercontent.com/73083035/126738060-52d91a68-bd31-4cd6-85be-65453ff4ecca.PNG)
![Minor](https://user-images.githubusercontent.com/73083035/126738068-df0bee0f-419b-4331-a786-b4418ffb2fdd.PNG)
![Medium](https://user-images.githubusercontent.com/73083035/126738070-c0a1aeac-837d-4c15-af54-7cadaf9180bc.PNG)
![Major](https://user-images.githubusercontent.com/73083035/126738072-99995e72-7f31-47ed-b337-a1fd8bb8565a.PNG)
![Severe](https://user-images.githubusercontent.com/73083035/126738075-f9de79c8-857a-408c-b486-af7d22026e84.PNG)
![Critical](https://user-images.githubusercontent.com/73083035/126738078-e3081e19-c608-49db-bf23-e605058e8502.PNG)

2021-07-23 05:40 UTC, arcturus2 commented
I'm yet to test it but it looks absolutely amazing @Delphinus8821.

2021-07-26 00:20 UTC, antares1470 requested changes
One minor thing but the Quality Category button in DAV has a white background when the category is ok. If you could change that to the same green you have in the QCV, that would be great (I did a quick test of this and I don't think there are any issues of this against the Go button).

Also if you're able to add a whatsnew and changelog entries, that would be good.

2021-07-26 03:24 UTC, antares1470 approved these changes

2021-07-26 05:19 UTC, arcturus2 approved these changes
Just brilliant :star:

2021-07-26 05:50 UTC, merged