Keep Attribute Editor multiple values expanded
constellation-app/constellation pull request #1147
Opened 2021-07-26 08:35 UTC by Auriga2

### Description of the Change
When the graph selection was changing, or graph was zooming in or out , any expanded node or transaction attributes were contracting to display "<Multiple Values>", rather than remaining expanded and populating newly selected values. 

### Alternate Designs
A possible extension is to keep the selection of attributes across graphs, and/or retain the selection upon returning to the graph. Currently it works only within a graph and loses the selection if the user leaves and returns a graph.

### Why Should This Be In Core?
Better UX and saves time

### Benefits
Better UX and saves time

### Possible Drawbacks
N/A

### Verification Process

1. Open a graph and the Attribute Editor
2. Select a set of nodes or transactions such that an attribute has more than one value for the selection
3. Expand an attribute with multiple values
4. Change the graph selection such that the chosen attribute still has multiple values and verify the expanded attribute/s do not collapse. 
5. Select a single Node or Transaction and verify the attribute/s collapse. Select multiple Nodes or Transactions and verify the previously viewed attribute/s expand again.
6. Zoom in and out the graph and verify the attributes are still expanded. 

 
### Applicable Issues

https://github.com/constellation-app/constellation/issues/1128

2021-07-26 22:48 UTC, antares1470 requested changes
If you're able to add a whatsnew entry as well that would be great

2021-07-26 22:48 UTC, antares1470 commented on CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeData.java
> +    public void setKeepExpanded(boolean isKeepExpanded) {
final

2021-07-27 22:29 UTC, antares1470 approved these changes

2021-07-27 23:46 UTC, arcturus2 commented on CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
> +        attributePane.expandedProperty().addListener((observable, wasExpanded, isNowExpanded)
I'm not sure if there is a way to remove the listener - I couldn't find a place to do it in this class.

2021-07-27 23:46 UTC, arcturus2 approved these changes
Works great.

2021-07-28 00:06 UTC, merged