Added More Filters for Auto Notes
constellation-app/constellation pull request #1152
Opened 2021-08-02 00:09 UTC by Delphinus8821

### Description of the Change
Have added another check combo box to the top of the Notes View to filter on what Auto Notes are displayed. This check combo box is only visible when the Auto Notes filter is selected. The second check combo box is populated with the same tags that appear in the Plugin Reporter. 

### Alternate Designs
None realised

### Why Should This Be In Core?
This change allows for users to filter more thoroughly on the Auto notes that are generated. 

### Benefits
Gives more users more options for filtering on what notes appear on the UI as not all auto notes that are generated would be relevant for users to view.

### Possible Drawbacks
None Realised

### Verification Process
Old graphs do not have plugin reporter tags attached to auto notes which results in the new check combo box being empty until new plugins are run. If nothing is selected in the new check combo box then all Auto notes are displayed and this occurs by default. 

### Applicable Issues
#1005 

![New Check Combo Box](https://user-images.githubusercontent.com/73083035/127789370-8dd77aa9-4d34-453b-b300-4d74711aa0b3.PNG)

2021-08-02 08:20 UTC, arcturus2 approved these changes
@Delphinus8821 this works really well and feels quick.

I noticed that when I loaded a saved graph with a filter (i.e GENERAL) that it did not load with just the "GENERAL" notes but with all of them.

I also noticed that switching graphs did not load the filters from the view's state but rather the last thing that was there on the notes view.

I think both of these are intentional so not an issue. The plugin reporter has the same behavior.

2021-08-04 01:28 UTC, antares1470 requested changes
The only thing I got from testing was that old graphs with existing auto notes don't have any tags (only newly generated auto notes will have tags) meaning you won't see any old auto notes when applying filters (and filters won't be available until after new auto notes are generated). Not sure though whether that is something to fix here or as a separate task

If you're also able to add a whatsnew as well as a changelog entry for some of the function definition changes, that would be great

2021-08-04 01:28 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +        autoFilterCheckComboBox.getCheckModel().getCheckedItems().addListener(new ListChangeListener() {
convert to a lambda (looks like you'll need to specify the type of the parameter though due to ambiguity)

2021-08-04 01:28 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +            for (String tag : tags) {
final

2021-08-04 01:28 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +                        if (addNote) {
I'd probably just merge these together given this is the only spot the boolean expression is used

2021-08-04 01:28 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewStateIoProvider.java
> +                                List<String> tagsArray = new ArrayList<>();
final

2021-08-05 22:56 UTC, antares1470 approved these changes

2021-08-05 22:56 UTC, merged