Unit tests for MergeNodesByLocation class
constellation-app/constellation pull request #1162
Opened 2021-08-04 00:05 UTC by Auriga2

### Description of the Change
Added unit tests for MergeNodesByLocation class.

I came up with a random number for the Threshold, such that it fulfill the if conditions. Let me know if we need to use a more realistic number.

### Alternate Designs

### Why Should This Be In Core?

### Benefits

### Possible Drawbacks

### Verification Process

### Applicable Issues
https://github.com/constellation-app/constellation/issues/413

2021-08-04 03:36 UTC, antares1470 requested changes

2021-08-04 03:36 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByLocationNGTest.java
> +        Map result = instance.getNodesToMerge(graph, leadVertexChooser, threshold, selectedOnly);
I'd avoid using the raw type

2021-08-04 03:36 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByLocationNGTest.java
> +        cluster1.addAll(Arrays.asList(new Integer[]{0, 1, 2, 3, 4}));
You can specify the elements of `Arrays.asList()` without needing to declare an array as an FYI (i.e. `Arrays.asList(0, 1, 2, 3, 4)` also works)

2021-08-04 03:36 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByLocationNGTest.java
> +        Map result = instance.getNodesToMerge(graph, leadVertexChooser, threshold, selectedOnly);
raw type

2021-08-04 03:36 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByLocationNGTest.java
> +        Map result = instance.getNodesToMerge(graph, leadVertexChooser, threshold, selectedOnly);
raw type

2021-08-04 03:36 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByLocationNGTest.java
> +    public void testGetNodesToMergee_Threshold_1600000_selectedOnlyFalse_2() throws Exception {
The impression I get is that this test is the same as the previous one except with different numbers. Generally speaking I would aim to have inputs for your unit tests achieving a particular purpose (e.g. edge cases, trying to get a particular flow of execution, etc)

2021-08-04 03:36 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByLocationNGTest.java
> +        Map result = instance.getNodesToMerge(graph, leadVertexChooser, threshold, selectedOnly);
raw type

2021-08-04 03:36 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByLocationNGTest.java
> +        Map result = instance.getNodesToMerge(graph, leadVertexChooser, threshold, selectedOnly);
same here

2021-08-04 03:36 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByLocationNGTest.java
> +        Map result = instance.getNodesToMerge(graph, leadVertexChooser, threshold, selectedOnly);
same here

2021-08-04 03:36 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByLocationNGTest.java
> +        Map result = instance.getNodesToMerge(graph, leadVertexChooser, threshold, selectedOnly);
same here

2021-08-05 10:46 UTC, arcturus2 approved these changes
Thank you @Auriga2 for this. I've approved it but pending changes suggested by @antares1470 in relation to having raw types.

2021-08-06 05:18 UTC, antares1470 approved these changes

2021-08-06 05:20 UTC, merged