Unit tests for MergeNodesByType.java
constellation-app/constellation pull request #1173
Opened 2021-08-10 00:28 UTC by Auriga2

### Description of the Change
Added unit tests for MergeNodesByType.java

### Alternate Designs

### Why Should This Be In Core?

### Benefits

### Possible Drawbacks

### Verification Process

### Applicable Issues
#413

2021-08-10 01:36 UTC, antares1470 requested changes

2021-08-10 01:36 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByTypeNGTest.java
> +        Map result = instance.getNodesToMerge(graph, leadVertexChooser, threshold, selectedOnly);
Are you to add the specific type of the map here?

2021-08-10 01:36 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByTypeNGTest.java
> +        Map result = instance.getNodesToMerge(graph, leadVertexChooser, threshold, selectedOnly);
same here

2021-08-10 23:43 UTC, antares1470 approved these changes

2021-08-11 03:26 UTC, arcturus2 approved these changes

2021-08-11 03:27 UTC, merged