`MergeNodesPlugin` Unit Tests
constellation-app/constellation pull request #1183
Opened 2021-08-11 04:26 UTC by formalhaunt

### Description of the Change

Unit tests for `MergeNodesPlugin` class. Added a test concrete implementation of `MergeNodeType`.  This gets picked up in the scan by the NB `Lookup`. As it is only in the test packages it will not be included in the final distribution and so is only available in the tests.

### Alternate Designs

Tried mocking the static call to `Lookup` but it proved difficult when the test was run with the other test classes. Something else must call the `MergeNodesPlugin` class before I set up the mocks and pre-populate the `static final` global variables essentially preventing the mocking from working.

### Why Should This Be In Core?

Tests are awesome!

### Benefits

Improves code coverage.

### Possible Drawbacks

### Verification Process

### Applicable Issues

https://github.com/constellation-app/constellation/issues/413

2021-08-12 00:22 UTC, arcturus2 approved these changes
Really neat and a lot of effort put in here. Thank you @formalhaunt.

2021-08-12 22:49 UTC, antares1470 requested changes

2021-08-12 22:49 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesPluginNGTest.java
> +                "MergeNodesPlugin.selected"));
I think it would be better to use the constant strings, e.g. `MergeNodePlugin.MERGE_TYPE_PARAMETER_ID`

2021-08-12 22:49 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesPluginNGTest.java
> +                (PluginParameter<SingleChoiceParameterValue>) parameters.get("MergeNodesPlugin.merge_type");
similar here and other places where the parameter name is used

2021-08-17 00:54 UTC, aldebaran30701 approved these changes

2021-08-17 23:27 UTC, arcturus2 commented
@formalhaunt would you be able to have a look at the feedback given and respond when you can?

2021-08-18 22:42 UTC, formalhaunt commented
Just saw these. My opinion is that you shouldn't use production code to in your code test. Basically if something changes in the production code the tests should break. By referencing the constants in the production code you prevent this from happening.
I found this article that makes my point in probably better words https://dev.to/scottshipp/don-t-use-non-test-constants-in-unit-tests-3ej0

2021-08-18 23:19 UTC, antares1470 commented
> 
> 
> Just saw these. My opinion is that you shouldn't use production code to in your code test. Basically if something changes in the production code the tests should break. By referencing the constants in the production code you prevent this from happening.
> I found this article that makes my point in probably better words https://dev.to/scottshipp/don-t-use-non-test-constants-in-unit-tests-3ej0
> In this case its probably not a big deal as they are id strings but imho I think its good practice to follow where possible.

I guess for me personally it comes down to the purpose of the test. If the value of the constant is important for the test then it makes sense to reference the value itself rather than the constant. On the other hand, if the value of a constant isn't that important to the test then I think using the constant may be better in the long term because in those instances, if you're changing the value of the constant you probably want that reflected in the test anyway.

But I get your point. I'd be the first to admit that I'm definitely getting picky here with my suggestion so I can approve this as is

2021-08-19 00:02 UTC, antares1470 approved these changes

2021-08-19 00:02 UTC, merged