Create MergeNodesByPrefixNGTest.java
constellation-app/constellation pull request #1192
Opened 2021-08-12 06:57 UTC by sol695510

### Description of the Change
Unit tests for MergeNodesByPrefix.

### Alternate Designs
N/A

### Why Should This Be In Core?
N/A

### Benefits
N/A

### Possible Drawbacks
N/A

### Verification Process
N/A

### Applicable Issues
#413

2021-08-12 07:00 UTC, sol695510 commented
I have been made aware @Auriga2 has modified and statically accessed LONGEST_VERTEX_CHOOSER and SHORTEST_VERTEX_CHOOSER for the unit tests for MergeNodesBySuffix, so what I have in the unit test file can be modified after their changes have been merged.

2021-08-12 09:02 UTC, arcturus2 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByPrefixNGTest.java
> +    };
@sol695510 can you please use the instance in `MergeNodesPlugin` and make that protected so that you can access it from this unit test?

2021-08-12 09:05 UTC, arcturus2 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByPrefixNGTest.java
> + */
Please configure the header template which includes the copyright and github username - see https://github.com/constellation-app/constellation/blob/master/CONTRIBUTING.md#pull-requests

2021-08-13 00:24 UTC, antares1470 requested changes

2021-08-13 00:24 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByPrefixNGTest.java
> +        Map result = instance.getNodesToMerge(graph, leadVertexChooser, threshold, selectedOnly);
Add the type of the map here

2021-08-13 00:24 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByPrefixNGTest.java
> +        Map result = instance.getNodesToMerge(graph, leadVertexChooser, threshold, selectedOnly);
same here

2021-08-13 00:24 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByPrefixNGTest.java
> +        Map result = instance.getNodesToMerge(graph, leadVertexChooser, threshold, selectedOnly);
and here

2021-08-13 00:24 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesByPrefixNGTest.java
> +        Map result = instance.getNodesToMerge(graph, leadVertexChooser, threshold, selectedOnly);
and here

2021-08-13 01:36 UTC, antares1470 approved these changes

2021-08-13 01:41 UTC, aldebaran30701 approved these changes

2021-08-13 01:57 UTC, merged