Core Util Tests
constellation-app/constellation pull request #1195
Opened 2021-08-13 01:00 UTC by formalhaunt

### Description of the Change

Filled in some coverage gaps in the core utils module. Fixed some sonar smells once the tests were in place.

### Alternate Designs

### Why Should This Be In Core?

Tests are awesome!

### Benefits

Improves code coverage

### Possible Drawbacks

### Verification Process

### Applicable Issues

https://github.com/constellation-app/constellation/issues/413

2021-08-13 01:30 UTC, aldebaran30701 requested changes
Just some consistency things

2021-08-13 01:30 UTC, aldebaran30701 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/csv/SmartCSVWriter.java
> +    private static final char NEW_LINE = '\n';
For consistency you can use SeparatorConstants.NEWLINE
Similarly, it might be worth adding line feed and other constants to that file

2021-08-13 01:30 UTC, aldebaran30701 commented on CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/text/StringUtilitiesNGTest.java
> +        final Set<Character> splitChars = Set.of(',', '|', '\t');
SeparatorConstants.PIPE can be used here, same with TAB etc.

2021-08-13 01:30 UTC, aldebaran30701 commented on CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/text/StringUtilitiesNGTest.java
> +        final char delimiter = ',';
SeparatorConstants.COMMA

2021-08-13 01:43 UTC, arcturus2 approved these changes
Again many thanks @formalhaunt for doing this and for also fixing up the Sonar smells.

2021-08-13 01:55 UTC, antares1470 approved these changes
Good to go once @aldebaran30701's feedback has been addressed

2021-08-13 05:33 UTC, formalhaunt commented
I have updated the PR pointing at the Separator class

2021-08-13 05:42 UTC, aldebaran30701 commented
>I have updated the PR pointing at the Separator class

@formalhaunt What did you think of my other two suggestions about the SeparatorConstants within `StringUtilitiesNGTest`

2021-08-16 01:04 UTC, formalhaunt commented
My preference is to not reference the static variables of the code being tested in the tests. Thats why I didn't change those two. The main point was to stop the CSV class from creating new string objects every time it added a row to a csv output stream.
The two cases in the test are not in loops etc. and will only be created once. I can put it in a final static at the top of the class but I don't think there is much value in it.

2021-08-16 01:11 UTC, aldebaran30701 commented
@formalhaunt Great explanation, happy with that from my end.

2021-08-16 01:11 UTC, aldebaran30701 approved these changes

2021-08-16 01:27 UTC, merged