Table View State Unit Tests
constellation-app/constellation pull request #1199
Opened 2021-08-13 05:41 UTC by formalhaunt

### Description of the Change

Added unit tests for the state package in table view.

### Alternate Designs

### Why Should This Be In Core?

Tests are awesome!

### Benefits

### Possible Drawbacks

### Verification Process

### Applicable Issues

https://github.com/constellation-app/constellation/issues/413

2021-08-15 23:07 UTC, arcturus2 approved these changes

2021-08-16 02:22 UTC, antares1470 requested changes

2021-08-16 02:22 UTC, antares1470 commented on CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/state/TableViewState.java
> +    public boolean equals(Object o) {
parameter can be final

2021-08-16 02:22 UTC, antares1470 commented on CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/state/TableViewState.java
> +        TableViewState that = (TableViewState) o;
can also be final. Maybe another name other than `that` would be good as well

2021-08-16 22:32 UTC, antares1470 approved these changes

2021-08-16 22:32 UTC, merged