Update tags for CoreConversationView plugins
constellation-app/constellation pull request #1207
Opened 2021-08-15 23:58 UTC by sol695510

### Description of the Change
Updated tags for CoreConversationView plugins.

### Alternate Designs
N/A

### Why Should This Be In Core?
N/A

### Benefits
N/A

### Possible Drawbacks
N/A

### Verification Process
N/A

### Applicable Issues
#1126

2021-08-16 03:52 UTC, arcturus2 requested changes
There are 3 inline plugins in `ConversationBox`. Would you be able to break them out into static classes?

2021-08-17 22:41 UTC, antares1470 requested changes

2021-08-17 22:41 UTC, antares1470 commented on CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/AddContentAttributesPlugin.java
> +@PluginInfo(pluginType = PluginType.NONE, tags = {"MODIFY"})
I would probably categorise as `PluginType.UPDATE`

2021-08-17 22:41 UTC, antares1470 commented on CoreConversationView/src/au/gov/asd/tac/constellation/views/conversationview/TranslationConversationContributionProvider.java
>      private class SetTranslationPlugin extends SimpleEditPlugin {
Given the plugin appears to be setting the relevant transaction attribute, I would go with MODIFY rather than LOW LEVEL

2021-08-17 23:38 UTC, arcturus2 approved these changes
I'm approving this based on suggestions from @antares1470 being addressed.

2021-08-18 02:04 UTC, antares1470 approved these changes

2021-08-18 02:04 UTC, merged