Update/add tags to CoreTableView plugins
constellation-app/constellation pull request #1212
Opened 2021-08-16 04:06 UTC by sol695510

### Description of the Change
Updated or added tags to CoreTableView plugins.

### Alternate Designs
N/A

### Why Should This Be In Core?
N/A

### Benefits
N/A

### Possible Drawbacks
N/A

### Verification Process
N/A

### Applicable Issues
#1126

2021-08-16 05:57 UTC, antares1470 requested changes

2021-08-16 05:57 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/delete/DeleteSelectionPlugin.java
> +@PluginInfo(pluginType = PluginType.DELETE, tags = {"DELETE", "MODIFY"})
I think I would remove the modify tag here as I think it makes sense to distinguish between creating, modifying, and deleting

2021-08-16 05:57 UTC, antares1470 commented on CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/TableViewUtilities.java
> +    @PluginInfo(pluginType = PluginType.SELECTION, tags = {"MODIFY", "SELECT"})
I think for similar reasons I would omit modify here

2021-08-16 08:11 UTC, arcturus2 approved these changes

2021-08-17 01:09 UTC, aldebaran30701 approved these changes
Once @antares1470 mentioned points are fixed, this looks good to me!

2021-08-17 22:32 UTC, antares1470 approved these changes

2021-08-17 22:32 UTC, merged