Tagging core graph utilities
constellation-app/constellation pull request #1213
Opened 2021-08-16 04:16 UTC by aldebaran30701

Refactor of anonymous plugins and tagging. Most of these plugins are tagged as VIEW as they change the camera or are camera related (perspective bookmarks)

2021-08-16 08:07 UTC, arcturus2 requested changes
Some suggestions to spark a discussion. Noted that these are changing `META` attributes so I can understand where the `VIEW` came from too.

2021-08-16 08:07 UTC, arcturus2 commented on CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/planes/PlaneManagerTopComponent.java
> +    private static class SetPlanePositionPlugin extends SimpleEditPlugin {
Hmm how about `MODIFY` ?

2021-08-17 01:14 UTC, aldebaran30701 commented
I've reviewed the tags and agree about your suggestions. I've kept the pluginTypes as VIEW because it seems to relate to the graph view.

2021-08-17 02:22 UTC, antares1470 requested changes

2021-08-17 23:22 UTC, aldebaran30701 commented on CoreGraphUtilities/src/au/gov/asd/tac/constellation/graph/utilities/perspectives/PerspectiveBookmarkTopComponent.java
> +            } catch (ExecutionException ex) {
Fixed

2021-08-17 23:39 UTC, antares1470 approved these changes

2021-08-18 00:04 UTC, arcturus2 approved these changes

2021-08-18 00:08 UTC, merged