Tagging for code graph file
constellation-app/constellation pull request #1216
Opened 2021-08-16 05:28 UTC by aldebaran30701

Refactored plugin to use read instead of getting a graph write lock

2021-08-16 05:59 UTC, antares1470 requested changes

2021-08-16 05:59 UTC, antares1470 commented on CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/open/OpenFilePlugin.java
> +    protected void read(GraphReadMethods graph, PluginInteraction interaction, PluginParameters parameters) throws InterruptedException, PluginException {
finals

2021-08-16 07:31 UTC, arcturus2 commented on CoreGraphFile/src/au/gov/asd/tac/constellation/graph/file/open/OpenFilePlugin.java
> +import au.gov.asd.tac.constellation.plugins.templates.SimpleReadPlugin;
:clap:

2021-08-16 07:32 UTC, arcturus2 approved these changes

2021-08-17 02:27 UTC, antares1470 approved these changes

2021-08-17 02:28 UTC, merged