Add tags to Core Schema View
constellation-app/constellation pull request #1227
Opened 2021-08-16 23:31 UTC by aldebaran30701

Add tags to Core Schema View

2021-08-17 01:28 UTC, antares1470 approved these changes

2021-08-17 02:51 UTC, arcturus2 requested changes

2021-08-17 02:51 UTC, arcturus2 commented on CoreSchemaView/src/au/gov/asd/tac/constellation/views/schemaview/TypeDropper.java
> +    public static class TypeDropperPlugin extends SimpleEditPlugin {
I was thinking "IMPORT" because what the `*Dropper`'s allow you to do is drag and drop something onto the graph and it should render it.

2021-08-18 00:40 UTC, arcturus2 approved these changes

2021-08-18 00:40 UTC, merged