Feature/table view refactor
constellation-app/constellation pull request #1267
Opened 2021-08-23 05:51 UTC by formalhaunt

### Description of the Change

This is an attempt at trying to come up with a template for how JFX components should be coded. The current way results in 1000+ lines of code with imbedded inner classes and code going everywhere and being executed at different times based on user triggered events.

The change is trying to separate out the areas of concern. This is just an initial attempt. More needs to be done. But its nearing a point where tests are more writable which will make finishing the refactor easier.

### Alternate Designs

### Why Should This Be In Core?

Readable and testable code is a must in any large project. Having high code complexity is not a good idea.

### Benefits

This will hopefully make the code more readable and allow others to more easily consume the smaller chunks of functionality.

### Possible Drawbacks

The code is obviously now spread across more files. This may make things more difficult to piece together but if I name things and structure things well, it should be pretty logical with a basic understanding of JavaFX.

### Verification Process

### Applicable Issues

2021-09-08 01:02 UTC, antares1470 requested changes
When I opened the Table View I got this exception (no graph opened):
```
java.lang.NullPointerException
	at au.gov.asd.tac.constellation.views.tableview2.TableViewTopComponent.getRemovedAttributes(TableViewTopComponent.java:268)
	at au.gov.asd.tac.constellation.views.tableview2.TableViewTopComponent.handleNewGraph(TableViewTopComponent.java:374)
	at au.gov.asd.tac.constellation.views.ListeningTopComponent.newActiveGraph(ListeningTopComponent.java:176)
	at au.gov.asd.tac.constellation.views.ListeningTopComponent.componentOpened(ListeningTopComponent.java:97)
```
And when I closed table view after that, I got this exception:
```
java.lang.IllegalArgumentException: Listener not registered.
	at java.prefs/java.util.prefs.AbstractPreferences.removePreferenceChangeListener(AbstractPreferences.java:1106)
	at au.gov.asd.tac.constellation.preferences.utilities.PreferenceUtilites.removePreferenceChangeListener(PreferenceUtilites.java:76)
	at au.gov.asd.tac.constellation.views.JavaFxTopComponent.handleComponentClosed(JavaFxTopComponent.java:140)
	at au.gov.asd.tac.constellation.views.ListeningTopComponent.componentClosed(ListeningTopComponent.java:108)
```
When I had the table view open and then created a new graph I got this:
```
java.lang.NullPointerException
	at org.apache.commons.collections4.CollectionUtils.subtract(CollectionUtils.java:348)
	at org.apache.commons.collections4.CollectionUtils.subtract(CollectionUtils.java:310)
	at au.gov.asd.tac.constellation.views.tableview2.TableViewTopComponent.getRemovedAttributes(TableViewTopComponent.java:267)
	at au.gov.asd.tac.constellation.views.tableview2.TableViewTopComponent.handleNewGraph(TableViewTopComponent.java:374)
	at au.gov.asd.tac.constellation.views.tableview2.TableViewTopComponent.lambda$new$4(TableViewTopComponent.java:157)
	at au.gov.asd.tac.constellation.views.ListeningTopComponent.lambda$graphChanged$11(ListeningTopComponent.java:249)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at au.gov.asd.tac.constellation.views.ListeningTopComponent.graphChanged(ListeningTopComponent.java:239)
	at au.gov.asd.tac.constellation.graph.locking.DualGraph$1.lambda$update$0(DualGraph.java:93)
```
Finally when I created a sphere graph and made a selection, I got this after trying to switch from transaction mode to node mode in the table view:
```
java.lang.NullPointerException
	at org.apache.commons.collections4.CollectionUtils.subtract(CollectionUtils.java:343)
	at org.apache.commons.collections4.CollectionUtils.subtract(CollectionUtils.java:310)
	at au.gov.asd.tac.constellation.views.tableview2.TableViewTopComponent.getRemovedAttributes(TableViewTopComponent.java:267)
	at au.gov.asd.tac.constellation.views.tableview2.TableViewTopComponent.handleNewGraph(TableViewTopComponent.java:374)
	at au.gov.asd.tac.constellation.views.tableview2.TableViewTopComponent.lambda$new$4(TableViewTopComponent.java:157)
	at au.gov.asd.tac.constellation.views.ListeningTopComponent.lambda$graphChanged$11(ListeningTopComponent.java:249)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at au.gov.asd.tac.constellation.views.ListeningTopComponent.graphChanged(ListeningTopComponent.java:239)
	at au.gov.asd.tac.constellation.graph.locking.DualGraph$1.lambda$update$0(DualGraph.java:93)
```
There could be other exceptions but that should be enough to get started. The stack traces did have a little extra in them but I opted to only include the Constellation parts of it (i.e. the most helpful bits of the trace)

2021-09-08 05:31 UTC, formalhaunt commented on CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/api/UserTablePreferences.java
> +public final class UserTablePreferences {
Not sure on the specific thinking that triggered me to do this. It happened pretty early on in the piece. But just looking at the code. These preference values are updated in runnable's used by listeners and the JavaFX thread. The concern is you don't want them competing.

That's why I added the conditional max rows per page update method as it does a check before the update.

2021-09-08 05:49 UTC, formalhaunt commented on CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/TableViewTopComponentNGTest.java
> +            }
This will provide guidance in the test results. Personally I like this better than a random exception being thrown 🤷‍♂️

2021-09-08 05:56 UTC, formalhaunt commented on CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/api/Column.java
> +    public void setAttributeNamePrefix(String attributeNamePrefix) {
Added

2021-09-08 05:56 UTC, formalhaunt commented on CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/api/UserTablePreferences.java
> +    public static final Integer DEFAULT_MAX_ROWS_PER_PAGE = 500;
Changed to `int`.

2021-09-08 05:59 UTC, formalhaunt commented on CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/components/TablePaneNGTest.java
> +        }
Similar reasoning to above. The throws were also there for the `latch.await()`. I have removed them favour of using the `WaitForAsyncUtils.waitForFxEvents();` utility from TestFX.

2021-09-08 06:00 UTC, formalhaunt commented on CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/components/TablePaneNGTest.java
> +        }
See above.

2021-09-09 11:57 UTC, arcturus2 commented
@formalhaunt the rewrite makes the code so much cleaner and you have done a really amazing job with the unit tests, code smells and code coverage. Well done!

I have been giving it a test as I am keen to merge this in, however there are some issues cropping up mainly the table data not recovering from an update. It often goes into the progress state (blue circle icon) and then stays like that and the data doesn't show. I think it has something to do with the old threading logic that was there to fix performance issues whereby if there was more that 1 table state thread, it would kill the older one when the new thread started. I can't see that logic there anymore but perhaps there is something that needs to be cleaned up to prevent thread interrupts from causing the table to no longer function.

Happy to help debug this if you like.

2021-09-09 22:43 UTC, antares1470 requested changes
Have another exception for you. 

I created a sphere graph with table view open and then switched from transaction mode to node mode. Subsequent switching between those modes doesn't trigger the exception:
```
java.lang.NullPointerException
	at javafx.controls/javafx.scene.control.ContextMenu$2.onChanged(ContextMenu.java:198)
	at javafx.base/com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
[catch] at javafx.base/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.base/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.base/javafx.collections.ModifiableObservableListBase.addAll(ModifiableObservableListBase.java:102)
	at javafx.base/javafx.collections.ObservableListBase.addAll(ObservableListBase.java:246)
	at au.gov.asd.tac.constellation.views.tableview2.components.ColumnVisibilityContextMenu.init(ColumnVisibilityContextMenu.java:226)
	at au.gov.asd.tac.constellation.views.tableview2.components.Table.openColumnVisibilityMenu(Table.java:613)
	at au.gov.asd.tac.constellation.views.tableview2.components.Table.updateColumns(Table.java:203)
	at au.gov.asd.tac.constellation.views.tableview2.components.TablePane.lambda$updateTable$2(TablePane.java:93)
```

Another thing I observed was that while no exception was thrown, there appear to be some issues with table preferences. When I pressed Save Preferences it took a few seconds to bring up the dialog to save the preferences. When I went to load those preferences, after I selected the preferences to load and hit ok, it locked up the application.

2021-09-09 22:43 UTC, antares1470 commented on CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/factory/TableViewPageFactory.java
> +            } catch (ExecutionException ex) {
make these final

2021-09-09 22:46 UTC, antares1470 commented on CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/factory/TableViewPageFactory.java
> +            } catch (ExecutionException ex) {
(ignore the outdated tag, issue still there at the same lines)

2021-09-09 22:49 UTC, antares1470 commented on CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview2/TableViewTopComponentNGTest.java
> +            }
I guess my reasoning for throwing is that is what we're doing in other unit tests for other classes. If you think the message is going to be helpful enough then I guess we can keep it but it is worth noting that if we do encounter this situation that we're probably going to need to debug the same way anyway

2021-09-14 01:40 UTC, antares1470 requested changes
I'm no longer seeing the exception but I'm still experiencing those issues with load/save templates. Just to make sure, I tested in master again and didn't encounter those issues there

2021-09-14 03:39 UTC, formalhaunt commented
So the load/save should work now. There was a thread sleep there previously that I tried to fix with a wait on the FX thread. Problem is that it was already in the FX thread which caused it to freeze.

2021-09-14 04:53 UTC, antares1470 requested changes
Got an exception trying to load an old template that didn't have a sort order:
```
java.lang.NullPointerException
	at au.gov.asd.tac.constellation.views.tableview2.components.PreferencesMenu.loadPreferences(PreferencesMenu.java:294)
	at au.gov.asd.tac.constellation.views.tableview2.components.PreferencesMenu.lambda$init$1(PreferencesMenu.java:113)
```

2021-09-14 04:53 UTC, antares1470 commented on CoreTableView/src/au/gov/asd/tac/constellation/views/tableview2/components/PreferencesMenu.java
> +                } catch (TimeoutException | ExecutionException ex) {
finals

2021-09-14 05:31 UTC, arcturus2 commented
Similar to @antares1470 I am having problems loading and saving templates. These did work when I was testing this PR last week/the week before.

2021-09-14 05:32 UTC, arcturus2 commented
@formalhaunt with the most recent changes I am no longer able to lockup the table view which is great. Thank you.

2021-09-14 23:05 UTC, formalhaunt commented
Ok. Added code that should allow the preferences to be backwards compatible with prefs save prior to this code change.

2021-09-14 23:15 UTC, antares1470 approved these changes
Thanks for all the effort you've put into this @formalhaunt

2021-09-14 23:33 UTC, arcturus2 approved these changes
I'll echo what @antares1470 said - this is an amazing effort @formalhaunt and a pattern we hope to follow in our other views. Thank you.

2021-09-14 23:34 UTC, merged