:fire: Remove unused code from ImmutableObjectCache
constellation-app/constellation pull request #1303
Opened 2021-08-26 04:43 UTC by groombridge34a

### Description of the Change

ImmutableObjectCache included a second, more complex version of the code which is unreachable.

### Alternate Designs

Whether the simple or complex code is enabled could be controlled by changing the VERBOSE field to a flag controlled by configuration.

### Why Should This Be In Core?

This code has never been reachable during the commit history of this project. Keeping dead code "just because" increases the complexity of the code.

### Benefits

Reduced code complexity and technical debt.

### Possible Drawbacks

This code was not covered by unit tests, it's possible that regression errors could be introduced.

### Verification Process

Created regression tests

### Applicable Issues

#413

2021-08-30 00:13 UTC, groombridge34a commented
> 
> 
> I think the `VERBOSE` was left there for debugging when deving locally. @cygnus-x-1 let me know your thoughts on this PR.

2021-08-31 01:28 UTC, arcturus2 requested changes
@groombridge34a wondering if you don't mind if we keep the code and use `java.util.logging.Logger` and `FINE` them instead? It will help with debugging and it is used by the IOProvider's.

2021-09-13 06:30 UTC, arcturus2 commented
@groombridge34a  would you be able to have a look passing the "verbose" as a parameter or something like that to test it out? I am looking at a performance issue and the verbose logging in here is useful so I would like to keep it if thats ok?

2021-09-20 01:39 UTC, closed without merging

2021-09-20 01:40 UTC, groombridge34a commented
As discussed, this code is useful for debugging and should be exposed with a code conditional of some kind. Closing this PR and deleting the branch, will proceed in a new PR.