:fire: Remove unused "localized" parameter from locate method signature
constellation-app/constellation pull request #1320
Opened 2021-08-30 23:22 UTC by groombridge34a

### Description of the Change

The `ConstellationInstalledFileLocator` class in `CoreUtilities` includes a `locate()` method intended to find files in NetBeans modules. One of the method parameters is `boolean localized`, which was intended to narrow the search to a localized and branded lookup. But the method never uses this parameter, it's hard coded to `false`.

### Alternate Designs

None.

### Why Should This Be In Core?

Minor update.

### Benefits

Increased clarity by removing unused code.

### Possible Drawbacks

None.

### Verification Process

- Used NetBeans to check for usages of the `locate()` method in the entire Core, and addressed those usages.
- Used NetBeans to check that `ConstellationInstalledFileLocator` has no occurrences of polymorphism (eg inheritance) and method overrides.
- Ran the unit test suite as problems with changing method signatures manifest as compile time errors.
- Ran Constellation, clicked around the Map View and the Scripting View.

### Applicable Issues

None.

2021-08-31 03:23 UTC, arcturus2 approved these changes

2021-08-31 23:04 UTC, antares1470 requested changes
Thanks for this @groombridge34a. If you're able to add an entry to CHANGELOG.md with the method signature change, that would be great

2021-09-02 04:47 UTC, groombridge34a commented
> 
> 
> Thanks for this @groombridge34a. If you're able to add an entry to CHANGELOG.md with the method signature change, that would be great

Done.

2021-09-02 23:07 UTC, antares1470 approved these changes

2021-09-06 00:52 UTC, merged