added tooltip to welcome view recent files
constellation-app/constellation pull request #1336
Opened 2021-09-01 06:47 UTC by Atlas139mkm

broken branch reproducer for welcome page tooltip error.

1. open constellation 
2. hover over any of the recent file buttons within the welcome view
3. Exception should occur

2021-09-03 01:46 UTC, Atlas139mkm commented
- I have updated the welcome page to show a tool tip when hovering over the recent graphs.
- I have turned wrap text off so the recent file name shows "..." this will help the user understand the title of the file is longer than what is shown on the screen.
- The tool tip will also not show on the recent item buttons without a file corresponding to them

2021-09-07 05:19 UTC, antares1470 requested changes

2021-09-07 05:19 UTC, antares1470 commented on CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/WelcomeViewPane.java
> +                    Tooltip toolTip = new Tooltip(recentGraphButtons[i].getText());
final

2021-09-07 05:19 UTC, antares1470 commented on CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/resources/welcome_theme.css
> +    /*    -fx-skin: "javafx.scene.control.skin.TooltipSkin";*/
If this is not needed, can this be removed?

2021-09-08 01:06 UTC, antares1470 approved these changes

2021-09-08 01:45 UTC, merged