fixed no image on recent graphs
constellation-app/constellation pull request #1343
Opened 2021-09-03 02:48 UTC by Atlas139mkm

### Description of the Change

- Added a default image when there is a graph with no screenshot
- Graph now updates its current screen shot on manual saves (ctrl s or closing the specific graph)
    - does not update on closing constellation, I couldn't find where the appropriate code was that saved the graphs
    
![image](https://user-images.githubusercontent.com/88649439/131942852-fe05350d-8108-411c-8b9b-25306efb6247.png)

### Why Should This Be In Core?

It looks nice by ensuring all recent graphs are uniform instead of some having an image and some not.

### Benefits

Look visually a lot nicer, especially when combined with the tool tip being added from #1336.

### Possible Drawbacks

Does not update the screen shot on saving when closing constellation.

### Verification Process

- Created new graphs and saved as = updates screenshot
- Manually saved graph (ctrl s) = updates screenshot
- Manually saved graph by closing the specific graph = updates screenshot
- Manually saved graph by closing constellation = doesn't update screenshot
- imported a graph and did not save it = shows default image
- imported a graph and saved it = updates screenshot

### Applicable Issues

#1094

2021-09-03 04:49 UTC, arcturus2 commented
Thank you for this @Atlas139mkm. Though I am yet to test this @Atlas139mkm but I was wondering if you could fix the minor code smell picked up by Sonar?

2021-09-03 05:31 UTC, Atlas139mkm commented
Just fixed it up, should be good now

2021-09-06 02:19 UTC, antares1470 requested changes

2021-09-06 02:19 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/gui/VisualGraphTopComponent.java
> +            File file = new File(freshGdo.getPrimaryFile().getPath());
final

2021-09-06 02:19 UTC, antares1470 commented on CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/WelcomeViewPane.java
> +                    if (i < fileNames.size()) {
can merge into `else if` since there is no other code in the else block outside the nested if block

2021-09-06 06:30 UTC, arcturus2 commented
How about the following scenario and let me know if this is out of scope @Atlas139mkm...

1. I open an old graph for the first time
2. close Constellation
3. open Constellation

I can see the recent graph is there but no placeholder image shows.

![image](https://user-images.githubusercontent.com/39325530/132170702-060a9fba-2227-4589-a9aa-da54e4366d61.png)

2021-09-06 23:03 UTC, Atlas139mkm commented
hmm so I just tried this out and mine appears to work as intended.  

Screen shot 1 shows my screenshots folder which only contains 2 screen shots for said file names.

Screen shot 2 shows my recent files which was able to find corresponding screenshots for the 2 files present within that screenshot directory. However it was not able to find a screen shot for file "oldNoteWithOldGa" so it provided the default image.

![image](https://user-images.githubusercontent.com/88649439/132264438-25199aef-66ba-4e5d-bf3c-39f221d9b9b3.png)

![image](https://user-images.githubusercontent.com/88649439/132264479-aa3d60f6-3ceb-45ff-9c87-35328d765190.png)

I'm not entirely sure how you received no image when its an if {} else {} statement. if a screen shot is present use that. else use the default image for the recent file.

2021-09-07 03:11 UTC, antares1470 commented
I've given this a test as well and confirm I see what @Atlas139mkm is seeing

2021-09-07 03:11 UTC, antares1470 approved these changes

2021-09-07 05:46 UTC, arcturus2 commented
My apologies @Atlas139mkm I was stuck in the `master` branch. Your change works perfectly.

2021-09-07 05:46 UTC, arcturus2 approved these changes

2021-09-07 05:51 UTC, merged