Add in the ability to do freeform selection via ALT+left mouse drawing
constellation-app/constellation pull request #1353
Opened 2021-09-05 07:58 UTC by CrucisGamma

### Description of the Change

Add in a way for a user to be able to run a freeform selection in the main graph view (similar to the box select)

### Alternate Designs

The alternate design was modelled on graphics tools

### Why Should This Be In Core?

It's adding to the functionality of the program and not having to do multiple little box selects at one time

### Benefits

The user will be able to do freeform selections to selectively pick out bits and pieces of the graph 

### Possible Drawbacks

Potential for some duplicated code requiring a refactor.  No speed or memory increase was noticed in the testing 

### Verification Process

Ran through multiple selections and box selections over multiple graphs with no loss of speed or noticeable slowdown after some time doing this.  No exceptions noted or odd behaviour encountered.

### Applicable Issues

#1268

2021-09-06 03:28 UTC, antares1470 requested changes

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/FreeformSelectionPlugin.java
> +        boolean requiresTransactionVisibility = txVisibilityAttr != Graph.NOT_FOUND;
final. Also could be moved closer to where they are used

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/FreeformSelectionPlugin.java
> +                    if (inFreeformPolygons(leftMostPoint, topMostPoint)) {
can merge these 2 if statements together (with `&&`)

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/FreeformSelectionPlugin.java
> +                                float visibility = graph.getFloatValue(txVisibilityAttr, txId);
final

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/FreeformSelectionPlugin.java
> +                                float visibility = graph.getFloatValue(txVisibilityAttr, txId);
final

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/DefaultInteractionEventHandler.java
> +        Point bottomRight = new Point();
final

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/DefaultInteractionEventHandler.java
> +         Float [] transformedVertices = freeformModel.getTransformedVertices();
final. Also if you could remove the space between `Float` and `[]` that would be great

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/DefaultInteractionEventHandler.java
> +        Plugin plugin = new FreeformSelectionPlugin(appendSelection, toggleSelection, VisualGraphUtilities.getCamera(rg), boxCameraCoordinates, transformedVertices, freeformModel.getNumPoints());
final

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/InteractiveGLVisualProcessor.java
> +    public VisualOperation setSelectionFreeformModel(SelectionFreeformModel model) {
parameter final

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/SelectionFreeformModel.java
> +    static private final int THRESHOLD = 8;
`static private` -> `private static`

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/SelectionFreeformModel.java
> +    public Point getPoint(int i) {
parameter final

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/SelectionFreeformModel.java
> +        float newHeight = bottomBoxCameraCoordinates - topBoxCameraCoordinates;
final

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/SelectionFreeformModel.java
> +        ArrayList<Float> vertices = new ArrayList<>();
final. Also change declaration to `List<Float>` (can keep instatiation as is)

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/SelectionFreeformModel.java
> +            float y = (getPoint(i).y - topMost) / ((float) height) * newHeight + topBoxCameraCoordinates;
final

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/SelectionFreeformModel.java
> +    public void setWindowBoxToCameraBox(float[] boxCameraCoordinates) {
parameter final

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/SelectionFreeformRenderable.java
> +        } catch (IOException ex) {
exception final

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/SelectionFreeformRenderable.java
> +            Logger.getLogger(SelectionFreeformRenderable.class.getName()).log(Level.SEVERE, null, ex);
I would extract the logger into a private static final field (see other classes for examples). This allows the logger to easily be used elsewhere in the class

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/SelectionFreeformRenderable.java
> +            float[] v = new float[150];
final

2021-09-06 03:28 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/renderables/SelectionFreeformRenderable.java
> +            Matrix44f mvpMatrix = new Matrix44f();
final

2021-09-06 05:42 UTC, CrucisGamma commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/FreeformSelectionPlugin.java
> +                    locatedInPolygon = !locatedInPolygon;
locatedInPolygon can change many times in the for loop.  This is a ray tracing algorithm where you test if a line  crosses a line in a polygon % 2 times.

2021-09-06 07:50 UTC, arcturus2 requested changes
@CrucisGamma it works really well and in terms of performance I couldn't see any issues.

Can you please add some doco regarding this and also an entry in `whatsnew.txt` for this please?

2021-09-07 02:24 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/FreeformSelectionPlugin.java
> +                    locatedInPolygon = !locatedInPolygon;
Right I missed that. As you were :)

2021-09-07 02:28 UTC, antares1470 approved these changes

2021-09-08 01:42 UTC, arcturus2 approved these changes

2021-09-08 01:43 UTC, merged