UI Unit Testing
constellation-app/constellation pull request #1356
Opened 2021-09-06 01:33 UTC by formalhaunt

### Description of the Change

TBC

### Alternate Designs

### Why Should This Be In Core?

TBC

### Benefits

TBC

### Possible Drawbacks

TBC

### Verification Process

TBC

### Applicable Issues

2021-09-08 01:41 UTC, antares1470 requested changes

2021-09-08 01:41 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIO.java
> +            } catch (IOException ex) {
final

2021-09-08 01:41 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIO.java
> +                DialogDisplayer.getDefault().notify(nd);
can use `NotifyDisplayer.display()`

2021-09-08 01:41 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIO.java
> +            } catch (IOException ioe) {
final

2021-09-08 01:41 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIO.java
> +            } catch (IOException ioe) {
final

2021-09-08 01:41 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIO.java
> +                DialogDisplayer.getDefault().notify(nd);
can use `NotifyDisplayer.notify()`

2021-09-08 01:41 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/genericjsonio/JsonIO.java
> +            } catch (SecurityException | IOException ex) {
final

2021-09-08 04:33 UTC, formalhaunt commented
Updated code based on comments from @antares1470

2021-09-08 04:59 UTC, antares1470 approved these changes

2021-09-09 08:29 UTC, arcturus2 approved these changes
Thank you very much for this too.

2021-09-09 08:29 UTC, merged