SaveParameters Test
constellation-app/constellation pull request #1364
Opened 2021-09-07 05:41 UTC by mimosa2

### Description of the Change

ParameterIOUtilities Unit test case for saveParameters

### Alternate Designs

### Why Should This Be In Core?

For unit testing

### Benefits

To improve code

### Possible Drawbacks

Performance

### Verification Process

Run the unit test

### Applicable Issues

2021-09-08 01:16 UTC, antares1470 requested changes

2021-09-08 01:16 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/io/ParameterIOUtilitiesNGTest.java
> +//
remove this comment with nothing in it

2021-09-08 01:16 UTC, antares1470 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/io/ParameterIOUtilitiesNGTest.java
> +//
remove these comments if code isn't being used

2021-09-10 00:47 UTC, antares1470 approved these changes

2021-09-13 06:25 UTC, arcturus2 approved these changes
Thanks @mimosa2

2021-09-13 06:25 UTC, merged