added balloon notifications to DB and File imports
constellation-app/constellation pull request #1375
Opened 2021-09-09 01:49 UTC by Atlas139mkm

### Description of the Change

I have removed pop up notification on file import and replaced it with a balloon notification. I have also added the notification to database imports as well.

File Importer:
![image](https://user-images.githubusercontent.com/88649439/132608263-b5275326-4770-462b-98c4-c6befbaa57df.png)
It says : imported 18393 rows of data from connection: test (what I named my connection)

Database:
![image](https://user-images.githubusercontent.com/88649439/132608214-b70e8b51-5d8d-4d07-bee1-fc6d076c9cbd.png)
This displays the exact same message as before but in balloon format.

### Alternate Designs

I have not added a click for more details. I wanted to wait for feedback first and what ask details I should add to that if I did add that feature. Also how to add a link to a balloon notification.

### Why Should This Be In Core?

It achieves the same outcome as the current pop up but does it in a less intrusive way to the user.

It also adds the functionality to the DB connection importer.

### Benefits

UX improvements.

### Possible Drawbacks

Maybe less obvious for some people??

### Verification Process

I ensured the message still posted the appropriate messages that I did before. This was based on if a file was imported, if a file wasn't imported and If no file was present.

### Applicable Issues

#1309

2021-09-09 12:06 UTC, arcturus2 approved these changes
Thanks for this @Atlas139mkm. This works really well. A very minor fix if you can make it is when it is only 1 file then it should be singular instead of "files".

2021-09-09 23:31 UTC, antares1470 requested changes
Agreeing with the suggestion from @arcturus2. Looks good otherwise

2021-09-10 00:38 UTC, antares1470 requested changes

2021-09-10 00:38 UTC, antares1470 commented on CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedPlugin.java
> +            }
Can be simplified to `final String fileFiles = (validFilenames.size() == 1) ? "file" : "files";`

2021-09-10 00:38 UTC, antares1470 commented on CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedPlugin.java
> +                }
similar here

2021-09-10 03:23 UTC, antares1470 approved these changes

2021-09-10 03:23 UTC, merged