Bugfix/histogram clears catergory and property selection on graph element selection change #1129
constellation-app/constellation pull request #1379
Opened 2021-09-09 07:58 UTC by sol695510

### Description of the Change
Stored the selections for Category, Property and Formatter in a new state within the HistogramState.

### Alternate Designs
N/A

### Why Should This Be In Core?
N/A

### Benefits
Reduces latency of analysis because the user does not need to reselect the options for Category, Property and Formatter every time they switch between graph elements.

### Possible Drawbacks
N/A

### Verification Process
Followed steps given in description of issue.

### Applicable Issues
#1129

2021-09-09 12:50 UTC, arcturus2 commented
Thanks @sol695510 it works well. Can you please add a what's new entry for this change to let users know?

2021-09-09 23:27 UTC, sol695510 commented
> Thanks @sol695510 it works well. Can you please add a what's new entry for this change to let users know?

What's New entry added.

2021-09-10 00:35 UTC, antares1470 requested changes
Found a bug. If you select a Category other than "Attribute" and then try choose a property, it resets the Category back to Attribute. I tested this in master as well and didn't encounter the issue.
![histogramStateBug](https://user-images.githubusercontent.com/62311243/132779907-733cdad6-379d-4001-8ebf-171e4e9702f4.gif)

2021-09-10 00:35 UTC, antares1470 commented on CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/whatsnew.txt
> +== 2021-09-10 Histogram View now save options chosen for Category and Property per Graph Element
I would simplify the title here to something like "Histogram View"

2021-09-13 23:25 UTC, antares1470 requested changes
Tested and not seeing that issue anymore

2021-09-13 23:25 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramState.java
> +            this.setElementState();
can omit the `this` keyword here

2021-09-13 23:25 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramState.java
> +            this.setElementState();
same here

2021-09-14 01:43 UTC, antares1470 approved these changes

2021-09-14 08:45 UTC, arcturus2 approved these changes
Works well. I resolved the merge conflict that came up with `whatsnew.txt` and will merge it in now.

2021-09-14 08:45 UTC, merged