Help Page Update 5
constellation-app/constellation pull request #1386
Opened 2021-09-10 04:24 UTC by antares1470

### Description of the Change

- updated all the help pages in the File Operations section (merged some pages together)
- updated all the help pages in the Visualisation section, moved Perspective Bookmarks to Views section
- updated all the help pages in the Selection section (merged some pages together), added some new pages as well
- updated all the analytic help pages
- updated some of the existing arrangement help pages and added a couple of new ones, removed help pages for Bubble Tree (temporarily until we add some proper help for it), Grid (General), and Clusters on Hilbert Curve

### Alternate Designs

### Why Should This Be In Core?

Updated help

### Benefits

More up to date help

### Possible Drawbacks

Nil

### Verification Process

### Applicable Issues

#340

2021-09-12 23:07 UTC, aldebaran30701 requested changes
Very thorough updates - Just some minor points but completely happy with this!

2021-09-12 23:30 UTC, Delphinus8821 approved these changes

2021-09-12 23:35 UTC, antares1470 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/docs/flatten-z-field.html
> +                    Arrange -&gt; Flatten Z Field
Ah I thought I got all those. Will make that change

2021-09-13 01:05 UTC, aldebaran30701 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/docs/flatten-z-field.html
> +            regardless of the current selection.
@antares1470 Just wondering your thoughts about this.

2021-09-13 01:49 UTC, antares1470 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/docs/flatten-z-field.html
> +            regardless of the current selection.
@aldebaran30701 I've made a mention of it essentially making the graph 2D. Let me know if you think that is sufficient

2021-09-13 22:16 UTC, aldebaran30701 approved these changes

2021-09-14 04:57 UTC, Atlas139mkm approved these changes

2021-09-14 06:11 UTC, arcturus2 approved these changes

2021-09-14 06:11 UTC, merged