Changed To image  ->  To screenshot image
constellation-app/constellation pull request #1391
Opened 2021-09-13 03:43 UTC by Atlas139mkm

### Description of the Change

Just changed the naming to be more self explanatory of what the action does.

![image](https://user-images.githubusercontent.com/88649439/133020431-275f99bd-adf3-4a44-a37e-0fa68654750c.png)

### Alternate Designs

### Why Should This Be In Core?

Better explanation of what it does.

### Benefits

UI UX

### Possible Drawbacks

### Verification Process

tested to see if the button still works - It does

### Applicable Issues
#1244

2021-09-13 04:38 UTC, antares1470 requested changes
There's also a reference to Image further down the help page. If you're able to change that one to Screenshot Image as well, that would be great

2021-09-13 04:38 UTC, antares1470 commented on CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/docs/export-from-constellation.html
>                      <img src="../image/exportToImage.png" alt="Export to Image Icon">
Are you able to change the alt here to "Export to Screenshot Image Icon"

2021-09-13 15:46 UTC, arcturus2 approved these changes

2021-09-13 22:02 UTC, antares1470 requested changes
There's also a reference to Image further down the help page. If you're able to change that one to Screenshot Image as well, that would be great

2021-09-14 00:06 UTC, antares1470 approved these changes

2021-09-14 00:06 UTC, merged