Import from File - Clearing the Search filters when all files are removed
constellation-app/constellation pull request #1396
Opened 2021-09-13 06:16 UTC by Auriga2

### Description of the Change
In the File importer, the table filter in the configuration Run panes and the Attributes filter will now be cleared when all the files are removed.

### Alternate Designs

### Why Should This Be In Core?

### Benefits

### Possible Drawbacks

### Verification Process

1. Open Import from file
2. Select a file for importing and watch the data populate on screen
3. Enter search criteria in the Filter in a few Run tabs
4. Enter in a search term into the Attributes section
5. Now I have decided that my data is incorrect so I remove the file using the red button
6. Check all the Filters above and verify they are cleared. 

### Applicable Issues
https://github.com/constellation-app/constellation/issues/1160

2021-09-13 08:14 UTC, arcturus2 approved these changes

2021-09-13 23:53 UTC, antares1470 requested changes
Testing looks good. If you could possibly add a whatsnew entry for this, that would be great

2021-09-14 01:42 UTC, antares1470 approved these changes

2021-09-14 05:28 UTC, arcturus2 approved these changes

2021-09-14 05:29 UTC, merged