display file name not full path in balloon notification
constellation-app/constellation pull request #1410
Opened 2021-09-16 06:17 UTC by Atlas139mkm

### Description of the Change

@GammaVel  hopefully this looks a bit better.

As per #1309 notification being to big due to the file path I have removed the path. Now it only displays the file names separated by a comma.

![image](https://user-images.githubusercontent.com/88649439/133559490-b0bba540-b402-4193-b35c-64c7582dc69b.png)
(it says the same file 3 times as its the only one I had. I added it 3 times)

### Alternate Designs

Have all file names on separate lines, however this was not possible due to the notification styles restrictions.

### Why Should This Be In Core?

Easier to read.

### Benefits

UX UI

### Possible Drawbacks

Can't see the full path in the notification. However they are still present in the file importer view.

### Verification Process

Ensured all relevant file names were posted

### Applicable Issues

#1309

2021-09-16 08:43 UTC, arcturus2 approved these changes

2021-09-16 22:44 UTC, antares1470 requested changes

2021-09-16 22:44 UTC, antares1470 commented on CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedPlugin.java
> +                    if (validFilenames.size() - 1 != i) {
are you able to move `i` to the LHS of this boolean statement?

2021-09-16 22:44 UTC, antares1470 commented on CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedPlugin.java
> +                        if (validFilenames.size() - 1 != i) {
similar here

2021-09-16 22:44 UTC, antares1470 commented on CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/delimited/ImportDelimitedPlugin.java
> +                    if (validFilenames.size() - 1 != i) {
and here

2021-09-17 00:54 UTC, antares1470 approved these changes
I didn't even pick up the fact that the last 2 should've been comparing to `invalidFilenames` rather than `validFilenames` so good pick up

2021-09-17 00:55 UTC, merged