Schema View Filter css
constellation-app/constellation pull request #1466
Opened 2021-10-01 02:28 UTC by antares1470

### Description of the Change

Have moved away from the temp solution for the schema view css  my making the needed minor adjustments to more align it with other filter search bars in other parts of the application while also solving the issue that the temp solution originally aimed to resolve.

### Alternate Designs

### Why Should This Be In Core?

Better style alignment across the application

### Benefits

More familiar style

### Possible Drawbacks

### Verification Process

### Applicable Issues

#841

2021-10-01 03:04 UTC, arcturus2 approved these changes

2021-10-05 03:41 UTC, Auriga2 requested changes
Changing the  `-fx-text-inner-color` hasn't fixed the issue when we handled it last time, as per the notes in https://github.com/constellation-app/constellation/issues/585. So I removed both these lines and it still works. Probably this was fixed by some other changes in between?

2021-10-05 22:24 UTC, aldebaran30701 approved these changes
Static code looks good, have not tested in the app.
Not sure if it is worth digging to find out what changed in the app that made this work as intended. just the fact that it works should be fine.

2021-10-06 01:52 UTC, Auriga2 approved these changes

2021-10-06 04:17 UTC, merged