Prevent exception of divide by zero in k-truss
constellation-app/constellation pull request #1604
Opened 2021-12-17 01:00 UTC by aldebaran30701

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Pane was resizing by diving by zero because of the `totalNeededHeight` variable. Adding a check to avoid dividing by zero seemed to prevent the exception. I have spend the last few hours trying to correct the actual problem of it being zero and checking if the current solution causes any detrimental behaviour but have not found anything.

I actually could not seem to create a graph that had nested k-trusses for testing. The pane will resize just as it did in previous versions on standard working graphs so I suspect this PR is fine.

### Alternate Designs
Tried to find alternate solution which involved avoiding the  case of zero being the variable value but came up short.

### Why Should This Be In Core?
Avoids exception to user by defensively checking variable values.

### Benefits
Avoids exception to user by defensively checking variable values.

### Possible Drawbacks
Possibly unfound drawbacks due to not being able to figure out how to trigger a nested ktruss.

### Verification Process
Creating and manipulating the ktruss view to try and throw an exception.
Using sphere graphs to test the functionality is not affected from this change. 
Toggling the up and down arrow 'V' and '^'

### Applicable Issues
#1460

2021-12-17 02:23 UTC, antares1470 requested changes

2021-12-17 02:23 UTC, antares1470 commented on CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/ktruss/NestedKTrussDisplayPanel.java
>          return expandHeight ? (y * PREFERRED_HEIGHT) / totalNeededHeight : y;
Given the return values here, could you potentially add your added if condition to the ternary below it?
i.e. `return expandHeight && totalNeededHeight > 0 ? ... : y`
I'm assuming here that `totalNeededHeight` isn't going negative but could also be changed from `>` to `!=` if need be

2021-12-17 02:23 UTC, antares1470 commented on CoreAlgorithmPlugins/src/au/gov/asd/tac/constellation/plugins/algorithms/clustering/ktruss/NestedKTrussDisplayPanel.java
>          return expandHeight ? (h * PREFERRED_HEIGHT) / totalNeededHeight : h;
similar here

2022-01-16 23:19 UTC, arcturus2 approved these changes

2022-01-17 03:56 UTC, antares1470 approved these changes

2022-01-17 03:56 UTC, merged