Add selected count to histogram display
constellation-app/constellation pull request #1605
Opened 2021-12-21 01:10 UTC by aldebaran30701

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Added a selected count to the histogram. First figure is the amount selected, the second is the total amount of bins.
![image](https://user-images.githubusercontent.com/58677759/146853308-ec4c4aa3-de13-473d-8cae-0fc67180590f.png)

### Alternate Designs

### Why Should This Be In Core?

### Benefits

### Possible Drawbacks

### Verification Process

### Applicable Issues

2022-01-16 22:43 UTC, Delphinus8821 approved these changes

2022-01-16 23:18 UTC, arcturus2 approved these changes

2022-01-17 04:05 UTC, antares1470 requested changes
If you're able to add a whatsnew as well that would be great

2022-01-17 04:05 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/BinCollection.java
> +    public Bin[] getSelectedBins() {
Are you able to add a unit test for this function you added (don't need to worry about the rest of the class)

2022-01-24 03:37 UTC, antares1470 commented on CoreHistogramView/test/unit/src/au/gov/asd/tac/constellation/views/histogram/BinCollectionNGTest.java
> +        Bin[] bins2 = new Bin[3];
This variable appears to be unused. Not sure if that was intentional?

2022-01-24 23:46 UTC, antares1470 approved these changes

2022-01-24 23:46 UTC, merged