Update width of Property Value text on Histogram
constellation-app/constellation pull request #1614
Opened 2022-01-21 03:29 UTC by Delphinus8821

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Updated the width of the property value text in the Histogram view to match the width of the text, rather than having some of the text cut off when longer labels are used. 
![Property Value Histogram](https://user-images.githubusercontent.com/73083035/150460496-65e318c6-da23-4e32-b28d-e8f61d2772cf.png)

### Alternate Designs
None realised 

### Why Should This Be In Core?
Stops he property value heading text and the text for the bin labels from being cut off.

### Benefits

### Possible Drawbacks
None realised 

### Verification Process

### Applicable Issues
#1600

2022-01-23 22:12 UTC, antares1470 requested changes
Looks good in testing. Just this one minor thing

2022-01-23 22:12 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +        int preferredTextWidth = getPreferredTextWidth(g);
final

2022-01-23 23:05 UTC, antares1470 approved these changes

2022-01-24 00:32 UTC, mimosa2 commented
Tested this. It works fine.

2022-01-24 00:34 UTC, mimosa2 approved these changes

2022-01-24 01:05 UTC, merged