Added DateTime Information to Logs
constellation-app/constellation pull request #1631
Opened 2022-02-04 02:24 UTC by Delphinus8821

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Added the local time to logs as they are displayed in the Constellation output window. 

### Alternate Designs

### Why Should This Be In Core?
Allows for the user to check when plugins were run using the information in the logs.

### Benefits

### Possible Drawbacks

### Verification Process

![image](https://user-images.githubusercontent.com/73083035/152461986-3e25807f-fd07-4279-984b-72576d357e07.png)

### Applicable Issues
#1058

2022-02-04 03:00 UTC, antares1470 requested changes
Are you possibly able to include the date as well? (you can use `LocalDateTime.now()`). Looks good otherwise

2022-02-04 04:23 UTC, antares1470 approved these changes

2022-02-07 00:04 UTC, arcturus2 approved these changes
Yes!!

2022-02-07 00:22 UTC, aldebaran30701 approved these changes

2022-02-07 01:24 UTC, merged