Show the directories in Table view export dialogs
constellation-app/constellation pull request #1667
Opened 2022-03-10 05:05 UTC by Auriga2

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Table view Export dialogs now display the folders along with the files of the relevant type.

### Alternate Designs

### Why Should This Be In Core?

### Benefits

### Possible Drawbacks

### Verification Process

1. Open a graph and go to the Table View
2. Click on the download option
3. Pick export to CSV
4. Verify the folders are displayed in the pop up window
5. Verify the folders are displayed in the folders at any level
6. Repeat with XLXS

### Applicable Issues
https://github.com/constellation-app/constellation/issues/1623

2022-03-10 21:33 UTC, antares1470 requested changes

2022-03-10 21:33 UTC, antares1470 commented on CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/components/ExportMenu.java
> +                        return file.isDirectory();
`return (file.isFile() && StringUtils.endsWithIgnoreCase(name, expectedFileExtension)) || file.isDirectory()`

2022-03-10 22:49 UTC, antares1470 approved these changes

2022-03-16 00:30 UTC, arcturus2 approved these changes

2022-03-16 01:07 UTC, merged