layers UI rework *WIP*
constellation-app/constellation pull request #1690
Opened 2022-05-03 00:25 UTC by aldebaran30701

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
This change is based off the design discussion in #1127 
It implements new UI components to bring up the consistency to that of the Data access view. 
![image](https://user-images.githubusercontent.com/58677759/166345760-87faaee8-285f-45d9-9f32-f40df902b722.png)

Error handling changes have been implemented within each query dialog based on recent changes to data access view error handling. The image below shows an incorrectly parsed query int he transaction section. When this occurs, the layer is disabled from being toggled, and the titlepane goes red as well as the specific query entry field. 
![image](https://user-images.githubusercontent.com/58677759/166345909-cfdfae32-d3de-4e1f-9d11-ad213205c9c0.png)

Outstanding work checklist:
* [x] Refresh layers without recreation of each titlepane object
* [ ] Ensure layer 0 is toggled when no other layer is enabled (visible feedback to the user that the complete graph is shown)
* [ ] Disable the checkbox in layer 0
* [ ] Correctly refresh the layers view when the current graph is switched or closed.

### Alternate Designs
Alternate designs have been discussed in detail within the main issue ticket. Implementation alternatives have not been discussed as yet.

### Why Should This Be In Core?
Enhances consistency of the UI elements throughout different Constellation Views
Enhances readability of queries and layers view workflow

### Benefits
as above

### Possible Drawbacks
none realised

### Verification Process
WIP

### Applicable Issues
#1127

2022-05-06 02:04 UTC, aldebaran30701 commented
I haven't managed to resolve all bugs, but the checkboxes in the description show the remaining tasks. 

To add onto this, the recent parameter values have not been fully implemented within the QueryInputPane. 

I also noticed there was one case when I entered an invalid query into Vertex section and both vertex and transaction query entries went red. Only the vertex field should do so.

2022-08-04 05:38 UTC, antares1470 requested changes
Are you able to add a whatsnew entry for this update. Also thinking it might be good to move this to the main views menu rather than leaving it in experimental if you're able to make that change as well

2022-08-04 05:38 UTC, antares1470 commented on CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/value/utilities/ExpressionUtilities.java
> +        // intentionally left blank
Are you able to throw an `IllegalStateException` here instead (similar to other utilities classes)

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewController.java
> +            LOGGER.log(Level.INFO, "Layer count maximum reached. Maximum is currently: {0}", BitMaskQueryCollection.MAX_QUERY_AMT);
Are you able to change the level to warning (just based on the line above it)

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewController.java
> +            Query txQuery = new Query(GraphElementType.TRANSACTION, "");
both queries can be final

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/LayersViewController.java
> +            LOGGER.log(Level.SEVERE, "is query visible already?: " + currentState.getVxQueriesCollection().getQuery(1).isVisible());
omit this log

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayerTitlePane.java
> +        enabledChanged = (ObservableValue<? extends Boolean> observable, Boolean oldValue, Boolean newValue) -> {
either make the lambda variables final or omit the explicit types

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayerTitlePane.java
> +        boolean validity = query.getQueryString() == null || ExpressionUtilities.testQueryValidity(query.getQueryString());
final

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayerTitlePane.java
> +        setValidity(validity);
given `setValidity(validity)` will do exactly what the line above it is doing, I think that line above can be removed

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayersViewPane.java
> +        CountDownLatch cdl1 = new CountDownLatch(1);
final

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayersViewPane.java
> +        } catch (InterruptedException ex) {
final

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayersViewPane.java
> +            LOGGER.log(Level.WARNING, ex.getMessage());
can you change this level to severe?

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayersViewPane.java
> +        CountDownLatch cdl1 = new CountDownLatch(1);
final

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayersViewPane.java
> +        } catch (InterruptedException ex) {
final

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayersViewPane.java
> +            LOGGER.log(Level.WARNING, ex.getMessage());
severe

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayersViewPane.java
> +            if (StringUtils.isEmpty(txqueryString) && StringUtils.isNotEmpty(vxqueryString)) {
are blank strings meant pass here? Wondering if it should be `isBlank` and `isNotBlank` respectively instead

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayersViewPane.java
> +                LayerTitlePane tp = new LayerTitlePane(queryIndex,queryDescription, bmq);
final

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayersViewPane.java
> +                LayerTitlePane oldTp = (LayerTitlePane) layersnew.getChildren().remove(queryIndex); // no 0 in list of 0
final

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayersViewPane.java
> +        if(totalLayers > iteratorEnd) {
are you able to add a space between `if` and `(` here?

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayersViewPane.java
> +        LayerTitlePane oldTp = (LayerTitlePane) layersnew.getChildren().remove(0);
final

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/NoGraphPane.java
> +    final Label noGraphLabel;
add an access modifier here (`protected` or `private`, whichever one is more suitable)

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/QueryInputPane.java
> +    public QueryInputPane(final LayerTitlePane parent, final String parameter, final String description, final String value, int defaultWidth, final boolean requiresValidityCheck) {
`defaultWidth` can be final

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/QueryInputPane.java
> +    public QueryInputPane(final LayerTitlePane parent, final String title, final String description, final String value, int defaultWidth, Integer suggestedHeight, final boolean requiresValidityCheck
same here

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/QueryInputPane.java
> +            protected void updateItem(String item, boolean empty) {
parameters final

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/QueryInputPane.java
> +            String recentValue = recentValuesCombo.getValue();
final

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/QueryInputPane.java
> +        field.addEventFilter(KeyEvent.KEY_PRESSED, (KeyEvent event) -> {
lambda parameter either final or explicit type removed

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/QueryInputPane.java
> +                IndexRange selection = field.getSelection();
final

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/QueryInputPane.java
> +        field.focusedProperty().addListener((ObservableValue<? extends Boolean> ov, Boolean t, Boolean t1) -> {
lambda parameters

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/QueryInputPane.java
> +        }
can you make this a ternary statement?

2022-08-04 05:38 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/query/Query.java
> +        long[] valueModificationCounters = new long[attributeIds.length];
final

2022-08-07 23:10 UTC, antares1470 commented on CoreLayersView/src/au/gov/asd/tac/constellation/views/layers/components/LayerTitlePane.java
> -        setValidity(validity);
Did you need to the layer re-colour to occur? If so, you probably want to keep the function call and remove the `this.isValid...` line instead

2022-08-07 23:29 UTC, antares1470 requested changes
Just did some testing as well. Found a few things:
1) Are you able to update the first screenshot in the help page? This is a screenshot of the old interface.
2) Looks like the right-click context menu may have the menus a little off with an extra layers menu. Are you able to fix that?
![LayersContextMenu](https://user-images.githubusercontent.com/62311243/183314953-7cbbfe6f-b7cf-4e1d-a76c-3ad0cd2c792e.png)
3) Looks like graph elements which are added to a layer via query aren't removed when the query is removed (only when the query is changed). Not sure what the intended behaviour is here but I would think those graph elements should be removed from the layer
![layersViewQueryIssue](https://user-images.githubusercontent.com/62311243/183315287-6cf61f27-c063-4e9c-b60b-803661ba8a7c.gif)

2022-08-08 01:50 UTC, Delphinus8821 commented
> Just did some testing as well. Found a few things:
> 
> 1. Are you able to update the first screenshot in the help page? This is a screenshot of the old interface.
> 2. Looks like the right-click context menu may have the menus a little off with an extra layers menu. Are you able to fix that?
> 3. Looks like graph elements which are added to a layer via query aren't removed when the query is removed (only when the query is changed). Not sure what the intended behaviour is here but I would think those graph elements should be removed from the layer
          
@antares1470 Points 1 and 3 should now be fixed.
Point 2 is something that has been occurring in the main branch since release v2.5. I will keep looking but at this stage I haven't found a fix for it.

2022-08-08 03:43 UTC, antares1470 commented
> > Just did some testing as well. Found a few things:
> > 
> > 1. Are you able to update the first screenshot in the help page? This is a screenshot of the old interface.
> > 2. Looks like the right-click context menu may have the menus a little off with an extra layers menu. Are you able to fix that?
> > 3. Looks like graph elements which are added to a layer via query aren't removed when the query is removed (only when the query is changed). Not sure what the intended behaviour is here but I would think those graph elements should be removed from the layer
> 
> @antares1470 Points 1 and 3 should now be fixed. Point 2 is something that has been occurring in the main branch since release v2.5. I will keep looking but at this stage I haven't found a fix for it.

Interesting. I'll create a separate ticket for point 2 then

2022-08-08 03:43 UTC, antares1470 approved these changes

2022-08-12 07:14 UTC, arcturus2 approved these changes
This has come a long way since I had a chance to look at it @aldebaran30701 @Delphinus8821.

The only issue I have found with the auto save feature is that because it regenerates the UI every time, it often looses the text area I had in focus so I have to click it twice. Seleting/Deselecting layers also requires a few goes. I would suggest looking at using an "Update" button instead.

Honestly, I started to get frustrated quickly when I had to click on the same location twice or 3 times.

2022-08-14 22:47 UTC, merged