Add option to specify timezone for Datetime formatters in Importers
constellation-app/constellation pull request #1705
Opened 2022-05-16 03:24 UTC by Auriga2

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Users can specify the input time zone used in the Datetime fields in imported data files. 

Right-click on the `Datetime` transaction attribute and navigate to `Formatter` -> `Datetime` then select the `Time Zone`. 

It'll be empty by default which will display the formatted columns as if they are in GMT, similar to the previous behavior.
![image](https://user-images.githubusercontent.com/64826928/168514416-0b0b8239-69b8-4012-975b-f191ab4f4abf.png)

When a value is selected:
![image](https://user-images.githubusercontent.com/64826928/168514528-43a1e880-0746-4e09-ac8f-262939ff4e6c.png)

### Alternate Designs
n/a

### Why Should This Be In Core?
Better ux

### Benefits

This is specially useful when Excel files are imported where the Excel datetime number doesn't contain time zone information.

### Possible Drawbacks

### Verification Process

1. Open Constellation and the File Importer
2. Load a file in to the importer containing date time columns of different formats
3. Right-click on the Datetime transaction attribute
4. Navigate to Formatter -> Datetime
5. Select different formats and time zones and verify the datetime values in the table format correctly.
6. Click `Import button and check the date time column is imported in the graph with the specified time zone.
7. Test a custom format with the time zone and see if it retains when the  time zone field is left blank but overwrites when a value is specified.

### Applicable Issues
https://github.com/constellation-app/constellation/issues/1673

2022-05-18 00:47 UTC, antares1470 requested changes
Few things I found from testing:
1) Given this is just changing the actual timezone as appose to converting to a timezone, I wonder whether this is actually addressing #1698 instead. #1673 is more about converting the datetime to the preferred timezone as apposed to specifying the timezone itself. If it is addressing #1698, I think it would be good if possible to disable the timezone field when you select a datetime format that already contains one

2) I've noted that when going through the list of timezones that a) they weren't all in timezone order (started out fine but got a bit muddled in the middle), and b) some of the zones didn't match up (e.g. had +5:00 (GMT -5) and vise-versa)

3) Converting timezones after applying the attributes appears to have some issues. I'll update this with a gif demonstrating but basically I changed to a timezone of +0:00 and it applied in one row as -1:00 and another row as -1:54 (both of which are obviously wrong)

2022-05-18 00:47 UTC, antares1470 commented on CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/translator/DatetimeAttributeTranslator.java
> +        if (!StringUtils.isBlank(timeZone)) {
`StringUtils.isNotBlank`

2022-05-18 00:47 UTC, antares1470 commented on CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/translator/DatetimeAttributeTranslator.java
> +        if (!StringUtils.isBlank(timeZone)) {
same here

2022-05-23 07:29 UTC, Auriga2 commented
@antares1470 For (1) you said you'll let me know whether we still need a time zone converter in the importers because we can already convert them in the Attribute editor. There we can convert on one transaction or a bulk selected (different times will be replaced with the time you enter-so not really useful?) , but couldn't fine a global time zone setting in Graph attributes as @arcturus2 mentioned. (Could it be available somewhere else?)

2022-05-23 22:48 UTC, antares1470 commented
> @antares1470 For (1) you said you'll let me know whether we still need a time zone converter in the importers because we can already convert them in the Attribute editor. There we can convert on one transaction or a bulk selected (different times will be replaced with the time you enter-so not really useful?) , but couldn't fine a global time zone setting in Graph attributes as @arcturus2 mentioned. (Could it be available somewhere else?)

@Auriga2 so there isn't a global timezone graph attribute. The datetimes and their timezones are all local to the node/transaction. Yes you can convert to the desired timezone in the attribute editor, but I still think it would be good to include an option to convert the timezone in the importer as I describe in #1673. That though is more a quality-of-life improvement (so that you don't have to then go to the attribute editor afterwards). Your current solution here though definitely seems more like it is aiming to fix #1698 which is focused on ensuring data with no timezone specified can still be correctly imported.

2022-05-24 00:00 UTC, Auriga2 commented
Agree that this is fixing the https://github.com/constellation-app/constellation/issues/1698. Updated the description here. I'll add a separate PR for https://github.com/constellation-app/constellation/issues/1673

2022-05-25 01:31 UTC, Auriga2 commented
These are the possible formats with time zones:
The Z (Zulu) on the end means UTC. that is, an offset-from-UTC of zero hours-minutes-seconds. 
 E.g.
"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"(eg  "2011-08-12T20:17:46.384Z")
 yyyy-MM-dd'T'HH:mm:ss'Z'(eg "2015-09-29T18:46:19Z")
 
These as a custom format, but I couldn't find a proper format string to get them formatted in consty yet.
 YYYY-MM-DDThh:mm+hh:mm (eg 1997-07-16T19:20+01:00)
YYYY-MM-DDThh:mm:ss+hh:mm (eg 1997-07-16T19:20:30+01:00)
YYYY-MM-DDThh:mm:ss.s-hh:mm (eg 1997-07-16T19:20:30.45-01:00)

 YYYY-MM-DD'T'HH:mm:ss Z ?(eg  2016-06-10T13:53:22 +0200)

2022-05-26 01:14 UTC, Auriga2 commented
Looks like there could be many time zone formats the [DateTimeFormatter ](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#:~:text=Offset%20X%20and%20x%3A%20This,%2C%20such%20as%20'%2B0130') can handle. I could see below formats working in consty. 
yyyy-MM-dd'T'HH:mmXXX (eg 1999-07-16T19:20-03:30)
yyyy-MM-dd HH:mm:ss.SSS XXX (eg 2020-05-09 22:14:14.037 +09:00)
yyyy-MM-dd'T'HH:mm:ssXX (eg 2016-06-10T13:53:22+0400)

I'll add a check assuming any format with trailing **X** and **'Z'** as containing time zone information.
Should probably also add trailing lowercase **x**, **O, V**

![image](https://user-images.githubusercontent.com/64826928/170394449-e95b1667-83f4-4f47-b5ac-9d16e12651ab.png)
![image](https://user-images.githubusercontent.com/64826928/170394642-dc3807f2-8664-4587-8059-abc6dd31c6fc.png)

2022-05-26 22:59 UTC, antares1470 requested changes
A few things I found (on top of the code comments above yet to be changed):

1) Epoch is measured from GMT and so should disable the timezone parameter when selected
2) When the datetime attribute is applied, there is a check for whether the timezone parameter is empty, but no check if it is disabled. This means currently that if you select a value in the parameter before it gets disabled and then apply that attribute, it will still use the timezone value picked (disabling doesn't remove the value, simply removes the ability to change it)

Side note: If you're also able to include a whatsnew for this, that would be great

2022-05-30 22:30 UTC, antares1470 requested changes

2022-05-30 22:30 UTC, antares1470 commented on CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/translator/DatetimeAttributeTranslator.java
> +    private boolean containsTimeZone(String format){
parameter final

2022-05-30 22:30 UTC, antares1470 commented on CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/translator/DatetimeAttributeTranslator.java
> +        if ( timeZoneParam.isEnabled() && !StringUtils.isBlank(timeZone)) {
`!StringUtils.isBlank(timeZone)` -> `StringUtils.isNotBlank(timeZone)`

2022-05-30 22:30 UTC, antares1470 commented on CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/translator/DatetimeAttributeTranslator.java
> +        if (timeZoneParam.isEnabled() && !StringUtils.isBlank(timeZone)) {
same here

2022-06-02 01:59 UTC, antares1470 approved these changes

2022-06-15 01:37 UTC, mimosa2 approved these changes

2022-06-15 02:13 UTC, Delphinus8821 approved these changes

2022-06-15 23:29 UTC, merged