Improvements to GitHub Actions
constellation-app/constellation pull request #1714
Opened 2022-06-08 11:31 UTC by arcturus2

### Prerequisites

- [X] Reviewed the [checklist](CHECKLIST.md)

- [X] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Based on work done in https://github.com/constellation-app/constellation-applications/pull/8 I have updated the GitHub actions here to align with this. Some improvements are as follows:

* Use the base Ubuntu image for most of the work
* Use addnab/docker-run-action@v3 to run the docker image
* :racehorse: Reuse Ivy caching
* Minor label improvements
-->

### Alternate Designs

### Why Should This Be In Core?

### Benefits

The `.ivy2` cache was not being restored which meant dependencies were being downloaded in every release. This has been fixed to work which saves 1.5 minutes off the build time

Some quality of life improvements which should make it easier to read the workflows and maintain them in the future

### Possible Drawbacks

### Verification Process

### Applicable Issues

2022-06-08 22:41 UTC, antares1470 requested changes
Looks like there is an issue with one of the scripts based on the CI result

2025-09-29 22:43 UTC, Delphinus8821 approved these changes
Do the formatting changes to that unit test need to be included here?

2025-09-29 23:00 UTC, antares1470 commented
> Do the formatting changes to that unit test need to be included here?

With respect to the primary changes being made, the unit test change probably doesn't need to be included. They were there from when @arcturus2 previously worked on it. I can remove them if you'd like though the changes themselves aren't overly problematic (i.e. really just fixing formatting)

2025-09-29 23:21 UTC, Delphinus8821 commented
> > Do the formatting changes to that unit test need to be included here?
> 
> With respect to the primary changes being made, the unit test change probably doesn't need to be included. They were there from when @arcturus2 previously worked on it. I can remove them if you'd like though the changes themselves aren't overly problematic (i.e. really just fixing formatting)

Happy either way, just thought the changes didn't seem very relevant

2025-10-01 23:56 UTC, Quasar985 approved these changes

2025-10-02 00:30 UTC, merged