#1580
constellation-app/constellation pull request #1716
Opened 2022-06-15 13:48 UTC by spica198

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Make sure to request focus to EnhancedTextArea every time text area is loaded to ensure cached text been wrapped correctly.

### Alternate Designs

### Why Should This Be In Core?

### Benefits

### Possible Drawbacks

### Verification Process

1. Open (or create) a graph with content in the transactions
2. Open Conversation View, ensure content is displayed in view

Expected behaviour: All text in a bubble is visible from the outset

### Applicable Issues

#1580

2022-06-20 02:05 UTC, antares1470 requested changes
It looks like from testing that I'm still seeing the issue. I tried both an existing graph and creating a new graph. See the attached gif (this is a new graph):
![conversationBubbleIssue2](https://user-images.githubusercontent.com/62311243/174512791-687d2ff9-4b27-4dbd-b438-9783be7365fa.gif)

2022-07-13 23:09 UTC, antares1470 approved these changes

2022-07-14 22:51 UTC, arcturus2 approved these changes
Looks good thank you @spica198

2022-07-18 02:08 UTC, mimosa2 approved these changes

2022-07-19 01:10 UTC, merged