Find View UI Improvements
constellation-app/constellation pull request #1734
Opened 2022-07-20 00:23 UTC by altair1673

### Prerequisites

- [X] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Changed title from "Find View" to "Find". In the "Basic Find" tab, "In Attributes" label has been updated to "Search Attributes". All attributes are selected by default. 
In the "Advanced Find" tab the number of matches found is displayed.
The "Match Criteria" and "Current Selection" labels have been spaced out.
Updated the "Ignore Case" label in advanced find tab.
Decided not to update strings in the "Look for" drop down to plural as it would impact code in other areas of the codebase.

### Alternate Designs

### Why Should This Be In Core?
Improves user experience.

### Benefits
Improves readability of UI text elements. Adds in features that were available in the old find view which improves experience.

### Possible Drawbacks

### Verification Process
Unit tests pass, UI is readable and well spaced out.

### Applicable Issues
#1692

2022-07-21 01:17 UTC, antares1470 requested changes
Thanks @altair1673, most of it seems alright in testing. One thing though is that I think the text for the advanced find result count blends in a little too well with the rest of the UI where it currently is. Might be helpful to either move that label below all the different queries (above the Find buttons) or potentially display in the same way the old Find view did (which I think is via the PluginInteraction object)
![newFindAdvanced](https://user-images.githubusercontent.com/62311243/180108675-33b3d9d8-cb33-474c-ac65-ee705e11c951.png)

Also, if you are able to make it such that the label isn't visible at all when there isn't any search, that I think would be a nice inclusion.
![newFindAdvanced2](https://user-images.githubusercontent.com/62311243/180108829-4086412e-9da6-44f1-87c3-3ae8799a25b8.png)

2022-07-21 01:17 UTC, antares1470 commented on CoreFindView/src/au/gov/asd/tac/constellation/views/find2/FindViewController.java
> +        AdvancedSearchPlugin advancedSearchPlugin = new AdvancedSearchPlugin(currentAdvancedSearchParameters, findAll, findNext);
can you make this final?

2022-07-21 01:17 UTC, antares1470 commented on CoreFindView/src/au/gov/asd/tac/constellation/views/find2/FindViewController.java
> +    public void setNumResultsFound(int value) {
are you able to make the parameter final?

2022-07-21 01:17 UTC, antares1470 commented on CoreFindView/src/au/gov/asd/tac/constellation/views/find2/plugins/advanced/AdvancedSearchPlugin.java
> +
are you able to remove some of the extra newlines here?

2022-07-21 01:17 UTC, antares1470 commented on CoreFindView/src/au/gov/asd/tac/constellation/views/find2/plugins/advanced/AdvancedSearchPlugin.java
> +        LOGGER.log(Level.SEVERE, "Running edit method");
Are you able to remove this log entry?

2022-07-21 01:17 UTC, antares1470 commented on CoreFindView/src/au/gov/asd/tac/constellation/views/find2/plugins/advanced/AdvancedSearchPlugin.java
> +
similar here

2022-07-22 00:55 UTC, antares1470 requested changes
Managed to get this exception which I confirmed isn't occurring in master:
```
java.lang.IllegalArgumentException: Children: duplicate children added: parent = Grid hgap=0.0, vgap=0.0, alignment=TOP_LEFT
	at javafx.graphics/javafx.scene.Parent$3.onProposedChange(Parent.java:558)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.add(VetoableListDecorator.java:206)
	at javafx.graphics/javafx.scene.layout.GridPane.add(GridPane.java:974)
	at au.gov.asd.tac.constellation.views.find2.components.AdvancedFindTab.updateButtons(AdvancedFindTab.java:208)
	at au.gov.asd.tac.constellation.views.find2.components.FindViewTabs.lambda$new$0(FindViewTabs.java:52)

```
Reproducer: Open new Find View, switch to Advanced Tab, switch to Basic Tab, switch to Advanced Tab.

I think you might have also missed one of my comments from my previous review (which I've unresolved)

2022-07-22 02:19 UTC, antares1470 approved these changes

2022-07-22 03:16 UTC, Delphinus8821 approved these changes

2022-07-24 22:27 UTC, merged

2022-08-22 00:59 UTC, GammaVel commented
Thanks  @altair1673 for making these improvements to the new Find view. They are looking great. Understand that you could not implement the plural for Node, Transaction and Edge but I don't think it is a big issue. 

I have gotten a couple of runtime errors when using the new Find functionality but they are not related to your updates. I will keep following up to see if they can be replicated and if so, raise new issues. 

Thanks again @altair1673 !