Added No Query Error Message
constellation-app/constellation pull request #1737
Opened 2022-07-21 07:21 UTC by altair1673

### Prerequisites

- [X] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
When no query is entered by the user an error message shows up.

### Alternate Designs

### Why Should This Be In Core?
Improves usability

### Benefits
Reduces user confusion when they click "Query" button with no query text and nothing happens.

### Possible Drawbacks

### Verification Process
Clicked "Query" with no text or with just spaces and the error message showed up.

### Applicable Issues
#1626

2022-07-21 23:06 UTC, antares1470 requested changes

2022-07-21 23:06 UTC, antares1470 commented on CoreImportExportPlugins/src/au/gov/asd/tac/constellation/plugins/importexport/jdbc/JDBCSourcePane.java
> +                NotifyDisplayer.displayLargeAlert("JDBC Import", "No Query Entered",
Are you able to possibly change this from `displayLargeAlert` to `displayAlert`? Given the size of the message, I think the latter should be ok.

2022-07-22 00:56 UTC, antares1470 approved these changes

2022-07-22 03:26 UTC, Delphinus8821 approved these changes

2022-07-25 00:00 UTC, merged