Bug with Searching Only Selected Nodes Is Fixed
constellation-app/constellation pull request #1741
Opened 2022-07-28 07:24 UTC by altair1673

### Prerequisites

- [X] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Changed variable at the top so that all nodes would keep being selected when the "Ignore" option is set.

### Alternate Designs

### Why Should This Be In Core?
Can properly advance search "Selected" nodes.

### Benefits
Stops confusion as to why selected nodes were being deselected.

### Possible Drawbacks

### Verification Process
Cannot re-create the bug anymore going through the same methods.

### Applicable Issues
#1694

2022-07-28 23:12 UTC, antares1470 requested changes

2022-07-28 23:12 UTC, antares1470 commented on CoreFindView/src/au/gov/asd/tac/constellation/views/find2/plugins/advanced/AdvancedSearchPlugin.java
> +                            //LOGGER.log(Level.SEVERE, "INSIDE SELECT ANY");
can you remove this line? I assume the logger imports were also for this so if that's the case, if you're able to remove those as well that would be great

2022-07-28 23:12 UTC, antares1470 commented on CoreFindView/src/au/gov/asd/tac/constellation/views/find2/plugins/advanced/AdvancedSearchPlugin.java
> +                // BUG IS HERE!!!
remove this comment as well (hopefully should no longer be a bug there 😄)

2022-07-31 23:35 UTC, antares1470 approved these changes

2022-08-02 22:24 UTC, Delphinus8821 approved these changes

2022-08-02 23:13 UTC, merged