DAV String Dropdown List Width
constellation-app/constellation pull request #1751
Opened 2022-08-08 22:31 UTC by Delphinus8821

### Prerequisites

- [X] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Updated the string dropdown lists from being able to show text longer than the Constellation window.

### Alternate Designs
N/A

### Why Should This Be In Core?
Stops text from being displayed in a way that is hard to read and extends off of the main window.

### Benefits
Easier readability.

### Possible Drawbacks
N/A

### Verification Process
Entered a long string into the Extract Types from Text plugin in DAV and observed that the width of the text in the dropdown list is set to a max size.

### Applicable Issues
#1686

2022-08-08 23:45 UTC, antares1470 requested changes
Is it possible to have it such that the width of the dropdown options cell corresponds to the length of the text until it reaches that largest preferred width? When I tested it, it seemed to do it for very small text lengths but once it got long enough it expanded up to that max width, even though the text still hadn't reach there.
![recentValuesLength](https://user-images.githubusercontent.com/62311243/183533133-f5967a0c-eb95-48f0-96b2-ebb98a034d18.gif)

2022-08-08 23:45 UTC, antares1470 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/ValueInputPane.java
> +                        public void updateItem(String item, boolean empty) {
parameters can be final

2022-08-09 01:27 UTC, antares1470 approved these changes

2022-08-09 04:41 UTC, arcturus2 approved these changes

2022-08-09 22:29 UTC, merged