Adding help text for DAV configure catergories
constellation-app/constellation pull request #1763
Opened 2022-09-15 02:35 UTC by mimosa2

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Added help text for configuring data access view categories.

### Alternate Designs

### Why Should This Be In Core?

### Benefits

This information is handy to the users.

### Possible Drawbacks

### Verification Process

Open the Data Access View and click the help guide link. Check the Data Access Categories section.

### Applicable Issues

2022-09-18 22:47 UTC, Delphinus8821 approved these changes

2022-09-26 01:34 UTC, antares1470 requested changes
I note the original ticket (#1681) also wanted a page under Preferences for the Data Access View tab (similar to other preference tabs). Not sure whether it might be worth creating a page for the preference tab containing what you've included, and then the Data Access View page simply refers the user to that page if they want to find out more about it

2022-09-26 01:34 UTC, antares1470 commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/docs/data-access-view.md
> +You can hide data access categories by selecting Setup -> Options -> CONSTELLATION -> Data Access View
are you able to change "->" to "-\&gt;"?

2022-10-04 00:55 UTC, antares1470 requested changes

2022-10-04 00:55 UTC, antares1470 commented on CorePreferences/src/au/gov/asd/tac/constellation/preferences/docs/dataaccess-category-preferences.md
> +# Data Access View Category Preferences
Are you able to rename this to "Data Access View" since that is the name of the tab in preferences

2022-10-04 00:55 UTC, antares1470 commented on CorePreferences/src/au/gov/asd/tac/constellation/preferences/docs/preferences-toc.xml
> +        <tocitem text="DataAccessView Categories" target="au.gov.asd.tac.constellation.preferences.dataaccessview"/>
same here

2022-10-05 05:05 UTC, antares1470 approved these changes

2022-10-05 05:05 UTC, merged