Updated Constellation Options Tabs
constellation-app/constellation pull request #1774
Opened 2022-10-19 05:00 UTC by Delphinus8821

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Updated order of menu tabs so they are listed in alphabetical order.

Combined some menu tabs to reduce over number of tabs. The Application Font and Anaglyphic Display tabs are now included under the Application tab. These were chosen to be moved as they contained the smallest number of options and do not take up a full window on their own. 

Fixed the paths for some existing help pages that were not able to be accessed. 

Note: there was an attempt to move the settings from the Online Help tab into the Application tab but this created a cyclic dependency. 

### Alternate Designs
N/A

### Why Should This Be In Core?
Reduces to number of options tabs that only contain one or two options. 

### Benefits
Having the tabs in alphabetical order increases readability and ease of finding the options quickly. 

### Possible Drawbacks
More options are included under the Application tab, meaning that users must scroll to see some of them.

### Verification Process
Checked each of the options to ensure they all still function.
Checked that the option help pages link to the correct pages. 

### Applicable Issues
#1679

2022-10-19 22:19 UTC, Delphinus8821 commented
I have reviewed the code smells and majority of them occur in the generated code for the options panel where they cannot be edited.

2022-10-20 04:54 UTC, antares1470 requested changes
Couple of things:
1) Could you possibly move the anaglyphic display options to the graph panel instead? Since they only affect a graph display rather than the whole application.
2) Could you update the Changlog with the changes made? Possibly a whatsnew entry as well since users will see these changes

2022-10-20 04:54 UTC, antares1470 commented on CorePreferences/src/au/gov/asd/tac/constellation/preferences/ApplicationPreferenceKeys.java
> +    public static final boolean ONLINE_HELP = false;
I think this one is still meant to be in `HelpPreferenceKeys`

2022-10-20 04:54 UTC, antares1470 commented on CorePreferences/src/au/gov/asd/tac/constellation/preferences/docs/application-preferences.md
> +CONSTELLATION -> Application.
I think this was just the opening to the old help page so this could probably be omitted

2022-10-23 23:43 UTC, antares1470 requested changes
Looking good. The only thing I noted is that the screenshot in the Data Access View Preferences help page is now a little out of date. Are you possibly able to update that?

2022-10-24 00:16 UTC, antares1470 approved these changes

2022-10-25 03:41 UTC, OrionsGuardian reviewed
Can we add a title/label for the Blaze colours. The unlabeled panel looks out of place with the other panels having a title and label for their settings.

2022-10-25 03:41 UTC, OrionsGuardian commented on CorePreferences/src/au/gov/asd/tac/constellation/preferences/GraphOptionsPanel.java
> +    private JPanel jPanel3;
Would prefer to see better named variables here.

2022-10-25 04:55 UTC, OrionsGuardian approved these changes

2022-10-25 21:52 UTC, merged