Improve Current Selection in New Find View
constellation-app/constellation pull request #1799
Opened 2023-01-15 22:32 UTC by Delphinus8821

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Updated the current selection drop down list in the new find view and split it into two drop downs, search in and post results action. The search in drop down shows where the search will be performed, e.g. the current selection, current graph or all open graphs. The post search actions drop down has the option to choose whether the search will replace the current selection, add to or remove from the current selection. 

A delete results button was also added to delete results from the graph quickly. It only becomes available after a find all search as it will delete all results found. After pressing the delete results button, the user is then displayed a dialog box which shows how many results will be deleted across x graphs and whether they wish to continue deleting these. 
The delete results option was originally going to be added as part of the Post Search Actions drop down but it was discovered that unless the search with the same results had already been made using a different option in the Post Search Actions drop down, completing the delete results option would cause Constellation to become unresponsive. 

These new options appear in both the basic find and the advanced find. 

### Alternate Designs
N/A

### Why Should This Be In Core?
Improves the usability of the new find view by expanding the different options. Also adds new functionality of being able to delete results from within the find view. 

### Benefits
Easier use of the new find view. 

### Possible Drawbacks

### Verification Process
Tested all options in both drop down lists on both the basic find and the advanced find to ensure all functionality still works as intended. 
Also tested the delete option on both tabs. 

### Applicable Issues
#1695

2023-01-17 01:15 UTC, antares1470 requested changes
Some other things from testing:
- When the post-action option is Replace Selection, Find All doesn't highlight any of the found terms and Find Next and Previous append to the selection
- In the Replace tab I'm a bit confused to what "Replace In" means. Replace in this case also seems to have 2 different meanings in this tab (with respect to text and with respect to selection) which I think might be confusing
- I would possibly look at the Delete Results button being a Post-search action option instead. I do like the inclusion of the prompt to check beforehand but I think it doesn't really make sense to be a separate button.
- The term "Delete Results" can also be a little confusing. When I first saw it, I interpreted it as clearing the search rather than deleting things from the graph

2023-01-17 01:15 UTC, antares1470 commented on CoreFindView/src/au/gov/asd/tac/constellation/views/find2/components/BasicFindTab.java
> +        postSearchChoiceBox.getSelectionModel().selectedItemProperty().addListener(new ChangeListener<String>() {
can the listener here and the one above be converted to a lambda? Or is there an issue with doing that? (If there's a problem, make the parameters final in the function)

2023-01-17 01:15 UTC, antares1470 commented on CoreFindView/src/au/gov/asd/tac/constellation/views/find2/plugins/BasicFindPlugin.java
> +                || (!this.parameters.isSearchAllGraphs() && ActiveFindResultsList.getBasicResultsList() == null && ActiveFindResultsList.getBasicResultsList().get(0) != null
`ActiveFindResultsList.getBasicResultsList() == null && ActiveFindResultsList.getBasicResultsList().get(0) != null` would appear to cause an issue (if the 1st is true, the 2nd will throw a null pointer)

2023-01-17 01:15 UTC, antares1470 commented on CoreFindView/src/au/gov/asd/tac/constellation/views/find2/plugins/advanced/AdvancedSearchPlugin.java
> +                && ActiveFindResultsList.getAdvancedResultsList().get(0) != null && !ActiveFindResultsList.getAdvancedResultsList().get(0).getGraphId().equals(graph.getId()))) {
Similar here

2023-01-17 04:27 UTC, antares1470 requested changes
Given there is only one option now for the Post actions in the Replace tab, is it possible for that dropdown to be removed?

2023-01-17 21:42 UTC, antares1470 approved these changes

2023-01-23 05:46 UTC, mimosa2 commented
I tested Basic Find with All Open Graphs and Find All picked up all the hits but I had the default Post-Search Action option as Add To Selection. This option didn't enable Find Prev and Find Next although there were results in the other graphs (they all high lighted correctly).
 I had the similar situation the when the default was set to Remove from Selection.  Is it possible to make no default option for this drop down ( Post-Search Action)?

2023-01-24 00:55 UTC, mimosa2 commented
After discussed with @Delphinus8821 and @antares1470  I understood that The Find Next & Previous are not meant to be enabled for Add To or Remove From options.

2023-01-24 00:56 UTC, mimosa2 approved these changes

2023-01-24 01:11 UTC, merged