Child plugin messages should be reported hierarchically through parent plugin.
constellation-app/constellation pull request #1803
Opened 2023-01-24 03:29 UTC by OrionsGuardian

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

When viewing the plugin messages through the Plugin Reporter:
Child plugin messages will now be shown as part of a hierarchy of messages originating from a parent plugin.

### Alternate Designs

N/A

### Why Should This Be In Core?

For improved readability of plugin messages in the Plugin Reporter.

### Benefits

Seeing the hierarchy of messages in the Plugin Reporter provides an addition means of tracking the program flow.

### Possible Drawbacks

N/A

### Verification Process

Use the Analytic View to run some metrics on a graph.
Look at the plugin messages in the Plugin Reporter to confirm child messages are contained within parent messages.

Can also test in the Data Access View -> Test Parameters (Batched)
Confirm the child messages shown in the Plugin Reporter are contained within parent messages.

### Applicable Issues

#323

2023-02-13 01:10 UTC, Delphinus8821 approved these changes

2023-02-15 01:21 UTC, antares1470 requested changes
Looks good testing-wise

2023-02-15 01:21 UTC, antares1470 commented on CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewPane.java
> +                    protected void execute(PluginGraphs graphs, PluginInteraction interaction, PluginParameters parameters) throws InterruptedException, PluginException {
can you make the parameters final?

2023-02-15 01:21 UTC, antares1470 commented on CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewPane.java
> +                        } catch (InvocationTargetException ex) {
exception final

2023-02-15 01:21 UTC, antares1470 commented on CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/AnalyticViewPane.java
> +                    LOGGER.log(Level.SEVERE, ex.getLocalizedMessage());
Can you separate the `InterruptedException` and add a `Thread.currentThread().interrupt()`?

2023-02-16 23:07 UTC, antares1470 approved these changes

2023-02-16 23:07 UTC, merged