Created global thread pool object that classes can call when another thread is needed
constellation-app/constellation pull request #1808
Opened 2023-03-01 05:57 UTC by altair1673

### Prerequisites

- [X] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Whenever a class needs a new thread, a new thread pool was being created. Now there are global thread pool objects that can be called when one or more threads are needed. This reduces overhead since creating a new thread pool every time is not efficient.
### Alternate Designs

### Why Should This Be In Core?

Potentially boost the speed of certain aspects of the app now that there is a shared thread pool now.
Cleaner code
### Benefits

Make things faster since overhead is reduced. (This still needs to be tested so we know exactly which components are faster).
### Possible Drawbacks

Josh mentioned that some components might need their own thread pools but so far everything looks good.
The help modules doesn't use the new thread pool class since there is a cyclic dependency between it and the utilities module.
### Verification Process

Speed still needs to be tested.
But components seem to be working fine.

### Applicable Issues

#1504

2023-03-15 03:20 UTC, Delphinus8821 approved these changes

2023-04-05 23:50 UTC, OrionsGuardian commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/templates/WorkflowQueryPlugin.java
> +        // THERE IS A POSSIBLE BUG HERE, GO BACK TO OLD METHOD IF ANY ISSUES
POSSIBLE BUG? .... Is this comment still appropriate?

2023-04-13 00:19 UTC, antares1470 requested changes
Are you possibly able to add an entry for this to the changelog? This would probably be a good change for developers to be aware of

2023-04-13 00:19 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/threadpool/UniversalThreadPool.java
> +public class UniversalThreadPool {
Can we rename this to something like `ConstellationGlobalThreadPool`? Universal doesn't seem quite like the correct wording here (as it really is only for Constellation code use)

2023-04-13 00:19 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/threadpool/UniversalThreadPool.java
> + * This class holds global objects for the variouse thead pools needed by the
"various thread"

2023-04-13 00:19 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/threadpool/UniversalThreadPool.java
> +
can you remove the blank line here

2023-04-13 01:06 UTC, antares1470 requested changes

2023-04-13 01:06 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/threadpool/UniversalThreadPool.java
> +public class UniversalThreadPool {
One other thing I missed before, are you able to write some unit tests for this class?

2023-04-14 01:51 UTC, antares1470 requested changes
If addition to the comments, it looks like CI is failing, possibly some other places you need to edit in light of changes made after my comments

2023-04-14 01:51 UTC, antares1470 commented on CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/threadpool/ConstellationGlobalThreadPoolNGTest.java
> +import static org.testng.Assert.*;
are you able to change this import to only include the classes actually being used?

2023-04-14 01:51 UTC, antares1470 commented on CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/threadpool/ConstellationGlobalThreadPoolNGTest.java
> +    }
Is there a way you can add to this test (and others) to demonstrate that the object you get back is what you're expecting (i.e. some asserts about the stuff in the object itself)? e.g. Perhaps demonstrating that you get the same object back if you call it a second time?

Acknowledge that there isn't much to those functions that you can really test but at present, the test is only really checking that what you returned matched the return type of the function...which doesn't really demonstrate anything about the function (if the return type didn't match, you'd get compilation errors)

2023-04-16 22:41 UTC, antares1470 commented on CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/threadpool/ConstellationGlobalThreadPoolNGTest.java
> +        assertEquals(s1 == s2, true);
Might be worth adding a comment explaining that you're checking that a new instance isn't being created the 2nd time the function is called (based on the function implementation). Similar thing for the other tests

2023-04-20 23:11 UTC, antares1470 approved these changes

2023-04-26 02:01 UTC, merged