Users can gives notes a custom colour
constellation-app/constellation pull request #1809
Opened 2023-03-02 05:30 UTC by altair1673

### Prerequisites

- [X] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Notes are by default this purple colour but now the user can use a JavaFX colour picker thats on every note to give it a custom colour.
### Alternate Designs

### Why Should This Be In Core?
Gives users to differentiate between notes. Eg. More important notes could be coloured in red so the user can prioritize those.

### Benefits

Better organization of notes.
Notes View can have visually appealing colours.
### Possible Drawbacks

Since each note has a colour option the UI could look cluttered
### Verification Process

Colour of note changes depending on whatever is chosen. Notes retain colour since it is saved in state.
### Applicable Issues

#1760

2023-03-03 04:41 UTC, Delphinus8821 requested changes
A few bugs found with testing
A null pointer when opening an older graph that includes user notes:
![image](https://user-images.githubusercontent.com/73083035/222632851-c1cc5e9f-5bef-4011-b2c5-fb8de2e35b6f.png)

Auto notes are no longer blue:
![image](https://user-images.githubusercontent.com/73083035/222632915-5c8aa9f2-9a8c-40d1-b97b-411aa4bbd201.png)

After editing a note, the colour picker gets put above the edit button:
![image](https://user-images.githubusercontent.com/73083035/222633003-fbbeae93-9be1-4a88-aecb-4650cb610845.png)

2023-03-03 04:53 UTC, Delphinus8821 requested changes

2023-03-03 04:53 UTC, Delphinus8821 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewEntry.java
> +    public NotesViewEntry(final String dateTime, final String noteTitle, final String noteContent, final boolean userCreated, final boolean graphAttribute, String nodeColour) {
Final on parameter

2023-03-03 04:53 UTC, Delphinus8821 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewEntry.java
> +    public void setNodeColour(String nodeColour) {
Final

2023-03-03 04:53 UTC, Delphinus8821 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +import javafx.event.EventHandler;
A lot of these imports are unused

2023-03-06 04:53 UTC, OrionsGuardian commented
Null pointer when loading an old graph:
![image](https://user-images.githubusercontent.com/104604488/223022211-9ee43499-825e-48fb-b119-1998cfb4c798.png)

2023-03-06 04:58 UTC, OrionsGuardian commented
There's a problem when re-loading a graph that has user defined coloured notes attached to specific graph elements ...
The notes are no longer attached correctly to the graph elements.
ie. a Vertex note is now linked to a transaction, and a Transaction note isn't linked to anything at all.
![image](https://user-images.githubusercontent.com/104604488/223022787-9c0690d4-0c6a-4452-9a77-68e1ddd336dc.png)

2023-03-06 05:15 UTC, OrionsGuardian commented
Another exception:
If you edit a Note, but don't save it yet, click on another graph and click back to the edited graph, then click on the Save button, it will throw an exception.
(also fyi, the colour picker appears in the edit window in that scenario as well)
```
java.lang.IllegalArgumentException: Children: duplicate children added: parent = VBox@2d3407ae
	at javafx.graphics/javafx.scene.Parent$3.onProposedChange(Parent.java:558)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:234)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:103)
	at au.gov.asd.tac.constellation.views.notes.NotesViewPane.lambda$createNote$28(NotesViewPane.java:834)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8879)
	at javafx.controls/javafx.scene.control.Button.fire(Button.java:200)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedScene.lambda$mouseEvent$4(EmbeddedScene.java:286)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.EmbeddedScene.lambda$mouseEvent$5(EmbeddedScene.java:279)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
[catch] at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

2023-03-06 05:22 UTC, OrionsGuardian requested changes
I think the colour picker should be part of the "Edit" mode for the Note, rather than having it on display for every Note.

2023-03-08 00:45 UTC, Delphinus8821 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +        //noteButtons.getChildren().add(colourPicker);
Can we remove some of these extra blank lines

2023-03-13 00:49 UTC, OrionsGuardian requested changes

2023-03-13 00:49 UTC, OrionsGuardian commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +            Color col = colourPicker.getValue();
final

2023-03-13 00:49 UTC, OrionsGuardian commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +            String currentColour = newNote.getNodeColour();
final

2023-03-13 01:05 UTC, OrionsGuardian commented
In the Edit Mode screen for the Note, can you move the Colour-Picker button to be above the Save and Cancel buttons, and have a larger gap between it and the save/cancel buttons. Pressing Save or Cancel will end the edit session, whereas changing the colour still keeps you in Edit mode.

2023-03-13 01:23 UTC, OrionsGuardian commented
![image](https://user-images.githubusercontent.com/104604488/224587496-4a5943e7-0ec4-49b5-be83-3fc581337def.png)
Notes on Pre-existing graphs are not being loaded properly. 
They are not being linked correctly to the corresponding nodes & transactions.

2023-03-14 22:51 UTC, Delphinus8821 commented
I think this is looking good to go once those couple of code smells have been fixed.

2023-03-17 00:48 UTC, Delphinus8821 approved these changes

2023-03-17 02:49 UTC, OrionsGuardian approved these changes

2023-03-17 02:51 UTC, merged