Added time filter in the Notes View
constellation-app/constellation pull request #1812
Opened 2023-03-10 05:48 UTC by altair1673

### Prerequisites

- [X] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

I have added a DateTimeRange Picker Accordion component to the Notes View. This component is in JavaFX unlike the one in the Data Access View which is a Swing component. The user can specify a datetime range to see a specific set of notes. The User can change time zones. They have to toggle the on/off button of the component and then hit apply for their filters to work. If the user clicks apply with the "active: button set to off then all notes are displayed.
### Alternate Designs

### Why Should This Be In Core?

Users can sort notes created at specific times. Allows for less clutter in the Notes View if only the important can be filtered.
The component is in JavaFX so some elements can be put in separate classes for future use whenever another time range picker needs to be used.
### Benefits

Allows more control to the user for which notes they want to see.
### Possible Drawbacks

The placement of the component might need to change, currently it is at the top of  the Notes View and when clicked it expands down making the top toolbar even bigger.
The dropdown for the time zones is extremely large and there is no scroll bar so it takes a while to scroll to the bottom. In the future maybe this can be replaced with a search box. Options also don't have the time offset next to them, eg. no "GMT+10" next to the region names which could be an issue.
The comparison code of the datetime variable of a note entry is dependent on the date format used in the Notes View. If the date formatting were to change then the code to filter by datetime would break and throw exceptions. This needs to change in the future. 
### Verification Process

The component successfully filters notes even if the time zone is different than the one the notes were created in.
### Applicable Issues

#1761

2023-03-14 00:47 UTC, Delphinus8821 requested changes
Having both an on/off button and an apply button is very confusing. Only one should be needed here:
![image](https://user-images.githubusercontent.com/73083035/224863764-ddd15afa-8ef9-402c-8a6c-75ba96b4b0cd.png)
If there are too many notes present in the Notes View then half of the time range selector is not accessible and gets cut off
![image](https://user-images.githubusercontent.com/73083035/224863879-b58c389c-f94d-4d5e-95f8-8ccecb1fe16e.png)

2023-03-14 00:50 UTC, Delphinus8821 requested changes

2023-03-14 00:50 UTC, Delphinus8821 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/DateTimePicker.java
> +    public void setCurrentDateTime(ZoneId zone) {
final

2023-03-14 00:50 UTC, Delphinus8821 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/DateTimePicker.java
> +    public void convertCurrentDateTime(ZoneId convertTo) {
final

2023-03-14 00:50 UTC, Delphinus8821 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +import javafx.scene.layout.TilePane;
Lots of unused imports

2023-03-14 00:50 UTC, Delphinus8821 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/DateTimePicker.java
> +import javafx.beans.property.SimpleIntegerProperty;
Unused imports

2023-03-20 00:58 UTC, Delphinus8821 commented
It would be good to have some unit tests be written for the DateTimePicker class

2023-03-20 02:08 UTC, Delphinus8821 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/DateTimeRangePicker.java
> +public class DateTimeRangePicker {
Need to add a class description here

2023-03-20 02:08 UTC, Delphinus8821 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/DateTimeRangePicker.java
> +    }
This spacing can be minimised

2023-03-20 22:07 UTC, Delphinus8821 approved these changes

2023-03-21 03:38 UTC, OrionsGuardian requested changes

2023-03-21 03:38 UTC, OrionsGuardian commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/DateTimePicker.java
> +        Label datePickerLabel = new Label();
final x2

2023-03-21 03:38 UTC, OrionsGuardian commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/DateTimePicker.java
> +        Label secLabel = new Label("Second");
final x4

2023-03-21 03:38 UTC, OrionsGuardian commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/DateTimePicker.java
> +        ZonedDateTime timeAtZone = ZonedDateTime.now(zone);
final

2023-03-21 03:38 UTC, OrionsGuardian commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/DateTimeRangePicker.java
> +        ZonedDateTime toTime = toDate.getCurrentDateTime();
final x2

2023-03-21 03:38 UTC, OrionsGuardian commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +                    String[] timeComponents = time.split(":");
final x5

2023-03-21 03:38 UTC, OrionsGuardian commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +                    int sec = Integer.parseInt(timeComponents[2]);
final x2

2023-03-21 03:38 UTC, OrionsGuardian commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +                    ZonedDateTime entryTime = ZonedDateTime.of(year, month, day, hour, min, sec, 0, ZoneId.of(ZoneId.systemDefault().getId()));
final

2023-03-21 03:38 UTC, OrionsGuardian commented on CoreNotesView/test/unit/src/au/gov/asd/tac/constellation/views/notes/DateTimePickerNGTest.java
> +        DateTimePicker instance = new DateTimePicker(true);
final x3

2023-03-21 03:38 UTC, OrionsGuardian commented on CoreNotesView/test/unit/src/au/gov/asd/tac/constellation/views/notes/DateTimePickerNGTest.java
> +        DateTimePicker instance = new DateTimePicker(true);
final x3

2023-03-21 03:38 UTC, OrionsGuardian commented on CoreNotesView/test/unit/src/au/gov/asd/tac/constellation/views/notes/DateTimePickerNGTest.java
> +        boolean result = instance.isActive();
final x3

2023-03-21 03:38 UTC, OrionsGuardian commented on CoreNotesView/test/unit/src/au/gov/asd/tac/constellation/views/notes/DateTimePickerNGTest.java
> +        DateTimePicker instance = new DateTimePicker(true);
final x2

2023-03-21 03:38 UTC, OrionsGuardian commented on CoreNotesView/test/unit/src/au/gov/asd/tac/constellation/views/notes/DateTimePickerNGTest.java
> +        DateTimePicker instance = new DateTimePicker(true);
final

2023-03-21 03:38 UTC, OrionsGuardian commented on CoreNotesView/test/unit/src/au/gov/asd/tac/constellation/views/notes/DateTimePickerNGTest.java
> +
final x2

2023-03-21 03:38 UTC, OrionsGuardian commented on CoreNotesView/test/unit/src/au/gov/asd/tac/constellation/views/notes/DateTimePickerNGTest.java
> +        ZoneId zone = ZoneId.of("Australia/Perth");
final x2

2023-03-21 03:38 UTC, OrionsGuardian commented on CoreNotesView/test/unit/src/au/gov/asd/tac/constellation/views/notes/DateTimePickerNGTest.java
> +        ZoneId result = instance.getZoneId();
final

2023-03-21 03:45 UTC, OrionsGuardian commented
The new functionality seems fine, however, I would like the layout of the Date Picker component to be modified a litttle:

![image](https://user-images.githubusercontent.com/104604488/226512512-bb653468-a4d0-40c6-9e53-eea5392de732.png)

From the above mock sample, I'd like the width of the Date Picker to be reduced, and the Clear button to be moved to titlebar, and only available when a filter is active.

2023-03-21 23:00 UTC, OrionsGuardian approved these changes

2023-03-21 23:37 UTC, merged