Prevent exception popup windows from being displayed when a notification was already shown.
constellation-app/constellation pull request #1830
Opened 2023-05-15 06:31 UTC by OrionsGuardian

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Addresses issues raised in #1641 

When a plugin shows a notification to the user, it should no longer show an exception popup as well.

This is achieved by setting a block-popups flag on the Error Report that is generated when the exception is logged.

### Alternate Designs
None

### Why Should This Be In Core?

It should be a consistent standard across the product to have notification popups without an accompanying exception dialog.

### Benefits

Improved user experience.
No need to show an exception dialog as well as a simple notification when that notification alone will suffice.

### Possible Drawbacks
None

### Verification Process

Test these plugins (as listed in #1641):
* Import from GraphML file
* Import from GML file
* Import from Pajek file
* Import from GDELT X2
* Extract types from text
* Extend from GML file
* Extend from from GDLET
* Utility > Select Top Node and the Import Options

Trying to run each plugin without completing the required details should cause a notification to be displayed.
For many cases, there should also be an Error Report generated and listed in the Error Report View.
For errors with an associated Error Report entry, confirm that the block-popups icon is showing on those entries.

Note that some plugins will throw an INFO severity level error.
The Error Report View will not show INFO popups by default. 
The default behaviour can be set in the Report Settings control.

### Applicable Issues

#1641

2023-05-23 23:40 UTC, antares1470 requested changes

2023-05-23 23:40 UTC, antares1470 commented on CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/ConstellationErrorManager.java
> +            final int firstColon = errorSummary.indexOf(":");
`SeparatorConstants.SEMICOLON`

2023-05-23 23:40 UTC, antares1470 commented on CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/ConstellationErrorManager.java
> +            final int prevDotPos = errorSummary.substring(0, (firstColon != -1 ? firstColon : errorSummary.length())).lastIndexOf(".");
`SeparatorConstants.PERIOD`

2023-05-24 00:06 UTC, Delphinus8821 approved these changes

2023-05-25 01:08 UTC, antares1470 approved these changes

2023-05-25 01:09 UTC, merged