Only allow numeric text in number parameters.
constellation-app/constellation pull request #1833
Opened 2023-05-23 05:33 UTC by OrionsGuardian

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Numeric fields will now check the input text against a number pattern to confirm valid numeric data.

### Alternate Designs

Could wait indefinitely for the component creator to provide a validation method.

### Why Should This Be In Core?

Improved User experience.

### Benefits

Prevents bad data being used in number fields.

### Possible Drawbacks

N/A

### Verification Process

Test on Integer parameters and Float parameters.
Confirm the non-numeric keystrokes are being ignored.

### Applicable Issues

#1687

2023-05-23 23:07 UTC, antares1470 approved these changes

2023-05-23 23:33 UTC, antares1470 requested changes
Apologies. I got excited after testing that I forgot to check the code 😄. See the below comments

2023-05-23 23:33 UTC, antares1470 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/NumberInputPane.java
> +            final int dotPos = newValue.indexOf(".");
`SeparatorConstants.PERIOD`

2023-05-23 23:33 UTC, antares1470 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/NumberInputPane.java
> +            if (intPart.matches("[\\-]?[0-9]?[0-9]?[0-9]?[0-9]?[0-9]?[0-9]?[0-9]?[0-9]?" + (isIntVal ? "[0-9]?" : ""))
could the series of [0-9]?... be reduced to [0-9]{0, 8}?
I could also be wrong but with that regex statement, technically "-" on its own will match (so you might need to specify that if there is a "-" then there needs to be something after it)

2023-05-23 23:33 UTC, antares1470 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/NumberInputPane.java
> +                                && (decPart.isBlank() || (decPart.matches("[0-9]?[0-9]?") && !isIntVal))) {
similarly [0-9]{0,2}

2023-05-23 23:43 UTC, Delphinus8821 approved these changes

2023-05-24 23:07 UTC, antares1470 approved these changes

2023-05-24 23:07 UTC, merged