Improved notification for File Not Found error when no file specified.
constellation-app/constellation pull request #1841
Opened 2023-05-31 04:13 UTC by OrionsGuardian

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Updated the "File not Found" notification when running a plugin from the Data Access View without specifying a filename. It should only pop up a single message informing the user that they haven't specified which file to use.

Also tightened the matching criteria used in the Error Report view, as there were similar exceptions from the data access plugins being grouped together, when they shouldn't be.

### Alternate Designs

N/A

### Why Should This Be In Core?

Improved user experience

### Benefits

Improved user experience

### Possible Drawbacks

N/A

### Verification Process

In the Data Access View, select (click the checkbox for) Import from Graph file.
Click the Go button
Confirm that you see a single popup window saying "File not specified" and no other popup windows.
There should be a corresponding exception logged in the Error Report View.

### Applicable Issues

#1839

2023-06-02 01:12 UTC, antares1470 requested changes

2023-06-02 01:12 UTC, antares1470 commented on CoreErrorReportView/src/au/gov/asd/tac/constellation/views/errorreport/ErrorReportSessionData.java
> +                    }
might be worth adding a break here. The loop is only determining whether `allConstyLinesMatch` should become false and once it does, it then stays that way for the remainder of the for loop so the remaining iterations are redundant after the if condition if fulfilled (and so might as well exit the loop at that stage as well).

2023-06-02 01:12 UTC, antares1470 commented on CoreErrorReportView/src/au/gov/asd/tac/constellation/views/errorreport/ErrorReportSessionData.java
> +                destination.append(sourceLines[i]).append("\n");
`SeparatorConstants.NEWLINE`

2023-06-02 01:12 UTC, antares1470 commented on CoreErrorReportView/src/au/gov/asd/tac/constellation/views/errorreport/ErrorReportSessionData.java
> +        return destination.toString().split("\n");
same here

2023-06-02 02:06 UTC, antares1470 approved these changes

2023-06-04 22:49 UTC, Delphinus8821 approved these changes

2023-06-04 23:52 UTC, merged