Bugfix/notes view autosave
constellation-app/constellation pull request #1849
Opened 2023-06-13 08:27 UTC by altair1673

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Notes that are being edit do not get reset when an autosave occurs. If a note is in edit mode and the user switches graphs, that note will remain in edit mode with any changes made when the user returns.

### Alternate Designs

### Why Should This Be In Core?

Makes editing notes safe as the users can the sure there changes won't randomly be lost if a background plugin finishes running.
### Benefits

Increases usability of the notes view.
### Possible Drawbacks

Auto notes are not updated in real time.
### Verification Process

Made changes to note in edit mode switched graphs and came back to see note still in edit mode with the changes I have made.
### Applicable Issues

#1848

2023-06-13 22:51 UTC, OrionsGuardian requested changes

2023-06-13 22:51 UTC, OrionsGuardian commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewEntry.java
> +    public void setWasInEditMode(boolean wasInEditMode) {
final

2023-06-13 22:51 UTC, OrionsGuardian commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewEntry.java
> +    public void setTempContent(String tempContent) {
final

2023-06-13 22:51 UTC, OrionsGuardian commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewEntry.java
> +    public void setTempTitle(String tempTitle) {
final

2023-06-14 03:13 UTC, Delphinus8821 approved these changes

2023-06-14 04:38 UTC, OrionsGuardian approved these changes

2023-06-14 23:31 UTC, antares1470 requested changes

2023-06-14 23:31 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/NotesViewPane.java
> +            for (int i = 0; i < notesToRender.size(); i++) {
use a for each here `for (final NotesViewEntry note : notesToRender)`

2023-06-14 23:31 UTC, antares1470 commented on CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/state/NotesViewEntry.java
> +    private String tempTitle = "";
add the instantiations to the constructor

2023-06-15 04:06 UTC, antares1470 approved these changes
Good to go once the merge conflict is resolved

2023-06-15 05:34 UTC, merged