Cursor changes when draw mode is activated
constellation-app/constellation pull request #1864
Opened 2023-07-18 03:52 UTC by Centauri0320001

### Prerequisites

- [x ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

When draw mode is clicked the cursor changes to crosshair. 
### Alternate Designs

### Why Should This Be In Core?

Enhancement to UX clarity to prevent confusion when in/out of draw mode.
### Benefits
Improves UX clarity.

### Possible Drawbacks

### Verification Process

Change to draw mode saw the cursor changed. Works across multiple graphs. 
### Applicable Issues

#921

2023-07-19 01:07 UTC, OrionsGuardian requested changes

2023-07-19 01:07 UTC, OrionsGuardian commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/utilities/DrawModeCursorFlag.java
> +    public static final BooleanProperty DrawModeEnabled = new SimpleBooleanProperty();
Can you make this private and define a getter and setter for it.
Also, the variable name should start with a lowercase letter.

2023-07-19 07:20 UTC, OrionsGuardian requested changes

2023-07-19 07:20 UTC, OrionsGuardian commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/InteractiveGLVisualProcessor.java
> +            if (resultState.getCurrentHitType().equals(HitType.NO_ELEMENT) && !DrawModeCursorFlag.getDrawModeEnabled()) {
This line can be replaced with the following:
```
            if (resultState.getCurrentHitType().equals(HitType.NO_ELEMENT) && !VisualGraphUtilities.isDrawingMode(GraphManager.getDefault().getActiveGraph())) {
```            
And this is the only code change required for this ticket.
All other code changes can be removed.
There is no need for the DrawModeCursorFlag class to exist at all.

Note that all the documentation changes can be kept.

2023-07-20 03:02 UTC, Delphinus8821 approved these changes

2023-07-20 04:05 UTC, OrionsGuardian approved these changes

2023-07-20 06:03 UTC, antares1470 approved these changes

2023-07-26 05:23 UTC, merged