Fixed double click bug in quality control view
constellation-app/constellation pull request #1866
Opened 2023-07-20 01:26 UTC by Centauri0320001

### Prerequisites

- [x ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Fixed bug where the users first click would count as two clicks in the Quality Control View when a new sphere graph is created. 
### Alternate Designs

### Why Should This Be In Core?

Fixes bug which causes confusion when using quality control view.
### Benefits

Improves usability of quality control view.
### Possible Drawbacks

### Verification Process

### Applicable Issues

#784

2023-07-20 06:27 UTC, OrionsGuardian requested changes
The problem is not fully fixed.
Only the very first click in the Quality Control table is blocked.
If you then de-select then re-select the same node in the graph, and single click the Quality Control table entry, it will again be treated like a double click.

2023-07-20 07:07 UTC, OrionsGuardian requested changes

2023-07-20 07:07 UTC, OrionsGuardian commented on CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewTopComponent.java
> +    private static boolean firstClick = true;
This variable should be defined in the QualityControlViewPane class.
There's no need for any code changes in this class.

2023-07-20 07:07 UTC, OrionsGuardian commented on CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java
> +                            value.getClickCount() > 2 && !QualityControlViewTopComponent.isFirstClick()) {
The `if` conditions can be simplified to:
```
        if (value.getClickCount() >= 2 && !firstClick) {
```
And have `firstClick` defined as a local class member variable.

2023-07-20 22:39 UTC, Delphinus8821 requested changes
I also found that if you click off of Constellation and then single click back onto the quality control view it is treated like a double click.

2023-07-20 22:52 UTC, OrionsGuardian requested changes
Also need to consider the case where a user may genuinely double-click on an entry in the table as the first thing they do.

2023-07-21 04:35 UTC, OrionsGuardian requested changes

2023-07-21 04:35 UTC, OrionsGuardian commented on CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewTopComponent.java
> +
I don't believe these changes are required.
The focus listener in the View Pane ensures the firstClick variable will always be set to true whenever the View Pane gets focus.

2023-07-21 04:35 UTC, OrionsGuardian commented on CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java
> +        alert.setY((screens.get(0).getVisualBounds().getMinY() + screens.get(0).getVisualBounds().getHeight() / 2));
This needs to account for the size of the Rule Dialog as well.
As it is, it shows in the bottom right portion of the application screen, with the bottom of the dialog potentially going below the bottom of the screen.

2023-07-21 04:35 UTC, OrionsGuardian commented on CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java
> +    }
Do not need a publicly accessible setter for this variable.
Assign the values directly.

2023-07-24 02:09 UTC, OrionsGuardian requested changes

2023-07-24 02:09 UTC, OrionsGuardian commented on CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewTopComponent.java
> +import au.gov.asd.tac.constellation.graph.monitor.GraphChangeEvent;
remove unused import

2023-07-24 03:58 UTC, OrionsGuardian requested changes

2023-07-24 03:58 UTC, OrionsGuardian commented on CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewTopComponent.java
Given that the only changes are now whitespace changes, I'd suggest undoing the changes. 
No value in checking in an essentially unchanged file.

2023-07-24 05:04 UTC, OrionsGuardian approved these changes
The code change does not identify the underlying cause of the double-click problem,
however, it does adequately address the functionality issue.
It is an acceptable workaround.

2023-07-26 02:48 UTC, mimosa2 approved these changes

2023-07-26 23:57 UTC, antares1470 requested changes
Agreeing with @OrionsGuardian in that this will be an adequate workaround since the actual issue (with the ControlsFX object) can't be fixed within Constellation itself.

With that in mind, are you possibly able to add some comments just to note that it is a workaround (possibly add it at the declaration of `firstClick`)? Doing so will just help us remember to re-assess the underlying issue in the future (as hopefully if the fx object is fixed, this workaround shouldn't be necessary)

2023-07-27 03:17 UTC, antares1470 approved these changes

2023-07-27 03:17 UTC, merged