Fixed quality control dialog box positioning
constellation-app/constellation pull request #1872
Opened 2023-07-31 06:57 UTC by Centauri0320001

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Fixed bug where the dialog boxes for select rule priority would appear only in the default monitor of workstations with multiple screens instead of the screen constellation is open in. 
### Alternate Designs

### Why Should This Be In Core?

Fixes a dialog positioning bug.
### Benefits

Reduces confusion for the user when opening the select rule priorities box.
### Possible Drawbacks

### Verification Process

### Applicable Issues

#1793

2023-07-31 22:48 UTC, Delphinus8821 approved these changes

2023-07-31 23:57 UTC, OrionsGuardian requested changes

2023-07-31 23:57 UTC, OrionsGuardian commented on CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/QualityControlViewPane.java
> +        alert.setY((screens.get(0).getVisualBounds().getMinY() + screens.get(0).getVisualBounds().getHeight() / 2) - 170);
Can you change the magic numbers (350 & 170) to instead use a calculation equal to half the width and height of the `rulesScrollPane` object as appropriate.

Please also fix a similar issue on lines 703 & 704 where a fixed number is being used when it should be calculated as width/2 and height/2 of the `sp` object.

2023-08-01 02:07 UTC, OrionsGuardian approved these changes

2023-08-02 03:56 UTC, antares1470 approved these changes

2023-08-02 03:57 UTC, merged