Added checks for null attributes and only add if "Show All" selected
constellation-app/constellation pull request #1898
Opened 2023-09-15 04:06 UTC by serpens24

### Prerequisites

- [X] Reviewed the [checklist](CHECKLIST.md)

- [X] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Added checks of attributes being displayed in populateContentContainer and if "Show All" is NOT enabled and values are null then dont call createAttributeTitlePane and add title pane for the attributes.

Updated AttributeEditorTopComponent to have a hook for preference changes to allow update as Show All is toggled.

### Alternate Designs

nil

### Why Should This Be In Core?

Fixing bug in "Show All" plus user requested ability to hide large amounts of null content

### Benefits

### Possible Drawbacks

### Verification Process

Open a graph and Attribute Editor. Hide/Unhide some attributes and ensure they are hidden/shown on Attribute editor. Now enable "Show All" and repeat.

confirm that if no node selected all node attributes show as null and dont display if "Show All" not enabled.
Set valeus for one or more of these and confirm it is shown as having a value.

### Applicable Issues

#1893

2023-09-20 02:17 UTC, antares1470 requested changes
Looks nice is testing. On top of the other comments, if you're able to add a whatsnew for this, that would be great

2023-09-20 02:17 UTC, antares1470 commented on CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
> +    {
are you able to put the open braces at the end of the previous line (I think there is a few places this can be done)

2023-09-20 02:17 UTC, antares1470 commented on CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
> +        showEmptyToggle.selectedProperty().addListener((ObservableValue<? extends Boolean> observable, Boolean oldValue, Boolean newValue)
can you either add finals to the lambda parameters or remove the explicit type definitions?

2023-09-20 02:17 UTC, antares1470 commented on CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
> +        showHiddenToggle.selectedProperty().addListener((ObservableValue<? extends Boolean> observable, Boolean oldValue, Boolean newValue)
same here

2023-09-20 02:17 UTC, antares1470 commented on CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
> +        if (values == null) return true;
are you able to add some curly braces here?

2023-09-20 02:17 UTC, antares1470 commented on CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
> +            if (value != null) return false;
same here

2023-09-20 04:49 UTC, OrionsGuardian commented
The functionality seems to work well, but I'm not sure I like having a toggle button being active by default.
It draws unnecessary attention to a setting which the user hasn't touched.
When a user clicks the toggle button, then it makes sense to draw attention to the setting which the user has changed.

It might be better if the button were to toggle between the words "Hide Empty" and "Show Empty", defaulting with the Hide Empty label on a grey background.
However, that would cause some confusion with the "Show Hidden" button, where that only affects flagged attributes.
Not sure of the best re-wording for the buttons (with or without toggling text), such that the default screen has both the toggles off.

2023-09-22 00:03 UTC, OrionsGuardian commented
Following on from my previous comment, this is an example of what it could look like:
![image](https://github.com/constellation-app/constellation/assets/104604488/b83eb979-f87f-4ce1-abc2-301ea85007ea)
Then the default state would be with toggle buttons showing the grey background options.
The user can then actively choose to hide attributes, and the toggle buttons will be active, which also highlights that their screen is in a modified state.

2023-09-28 01:06 UTC, serpens24 commented
Feedback from issue raiser and other end users is the current implementation sounds good. As such propose we leave as is at this point.

2023-10-13 02:44 UTC, antares1470 requested changes

2023-10-13 02:44 UTC, antares1470 commented on CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
> +        showEmptyToggles = new HashMap<HeadingType, ToggleButton>();
you should be able to instantiate using just the diamond operator `<>`

2023-10-13 02:44 UTC, antares1470 commented on CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
> +            final GraphElementType elementType;
seems like this variable isn't being used

2023-10-13 02:44 UTC, antares1470 commented on CoreAttributeEditorView/src/au/gov/asd/tac/constellation/views/attributeeditor/AttributeEditorPanel.java
> +    {
can you move this to the end of the previous line?

2023-10-16 21:57 UTC, antares1470 approved these changes

2023-10-17 21:34 UTC, Delphinus8821 approved these changes

2023-10-17 22:07 UTC, merged