Added help text for Markdown
constellation-app/constellation pull request #1902
Opened 2023-10-11 03:18 UTC by altair1673

### Prerequisites

- [ x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Added in some help text that say what markdown features are available in the notes view.

### Alternate Designs

### Why Should This Be In Core?

Users might not know what markdown is or which features have been implemented so this is just some documentation on that.
### Benefits

Easier to use the markdown features
### Possible Drawbacks

Maybe some of the help is not descriptive enough.
### Verification Process

### Applicable Issues

#1754

2023-10-15 21:43 UTC, Delphinus8821 approved these changes

2023-10-20 01:33 UTC, antares1470 requested changes

2023-10-20 01:33 UTC, antares1470 commented on CoreNotesView/release/modules/ext/docs/CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/notes-view.md
> +The notes view supports some markdown text now. There is a checkbox in the new note
capitalise "Notes View". I would potentially also reword from "some markdown text now" to "some Markdown formatting options"

2023-10-20 01:33 UTC, antares1470 commented on CoreNotesView/release/modules/ext/docs/CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/notes-view.md
> +window that allows you to enable and disable markdown. Markdown is a lightweight markup
capitalise "Markdown"

2023-10-20 01:33 UTC, antares1470 commented on CoreNotesView/release/modules/ext/docs/CoreNotesView/src/au/gov/asd/tac/constellation/views/notes/notes-view.md
> +language for creating formatted text. As of now the notes view supports MD features like:
expand MD

2023-10-24 22:27 UTC, antares1470 approved these changes

2023-10-24 22:27 UTC, merged