Connection Logging for Data Access plugins
constellation-app/constellation pull request #1905
Opened 2023-10-18 01:22 UTC by OrionsGuardian

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Added an option in the Workflow Options menu in the Data Access View: 
Connection Logger

When enabled, any RestClient calls will have the request data and response data logged.
The Logger will only be active for a limited amount of time (2.5 hours), after-which the Connection Logger setting will automatically be disabled.

### Alternate Designs

Could be made as a Global option, not tied directly to the Data Access View.

### Why Should This Be In Core?

Providing this in core will allow it to be referenced from other modules.

### Benefits

Supporting and troubleshooting issues will be quicker and easier with a built-in tool to capture connection data.

### Applicable Issues

#1904

2023-10-19 22:11 UTC, Delphinus8821 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/log/LogPreferences.java
> +    public static void setConnectionLogging(boolean activateLogging) {
parameter final

2023-10-23 04:47 UTC, antares1470 requested changes

2023-10-23 04:47 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/log/ConnectionLogging.java
> + * The ConncetionLogger is used as a portal for logging requests to be processed.
"ConnectionLogger"

2023-10-23 04:47 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/rest/RestClient.java
> +    public void logRequestBytes(final String url, final List<Tuple<String, String>> params, final byte[] messageBytes) {
some of functions here might be nice to have unit tests for

2023-10-26 00:43 UTC, antares1470 approved these changes

2023-10-26 22:16 UTC, Delphinus8821 approved these changes

2023-10-27 02:37 UTC, mimosa2 approved these changes

2023-10-31 21:34 UTC, merged