Ensure Persistent File Browsing Location
constellation-app/constellation pull request #1923
Opened 2023-11-30 05:44 UTC by capricornunicorn123

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Refactors the `FileInputPane` to use the static `FileChooser.openDialogue()` instead of the `FileChooser` instantiation with method `showDialogue()`.

The property "Remember open save location" has been removed.

Plugins that used an `ExtensionFilter` have been reviewed to ensure that they utilize the `FileExtensionConstants` class.

`FileParameterKind`s have been updated to include an "obscured" alternate to existing file kinds. this enables the same functionality a their non obscured alternative but enables the button to express the text "..." instead of "save" or "open".

### Alternate Designs

### Why Should This Be In Core?

It related to core functionality

### Benefits

Ensure that the modified file exporters use the same methods / logic.

### Possible Drawbacks

### Verification Process

Functional Testing
Unit testing

### Applicable Issues

2023-12-04 02:07 UTC, Delphinus8821 requested changes

2023-12-04 02:07 UTC, Delphinus8821 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/FileInputPane.java
> +                            String expectedExtension = FileParameterType.getFileFilters(parameter).getExtensions().get(0);
final

2023-12-04 02:07 UTC, Delphinus8821 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/FileInputPane.java
> +                } catch (InterruptedException | ExecutionException ex) {
final and should split this into two and interrupt the thread on the interrupted exception

2023-12-05 03:25 UTC, antares1470 requested changes
I gave it a test with the Import Graph File plugin. I'm not sure how I feel about the text "Open Multiple" as that seems 'straight out of the code' if you get what I mean. Maybe something like "Open File(s)" might be a little friendlier

2023-12-05 03:25 UTC, antares1470 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/FileInputPane.java
> +                } catch (InterruptedException ex){
exceptions can be final

2023-12-05 03:25 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/file/FileExtensionConstants.java
> +    public static final String GML = ".gml";
GML, GRAPHML, and PAJEK should be grouped together under Graph file extensions

2023-12-05 04:15 UTC, Delphinus8821 approved these changes

2023-12-05 04:38 UTC, capricornunicorn123 commented
> Maybe something like "Open File(s)" might be a little friendlier

Fair call, I've amended the text to "Open File(s)"

2023-12-05 23:21 UTC, antares1470 approved these changes

2023-12-15 01:03 UTC, merged