Fixed Data Access Categories not displaying when migrating from v2.10 to v2.11
constellation-app/constellation pull request #1927
Opened 2023-12-04 00:43 UTC by sol695510

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Reworked plugin lookup logic, and fixed associated classes including the test class.

### Alternate Designs
N/A

### Why Should This Be In Core?
It is a core functionality of the Data Access View.

### Benefits
Plugins will now be displayed correctly when migrating from v2.10 to v2.11.

### Possible Drawbacks
N/A

### Verification Process
Tested using the steps to reproduce in the associated issue ticket.

### Applicable Issues
#1918

2023-12-13 21:37 UTC, Delphinus8821 approved these changes

2023-12-13 22:24 UTC, OrionsGuardian requested changes

2023-12-13 22:24 UTC, OrionsGuardian commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessViewCategoryPanel.java
> +            for (String visibleCategory : visibleCategoryArray) {
`final`

2023-12-13 22:24 UTC, OrionsGuardian commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessViewCategoryPanel.java
> +            for (String hiddenCategory : hiddenCategoryArray) {
`final`

2023-12-13 23:10 UTC, antares1470 requested changes
Adding to above, it looks like the default ordering (what comes up after a clean-build) no longer matches the positions.
i.e. Running Core, it is coming up as Utility, Import, Developer, Clean when it should be Import, Clean, Utility, Developer

2023-12-14 21:19 UTC, antares1470 approved these changes

2023-12-14 21:31 UTC, Delphinus8821 approved these changes

2023-12-14 21:47 UTC, OrionsGuardian approved these changes

2023-12-14 23:21 UTC, merged