Enforce required `PluginParameters`
constellation-app/constellation pull request #1932
Opened 2023-12-05 03:26 UTC by capricornunicorn123

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Developers have the ability to set a required attribute on a `PluginParameter`. Currently when a `PluginParameter` is displayed in a `PluginParametersSwingDialog` this required attribute simply sets a tooltop and adds "*" to the parameter name. 

This PR deactivates the acceptance button if required parameters are not satisfied. 

### Alternate Designs

The current design of executing a plugin, with missing fields caught during plugin execution, was undesirable as users have to re-execute the plugin from the start rather than getting parameters correct the first time. 

A similar approach could be considered in the Data Access View. Currently plugins can be executed with missing fields and simply execute quietly without performing any graph manipulation. Users have to check the plugin reporter to see if the plugin executed. Instead, the "Go" button could be deactivated if required fields have not been completed.

### Why Should This Be In Core?

It is a core feature.

### Benefits

Users will be prevented from executing plugins with missing required data ensuring that they do not have to recommence the plugin execution process from the beginning. 

### Possible Drawbacks

Plugin Parameters do not appear to have the ability to validate their data. As such this PR only checks that the data in a required field is not blank or empty. Instead the plugin parameter could have an interfaced method of `booelan : isValid()` which can then be called to ensure that plugin parameters have valid content when a required field is present. 
Note: this is really only relevant for the `FileParameterValue`

### Verification Process

Execute a graph to a GeoJSON and remove the text from the file location parameter. File > Export > to GeoJSON.
Note the execute button becomes deactivated.

### Applicable Issues
#1930

2024-01-29 02:13 UTC, antares1470 requested changes

2024-01-29 02:13 UTC, antares1470 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/types/FileParameterType.java
> +        private static final Logger LOGGER = Logger.getLogger(FileParameterValue.class.getName());
removed unused (+ dependency)

2024-01-29 02:13 UTC, antares1470 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/types/FileParameterType.java
> +            if (validationFile.isDirectory() || (!validationFile.isDirectory() && validationFile.getParentFile() != null && validationFile.getParentFile().exists())){
The first bit of the clause after || is redundant as this is implied by the first condition

2024-01-29 02:13 UTC, antares1470 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/types/FileParameterType.java
> +            File validationFile = new File(s);
final

2024-01-29 02:13 UTC, antares1470 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/parameters/types/FileParameterType.java
> +            }
can you make this a ternary statement?

2024-01-29 02:13 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/filechooser/ShowFileChooserDialog.java
> +                    int returnState = jfc.showSaveDialog(WindowManager.getDefault().getMainWindow());
final

2024-01-31 04:47 UTC, Delphinus8821 requested changes

2024-01-31 04:47 UTC, Delphinus8821 commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessPane.java
>      public void validityChanged(boolean enabled) {
final

2024-01-31 04:47 UTC, Delphinus8821 commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataAccessPane.java
> +    public void notifyParameterValidityChange(PluginParameter<?> parameter, boolean currentlySatisfied) {
finals

2024-01-31 04:47 UTC, Delphinus8821 commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/DataSourceTitledPane.java
> +    public void notifyParameterValidityChange(PluginParameter<?> parameter, boolean currentlySatisfied) {
finals

2024-01-31 04:47 UTC, Delphinus8821 commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/HeadingPane.java
> +    public void notifyParameterValidityChange(PluginParameter<?> parameter, boolean currentlySatisfied) {
finals

2024-01-31 04:47 UTC, Delphinus8821 commented on CoreDataAccessView/test/unit/src/au/gov/asd/tac/constellation/views/dataaccess/panes/HeadingPaneNGTest.java
> +        public void notifyParameterValidityChange(PluginParameter<?> parameter, boolean currentlySatisfied) {
finals

2024-01-31 04:47 UTC, Delphinus8821 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/PluginParametersSwingDialog.java
> +    public void validityChanged(boolean valid) {
final

2024-02-01 03:37 UTC, antares1470 approved these changes

2024-02-01 23:06 UTC, Delphinus8821 approved these changes

2024-02-01 23:28 UTC, merged