Enhancement/attribute editor field auto untick
constellation-app/constellation pull request #1959
Opened 2024-02-19 02:24 UTC by sol695510

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Removed the no value checkbox from classes it was present in. The no value checkbox's functionality was also replicated by the Restore Default button in many cases so the checkbox was removed and the Restore Default button was updated to disable editable fields when clicked, as it did for some fields but now for all editors, but also be able to undo the Restore Default action during editing if desired, which also re-enables the editable fields.

### Alternate Designs
N/A

### Why Should This Be In Core?
Part of the core functionality of the Attribute Editor.

### Benefits
Allows for immediate editing of editor fields.

### Possible Drawbacks
N/A

### Verification Process
Checked each editor to ensure the correct values are saved with either default enabled or not.

### Applicable Issues
#1888

2024-02-19 05:15 UTC, antares1470 reviewed
I'm not sure how I feel about removing the No value checkbox altogether. With the attributes types that have them, the reason they have them is that no value is a valid value and so I feel people need the option to change it to that. I know its still there in Restore to Default, but I don't feel like that is particularly intuitive, and it assumes that the the default value is in fact no value which may not necessarily be the case (and if it isn't, you have no way of setting no value)

2024-02-19 21:54 UTC, antares1470 commented
> I'm not sure how I feel about removing the No value checkbox altogether. With the attributes types that have them, the reason they have them is that no value is a valid value and so I feel people need the option to change it to that. I know its still there in Restore to Default, but I don't feel like that is particularly intuitive, and it assumes that the the default value is in fact no value which may not necessarily be the case (and if it isn't, you have no way of setting no value)

Just to further add, I'm not against the idea of converting No value into a button (perhaps its similar to pressing ok or cancel except when clicked it sets the value to null). I just think No value should be a clear option (even if its not set by default when you open the edit dialog)

2024-02-19 22:20 UTC, OrionsGuardian requested changes
![image](https://github.com/constellation-app/constellation/assets/104604488/b29a75ce-559c-448a-a3fd-b86fd0828373)

2024-02-22 04:33 UTC, Delphinus8821 approved these changes

2024-02-23 02:22 UTC, antares1470 approved these changes

2024-02-23 02:22 UTC, merged