Fastest box blur exception
constellation-app/constellation pull request #1960
Opened 2024-02-22 04:18 UTC by Quasar985

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Bug fix for ArrayOutOfBounds exception in the `gaussianBlurBox` function using the `FASTEST` BoxBlurType.
Also fixed bug that set the resulting `targetChannel` array to have its elements set to 0. This itself results in an invisible image. This bug occurred both in the `FAST` and `FASTEST` algorithm presets. It would seem unit test's expected values were incorrect, so these have been updated too.

### Alternate Designs

No alternate designs were considered for the ArrayOutOfBounds exception, as it was caused by a lack of valid index checking.

For fixing the issue with data being cleared from the `targetChannel`, alternate designs include: 

- Returning a new array in the `gaussianBlurBox` function instead of editing `targetChannel` directly.
- Removing code responsible for reassigning `targetChannel`, later resulting in its data being cleared (likely a bug itself in the `ArrayUtils.addAll` function)
- Rewriting code responsible for reassigning `targetChannel` to fulfill the same purpose, using different fucntions

Removing the offending code was chosen as: changing the function signature would likely cause issue in other area of the code base and attempts to rewrite the code caused visual problems in initial tests. Considering that the map view has been complete reworked in the latest version of Constellation, it was not deemed critical to rewrite the offending code to perfectly produce a blurred image.

### Why Should This Be In Core?

### Benefits

Exception no longer occurs, and Map view's heat map now functions again.

### Possible Drawbacks

As the gaussian blur is currently only used by the map view's heat map, it is likely there are no side effects to other parts of the code base.

### Verification Process

Functionality was verified both through unit tests and visually. The heat map is the only feature that uses the gaussian blur, so it was used as visual indicator of correct functionality.
There are likely no regressions, as only the map view's heat map makes use of the functionality.

### Applicable Issues

https://github.com/constellation-app/constellation/issues/1616#issue-1110055063X

2024-02-22 23:04 UTC, OrionsGuardian requested changes

2024-02-22 23:04 UTC, OrionsGuardian commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/image/GaussianBlur.java
> +                    //targetChannel = ArrayUtils.addAll(tempChannel);
The commented out lines can be removed.

2024-02-22 23:04 UTC, OrionsGuardian commented on CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/image/GaussianBlurNGTest.java
> +        //final float[] targetChannel = {0f, 0f, 0f, 0f, 0f, 0f, 0f, 0f};
Can remove this commented out line.

2024-02-22 23:08 UTC, OrionsGuardian commented
While testing the HeatMap, was consistently getting this exception when moving the map down, so the heatmapped nodes are off-screen below the viewing area.

![image](https://github.com/constellation-app/constellation/assets/104604488/17e5b676-d670-4be6-81fa-74bb8a587ab0)

This was likely a pre-existing issue, but would be good to identify and handle this in a better way.

2024-02-29 00:30 UTC, antares1470 approved these changes

2024-02-29 00:43 UTC, capricornunicorn123 approved these changes

2024-02-29 22:03 UTC, merged