Zoom In/Out keyboard shortcut
constellation-app/constellation pull request #1971
Opened 2024-03-01 00:43 UTC by Quasar985

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [x] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Added keyboard shortcuts and toolbar buttons for zooming in/out the graph view. Shortcuts are Ctrl+Alt+Up and Ctrl+Alt+Down, respectively.

### Alternate Designs

Buttons could be positioned in different areas of the UI. Their current position is close to buttons of similar funciton, "Reset View" and "Zoom To Selection" on the toolbar.

### Why Should This Be In Core?

Allows users without a scroll wheel to conveniently zoom in and out of the graph view.

### Benefits

Greater accessibility to users of different hardware configurations.

### Possible Drawbacks

Toolbar UI may eventually become cluttered if more buttons are added.

### Verification Process

Combination of visual testing in graph view and unit tests written to verify camera position.

### Applicable Issues

https://github.com/constellation-app/constellation/issues/1955

2024-03-01 02:29 UTC, capricornunicorn123 reviewed
I wonder if these plugins could be merged to a simple zoom plugin and parameters added to indicate direction, distance etc? This could then be integrated into the `DefaultInteractionEventHandeler` and become a reusable zooming functionality.

2024-03-01 02:29 UTC, capricornunicorn123 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomOutPlugin.java
> +    final int ZOOM_AMOUNT = 10;
These two variables can be declared static

2024-03-01 02:29 UTC, capricornunicorn123 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomInPlugin.java
> +    final int ZOOM_AMOUNT = 10;
These two variables can be declared static

2024-03-01 02:29 UTC, capricornunicorn123 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomOutPlugin.java
> +            Animation.startAnimation(new PanAnimation("Zoom to Selection", oldCamera, camera, true));
Running this as an animation looks nice when users zoom with a gap between zoom requests. However, when zooming quicky. (i.e ctrl + alt + hold up arrow) the experiences a little jarring with pan animations stopping and starting. I wonder if simply writing to the graph and not doing an animation would be nicer? Single requests to zoom would be more jarring but might be a lesser evil. (Same goes for ZoonInPlugin)

2024-03-01 02:29 UTC, capricornunicorn123 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomOutPlugin.java
> +        CameraUtilities.zoom(camera, ZOOM_AMOUNT, ZOOM_DIRECTION, 0F);
Setting the node distance to 0F will mean that zooming through vast empty space to distant nodes will be slow. Might be worth trying to get node distances to help with this.

2024-03-04 00:42 UTC, OrionsGuardian requested changes
We should probably be re-using the existing code for zooming in and out via the mouse wheel, and develop a modified version to handle the keyboard shortcuts.
`DefaultInteractionEventHandler.mouseWheelMoved(event)`

This should also address some of the concerns raised by @capricornunicorn123

2024-03-06 21:53 UTC, Delphinus8821 requested changes

2024-03-06 21:53 UTC, Delphinus8821 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomInPlugin.java
> +    static private final int ZOOM_MAGNITUDE = 2;
private static

2024-03-06 21:53 UTC, Delphinus8821 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomOutPlugin.java
> +    static private final int ZOOM_MAGNITUDE = 2;
private static

2024-03-06 21:53 UTC, Delphinus8821 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomUtilities.java
> +    static public void zoom(final GraphWriteMethods graph, final int zoomMagnitude, final Vector3f zoomDirection, float distanceToClosestNode) throws InterruptedException, PluginException {
public static and last parameter final

2024-03-06 21:53 UTC, Delphinus8821 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomUtilities.java
> +    static public void zoom(final GraphWriteMethods graph, final int zoomMagnitude, final Vector3f zoomDirection) throws InterruptedException, PluginException {
public static

2024-03-06 21:53 UTC, Delphinus8821 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomUtilities.java
> +    static public Vector3f closestNodeCameraCoordinates(GraphReadMethods graph) {
public static and parameter final

2024-03-06 21:53 UTC, Delphinus8821 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/InteractiveGLVisualProcessor.java
> +        static public NodeCameraDistance getClosestNode(NodeCameraDistance ncd1, NodeCameraDistance ncd2) {
public static and parameters final

2024-03-06 22:52 UTC, Delphinus8821 approved these changes

2024-03-07 22:14 UTC, antares1470 reviewed
1) If you would add an entry to `whatsnew.txt` for this, that would be great
2) I see there is a use of `CameraUtiltities.zoom` in the `DefaultInteractionEventHandler` (which is where it handles mouse wheel scrolling). Wondering if that should be altered to use the `ZoomUtilities` class you created

2024-03-07 22:14 UTC, antares1470 commented on CoreInteractiveGraph/test/unit/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomInPluginNGTest.java
> +import static org.testng.Assert.*;
can you replace this import with the specifically used classes?

2024-03-07 22:14 UTC, antares1470 commented on CoreInteractiveGraph/test/unit/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomOutPluginNGTest.java
> +import static org.testng.Assert.*;
same here

2024-03-07 22:14 UTC, antares1470 commented on CoreInteractiveGraph/test/unit/src/au/gov/asd/tac/constellation/graph/interaction/plugins/zoom/ZoomUtilitiesNGTest.java
> +import static org.testng.Assert.*;
same here

2024-03-07 23:27 UTC, Quasar985 commented
> 1. If you would add an entry to `whatsnew.txt` for this, that would be great
> 2. I see there is a use of `CameraUtiltities.zoom` in the `DefaultInteractionEventHandler` (which is where it handles mouse wheel scrolling). Wondering if that should be altered to use the `ZoomUtilities` class you created

The `ZoomUtilities` class was more to streamline the shared functionality of `ZoomInPlugin` and `ZoomOutPlugin`, and gather the parameters needed to call `CameraUtiltities.zoom` with what info plugins are able to access. I think swapping out `CameraUtilities` for `ZoomUtilities`, would make `DefaultInteractionEventHandler` slightly worse in terms of code readability and how the graph view is updated.

I'm thinking the solution might be to rename `ZoomUtilities` to better reflect it's intended purpose as a base class for the zoom plugins. Let me know your thoughts.

2024-03-08 02:54 UTC, antares1470 commented
> The `ZoomUtilities` class was more to streamline the shared functionality of `ZoomInPlugin` and `ZoomOutPlugin`, and gather the parameters needed to call `CameraUtiltities.zoom` with what info plugins are able to access. I think swapping out `CameraUtilities` for `ZoomUtilities` would make `DefaultInteractionEventHandler` slightly worse in terms of code readability and how the graph view is updated.
> 
> I'm thinking the solution might be to rename `ZoomUtilities` to better reflect it's intended purpose as a base class for the zoom plugins. Let me know your thoughts.

I suppose the thinking in my head was that you would expect that the mouse scrolling and the zoom plugins would all be tapping into the same functionality. And they are...but possibly not as much as you would expect. That being said, having looked at the functions, I can see why it might be difficult to consolidate further. Renaming probably also won't help as its likely to be difficult to come up with a better name (even something like "ZoomPluginUtilities" doesn't really remove the confusion).

So based on that, I guess you can ignore that 2nd point (though maybe adding a description to the ZoomUtilities class could help to outline its purpose).

2024-03-11 22:27 UTC, antares1470 approved these changes

2024-03-17 23:02 UTC, Delphinus8821 approved these changes

2024-03-18 04:33 UTC, merged