Enhancement/wordcloud scrollbar
constellation-app/constellation pull request #1979
Opened 2024-03-12 05:53 UTC by Quasar985

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [x] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Added scroll bar to the "Generate Content" section of the word cloud view. Also altered height of pane that contains the contents of word cloud to be based on the window size, instead of being a constant value.

### Alternate Designs

It was considered to keep the height as a constant value, however doing so would result in an inconsistent scale of the content page depending on the screen's resolution.

### Why Should This Be In Core?

Fixes issue where, depending on the user's screen resolution, the button to generate the word cloud is inaccessible.

### Benefits

Fixes issue related to word cloud generation being inaccessible.

### Possible Drawbacks

The functionality to dynamically set the height of the pane may need tweaking if the word cloud view undergoes major layout changes.

### Verification Process

Verified visually, by changing the window size, and by moving constellation to different monitors.

### Applicable Issues

https://github.com/constellation-app/constellation/issues/1961

2024-03-12 21:44 UTC, Delphinus8821 requested changes
A couple of things:
If you make the pane narrower than it expects, it cuts off the generate button even when there is room below it to expand to 
![image](https://github.com/constellation-app/constellation/assets/73083035/f8354e0a-91f7-4484-841c-78db8f176009)

If you change your windows setting scaling to something quite zoomed in, the generate tab is still off of the screen. 
![image](https://github.com/constellation-app/constellation/assets/73083035/44c0bba2-1ac5-4bd3-9ee0-c48b8c9b37f9)

2024-03-12 21:44 UTC, Delphinus8821 commented on CoreWordCloudView/src/au/gov/asd/tac/constellation/views/wordcloud/ui/WordCloudPane.java
> +    public void setEverythingHeight(int h) {
parameter final

2024-03-14 21:50 UTC, antares1470 requested changes
Not sure if I'm a fan of the large gap being left at the top as it makes the Generate Word Cloud section look a little messy with its positioning. If possible, it would be good to have it as it was before with the panel showing the actual word cloud only displaying when there is something to be displayed.

![wordCloudPanePositioning](https://github.com/constellation-app/constellation/assets/62311243/cdad3f81-da73-436a-affb-af9cf5853a0e)

2024-03-14 21:50 UTC, antares1470 commented on CoreWordCloudView/src/au/gov/asd/tac/constellation/views/wordcloud/ui/WordCloudTopComponent.java
> +                wordCloudPane.setContentHeight((int) (double) newVal);
I think only one of these type casts needs to occur

2024-03-14 22:15 UTC, Delphinus8821 commented
> Not sure if I'm a fan of the large gap being left at the top as it makes the Generate Word Cloud section look a little messy with its positioning. If possible, it would be good to have it as it was before with the panel showing the actual word cloud only displaying when there is something to be displayed.
> 


I agree. It also looks a bit odd when there are not many words in the word cloud 

![image](https://github.com/constellation-app/constellation/assets/73083035/11e92963-8ad8-4499-9935-13c714bdc7a8)

2024-03-17 22:56 UTC, antares1470 requested changes
On my laptop, once you generate a word cloud, the view doesn't fit horizontally within the default dimensions of the view space (including the Generate Word Cloud section which prior to generating a word didn't suffer from that issue). Perhaps an addition of a horizontal scroll bar would be useful (or better if possible, fitting the view to the default width of the view).

![wordCloudHorizontal](https://github.com/constellation-app/constellation/assets/62311243/bae7c0d9-13cd-4221-bace-36ef6d27e155)

2024-03-17 22:56 UTC, Delphinus8821 approved these changes

2024-03-27 03:01 UTC, Delphinus8821 approved these changes

2024-03-27 03:28 UTC, antares1470 approved these changes

2024-03-27 03:28 UTC, merged