Graph Framework update
constellation-app/constellation pull request #2018
Opened 2024-04-16 01:46 UTC by antares1470

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Updated Core Graph Framework with java updates and other various code cleanup.

### Alternate Designs

### Why Should This Be In Core?

Updating Core code

### Benefits

Updated Core code

### Possible Drawbacks

### Verification Process

### Applicable Issues

#1987

2024-04-16 05:52 UTC, Delphinus8821 approved these changes

2024-04-17 02:08 UTC, OrionsGuardian requested changes

2024-04-17 02:08 UTC, OrionsGuardian commented on CoreGraphFramework/src/au/gov/asd/tac/constellation/graph/value/types/floats/FloatValue.java
>      public boolean equals(Object other) {
`final`

2024-04-17 04:42 UTC, OrionsGuardian approved these changes

2024-04-17 05:07 UTC, merged