Fix Light mode screen issues.
constellation-app/constellation pull request #2037
Opened 2024-04-30 06:38 UTC by OrionsGuardian

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Extended from some earlier work that was done to create a light mode for Constellation.
A number of screens have been further updated for light mode usage.

### Why Should This Be In Core?

Core UI enhancement when using a light mode Look and Feel.

### Benefits

The UI will have a more appropriate and consistent colour scheme when a light mode Look and Feel is being used.

### Verification Process

Change to a Light mode Look and Feel, such as "FlatLaf Light" and confirm that the screen elements are appropriately coloured for light mode usage.
Confirm the following changes:
Attribute Editor: Default lighter colours for each attribute element, and light background area for each element value.
Attribute Editor: Icon Editor dialog, background now allows white icons to be visible.
Data Access View: Workflow Options: Black version of icons now used in the menu.
Conversation View: Light grey background to allow white icons to be visible, and conversation bubbles have slightly brighter colour.
Notes View: Black text at the top of the note, and lighter default background colour.
Error Report View: Adjusted colour and sizing of components.

### Applicable Issues

#2016

2024-05-06 01:38 UTC, Delphinus8821 requested changes
Looks good apart from this weird mouse hover behaviour happening on the Icon Editor dialog in the Attribute Editor which only occurs in Light Mode.
![image](https://github.com/constellation-app/constellation/assets/73083035/a2d98275-a7ba-428f-b6f6-7462ceb195d5)

2024-05-06 01:38 UTC, Delphinus8821 commented on CoreErrorReportView/src/au/gov/asd/tac/constellation/views/errorreport/ErrorReportTopComponent.java
> +        String areaBackgroundColour = "radial-gradient(radius 100%, " + backgroundColour + " 0%, " + backgroundFadeColour + " 100%)";
final

2024-05-06 02:52 UTC, Delphinus8821 approved these changes

2024-05-06 05:55 UTC, antares1470 requested changes
A couple of things from testing:
1) For the Attribute editor, I think the blue for the custom attributes blends isn't distinct enough from the grey. Perhaps a darker blue might help? I would be saying similar things about the grey for the hidden attributes but I think the white text offers enough contrast.
![attributeEditorLightColours](https://github.com/constellation-app/constellation/assets/62311243/6c28427a-962e-471c-96d4-c30cd2e66d5c)

2) Probably doesn't need to be addressed here but figured it worth a mention. With changing the default color for notes in the Notes View, its worth noting that when saved, they are saved with that color and so if you switch to dark mode later, you still have the light colored note (and potentially a series of lighter and darker user notes if you don't change the colors manually)

2024-05-06 05:55 UTC, antares1470 commented on CoreErrorReportView/src/au/gov/asd/tac/constellation/views/errorreport/ErrorReportDialog.java
> +            public void changed(ObservableValue<? extends Number> observable, Number oldValue, Number newValue) {
can this be made a lambda (if not, parameters can be final)

2024-05-06 05:55 UTC, antares1470 commented on CoreErrorReportView/src/au/gov/asd/tac/constellation/views/errorreport/ErrorReportEntry.java
> +        if (adjustedHeading.endsWith("\n")) {
`SeparatorConstants.NEWLINE`

2024-05-07 04:26 UTC, antares1470 approved these changes
Having played around with it a little, I think there is possibly some further areas to improve the light/dark mode compatibility. One of the main issues is that a number of visual parts of the graph are saved with the graph and so this makes switching between light and dark mode interesting when your graphs don't really do the same thing (opening an old graph in light mode still has the dark background).

That being said, that's a much bigger potential body of work, and not one that needs to be addressed here

2024-05-07 04:30 UTC, merged