Select all nodes button and select all transactions button
constellation-app/constellation pull request #2059
Opened 2024-05-31 02:28 UTC by Quasar985

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Added "Select all Nodes" and "Select all Transactions" to the selection menu. Also created class to house shared functionality between existing and the new selection plugins.

### Alternate Designs

N/A

### Why Should This Be In Core?

N/A

### Benefits

Users can now more easily select all nodes or all transactions.

### Possible Drawbacks

None.

### Verification Process

Manual and automated testing.

### Applicable Issues

2024-05-31 05:36 UTC, Delphinus8821 requested changes
Looks good but can we change the menu option to be Select Nodes instead of Select Vertices, and can it be swapped so that Select Nodes is before Select Transactions in the menu options

2024-06-02 22:47 UTC, Delphinus8821 approved these changes

2024-06-02 23:35 UTC, antares1470 requested changes
Minor thing but I think the display names for the operations should correlate to their respective inverse operations
e.g. In the Selection Menu you have "Select All Nodes" and "Deselect Nodes"
Ideally, for consistency, it should either read as "Select Nodes" and "Deselect Nodes", or "Select All Nodes" and "Deselect All Nodes" (I personally prefer the former but that's just me, happy for you to choose which one you prefer)

2024-06-03 01:30 UTC, antares1470 requested changes
One more thing sorry, could you please add a whatsnew entry for this?

2024-06-03 04:01 UTC, antares1470 approved these changes

2024-06-03 04:01 UTC, merged