Bug/data access view option category changes
constellation-app/constellation pull request #2065
Opened 2024-06-04 03:49 UTC by Quasar985

### Prerequisites

- [
- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Added code to fix exception caused by removing all data access view plugins and added code to automatically refresh visible plugins in data access view.

### Alternate Designs

Could prompt the user to restart consty, similar to changing look and feel. The chosen solution doesn't require a restart, though.

### Why Should This Be In Core?

N/A

### Benefits

Fixes exception and saves user time as they no longer need to restart consty to see data access view changes.

### Possible Drawbacks

None.

### Verification Process

Manual and automated testing.

### Applicable Issues

https://github.com/constellation-app/constellation/issues/2055

2024-06-06 02:58 UTC, Delphinus8821 requested changes
Looks like it is working really well. No more errors and very responsive.

The warning on the options page to tell the users to restart Constellation for changes to take effect can be removed now.

2024-06-06 02:58 UTC, Delphinus8821 commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/components/DataAccessTabPane.java
> +    public void setPlugins(Map<String, Pair<Integer, List<DataAccessPlugin>>> newPlugins) {
final

2024-06-11 23:06 UTC, Delphinus8821 approved these changes

2024-06-12 02:37 UTC, antares1470 requested changes

2024-06-12 02:37 UTC, antares1470 commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/tasks/LookupPluginsTask.java
> +    public static Preferences getPreferences() {
can this be made protected if only being used for testing?

2024-06-12 02:37 UTC, antares1470 commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/components/DataAccessTabPane.java
> +    public void preferenceChange(PreferenceChangeEvent evt) {
parameter final

2024-06-12 03:59 UTC, capricornunicorn123 commented
Looks we have a functionality issue.

Selecting the name of a plugin, the name of a category or a collapse arrow should be able to collapse or expand the plugin or the category. In both of these cases, the plugins that are selected should persist and remain selected as indicated by the tick and the green box. However doing these actions appears to reset all plugins to unselected. Also note some formatting anomalies in the alignment of the `Select All` plugin when the data access view is refreshing.

![DAV being weird](https://github.com/constellation-app/constellation/assets/139201011/2bd9b41d-c781-43bb-b78e-f68c97e73b18)

Also, might be worth noting here as this is what I was trying to test. Are we happy with the functionality that when a plugin category containing selected plugins is removed and re added to the data access view, then these re-introduced, previously-selected plugins are deselected by default? I would assume this functionality is intuitive and easiest to implement however I'm unsure if users would appreciate the persistence of plugin selection through the hiding and unhiding process. 

i.e. `Select Top N` is selected > `Utility` is hidden > `Utility` is unhidden > the selection of `Select Top N` has not persisted through the hiding process and is now unselected.

2024-06-12 05:36 UTC, antares1470 commented
> Also, might be worth noting here as this is what I was trying to test. Are we happy with the functionality that when a plugin category containing selected plugins is removed and re added to the data access view, then these re-introduced, previously-selected plugins are deselected by default? I would assume this functionality is intuitive and easiest to implement however I'm unsure if users would appreciate the persistence of plugin selection through the hiding and unhiding process.
> 
> i.e. `Select Top N` is selected > `Utility` is hidden > `Utility` is unhidden > the selection of `Select Top N` has not persisted through the hiding process and is now unselected.

@capricornunicorn123 I think plugins being unselected after being hidden then unhidden is ok. The main reason I would suggest is the main use of the functionality. I would guess that normally if someone is moving a category to hidden, its because they don't have an interest in the plugins of that category and in that case, whether any of those plugins are selected or not is probably not important. If they do want to see it again, I suspect that will be dictated by use case, but probably not immediately after hiding.

Similarly for general use, I imagine people using Data Access View will adjust categories either before or after using the View, but probably not in the middle of use. 

The only case then (testing aside) where it could pop up would be following the steps you outlined with the caveat that hiding the category was accidental. But that seems very niche and highly unlikely. In fact in the general case, users may actually prefer plugins come back unselected because it may result in plugins being accidentally run if they didn't realise they were already selected (and weren't intending to run)

2024-06-12 05:54 UTC, capricornunicorn123 commented
> I think plugins being unselected after being hidden then unhidden is ok.

Brilliant, thanks for clarifying

2024-06-13 04:31 UTC, antares1470 requested changes

2024-06-13 04:31 UTC, antares1470 commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/panes/QueryPhasePane.java
> +            for (var entry : new HashMap<>(currentPlugins).entrySet()) {
`Map.Entry<String, HeadingPane>` instead of `var` (and final)

2024-06-17 06:14 UTC, antares1470 approved these changes

2024-06-17 06:15 UTC, merged