Documentation/updating documentation 2
constellation-app/constellation pull request #2085
Opened 2024-06-19 06:43 UTC by Quasar985

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Updated the following documentation:
- Composite Selected Nodes
- Composite Correlated Nodes
- Destroy All Composites
- Select All
- Select Top N
- Test Parameters
- Datetime Range
- Select Nodes
- Select Transactions
- Compare Graph
- General Selection

### Alternate Designs

N/A

### Why Should This Be In Core?

N/A

### Benefits

Updated documentation.

### Possible Drawbacks

N/A

### Verification Process

Tested manually.

### Applicable Issues

https://github.com/constellation-app/constellation/issues/340

2024-06-20 02:07 UTC, Delphinus8821 requested changes

2024-06-20 02:07 UTC, Delphinus8821 commented on CoreInteractiveGraph/release/modules/ext/docs/CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/composite-nodes.md
> +It can be expaned to reveal the ndoes contained within.
nodes

2024-06-20 02:07 UTC, Delphinus8821 commented on CoreInteractiveGraph/release/modules/ext/docs/CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/composite-nodes.md
> +by correlation are compsited together.
composited

2024-06-20 05:25 UTC, Delphinus8821 approved these changes

2024-06-20 23:08 UTC, antares1470 requested changes
A couple other things:
1) For the Composite Nodes pages, could you add a table at the top similar to what we have in other pages (such as General Selection) just to summarise how to access some of the actions
2) `interactivegraph-toc.xml` will also need to be updated in order for Composite Nodes to display in the Table of Contents (currently there isn't really a good way of seeing the help page unless you happen to know the file path off by heart). I suspect the page best fits in Graph > Editing (though there is an argument to put in Tools given a lot of the functionality is found in that menu)

2024-06-21 03:25 UTC, antares1470 approved these changes

2024-06-21 03:25 UTC, merged