Update Help Pages for Plugin Reporter, Quality Control, and Scripting View
constellation-app/constellation pull request #2091
Opened 2024-06-25 04:44 UTC by OrionsGuardian

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Updated the Help Pages for Plugin Reporter, Quality Control, and Scripting View.
Fixed some linked paths and formatting in the javadocs for the Scripting View.
Also modified the internal Help Page converter code to force UTF-8 as the character set for the locally built web pages.

### Why Should This Be In Core?

Documentation should reflect the current state of the product.

### Verification Process

Confirm the help pages for the Plugin Reporter, Quality Control, and Scripting View are up to date.

### Applicable Issues

#340

2024-06-25 06:16 UTC, Delphinus8821 requested changes
Would it be possible to add a help button to the Scripting View pane? The API Documentation button leads to the help page but I don't think users will necessarily think its the same.
Also the icon for the Plugin Reporter needs to be updated on the help page.

On the Scripting View help pages:
- the All Methods, Instance Methods and Concrete Methods links on the ScriptingUtilities, SAttribute, SCollection, SVertex, SLink, SReadableGraph, SWritableGraph, STransaction, SAttributeIterator, SEdgeIterator, SEdgeTransactionIterator, SLinkEdgeIterator, SLinkIterator,  SLinkTransactionIterator, STransactionIterator, SVertexEdgeIterator, SVertexIterator, SVertexLinkIterator, SVertexTransactionIterator, page don't go anywhere

- SGraph, SAttribute, SCollection, SEdge, SLink have weird symbols appearing 

- The navigation links don't need to appear at the top and bottom of each page

2024-06-27 02:34 UTC, antares1470 requested changes

2024-06-27 02:34 UTC, antares1470 commented on CoreQualityControlView/release/modules/ext/docs/CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/quality-control-view.md
> +*Note: A node is considered to have an OK Quality by default. Only when a rule fails will the Quality will be modified, matching the priority value assigned to the rule that failed.*
"will the quality be modified"

2024-06-27 02:34 UTC, antares1470 commented on CoreQualityControlView/release/modules/ext/docs/CoreQualityControlView/src/au/gov/asd/tac/constellation/views/qualitycontrol/quality-control-view.md
> +&nbsp; &nbsp; &nbsp; *If multiple rules fail, then the Quality for the node will be set to the highest priority value from among the rules that failed.*
I think the formatting here also doesn't appear to have worked

2024-06-27 23:31 UTC, Delphinus8821 approved these changes

2024-06-27 23:32 UTC, antares1470 approved these changes

2024-06-27 23:32 UTC, merged