Fix incorrect warning when opening file
constellation-app/constellation pull request #2112
Opened 2024-07-04 01:14 UTC by Quasar985

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Fixed bug that would cause a warning to be shown, telling users that the file they were opening in word cloud would be overridden.

### Alternate Designs

N/A

### Why Should This Be In Core?

N/A

### Benefits

Bug fix, minimizing confusion.

### Possible Drawbacks

None.

### Verification Process

### Applicable Issues

https://github.com/constellation-app/constellation/issues/2111

2024-07-04 03:00 UTC, Delphinus8821 approved these changes

2024-07-04 06:11 UTC, Auriga2 commented
Thought it'd be convenient if we can restrict the file types to text files. Currently it displays the entire directory including .bak, .star, .gif and all.

2024-07-04 23:51 UTC, antares1470 requested changes

2024-07-04 23:51 UTC, antares1470 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/gui/FileInputPane.java
> +                case OPEN, OPEN_OBSCURED -> dialogFuture = FileChooser.openOpenDialog(getFileChooser(parameter, "Open", FileExtensionConstants.TEXT)).thenAccept(optionalFile -> optionalFile.ifPresent
not sure I'm a fan of this one as this default then also applies to any use of the File Input Pane, notably plugin parameters
e.g. Input File parameter of Test Parameters. Probably need to find a way to include that filter only for word cloud use case

2024-07-21 23:17 UTC, antares1470 commented on CorePluginFramework/test/unit/src/au/gov/asd/tac/constellation/plugins/parameters/types/FileParameterTypeNGTest.java
> +import com.jogamp.newt.event.KeyEvent;
Thoguht this might need to be `javafx.scene.input.KeyEvent` but it seems its actually unused and can be removed.

2024-07-21 23:17 UTC, antares1470 commented on CorePluginFramework/test/unit/src/au/gov/asd/tac/constellation/plugins/parameters/types/FileParameterTypeNGTest.java
> +import javafx.scene.input.KeyCode;
can also be removed

2024-07-21 23:17 UTC, antares1470 commented on CoreTesting/test/unit/src/au/gov/asd/tac/constellation/testing/ExportGlyphTexturesActionNGTest.java
> +        System.out.println(optionalFile == null);
can these couple lines be removed?

2024-07-22 00:22 UTC, antares1470 approved these changes

2024-07-22 00:22 UTC, merged