Fix the conversation view to not show conversations from other graphs.
constellation-app/constellation pull request #2169
Opened 2024-08-01 02:42 UTC by Auriga2

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Conversation view no longer shows conversations from the last viewed graph when the current graph does not contain conversation data of its own.

### Alternate Designs

### Why Should This Be In Core?
Bug fix

### Benefits
Bug fix

### Possible Drawbacks

### Verification Process

1. Open a graph with conversation data
2. Create a new graph and add 2 nodes and a transaction, which would not have conversation data to display
3. Open Conversation View and verify conversations are shown when the first graph is selected
4. Verify conversations clear when the nodes are selected on the second graph

### Applicable Issues
https://github.com/constellation-app/constellation/issues/2149

2024-08-01 04:28 UTC, Delphinus8821 approved these changes

2024-08-01 04:39 UTC, OrionsGuardian requested changes
The code change does work to address the described issue, but I found another related issue that should also be addressed at the same time.

Test the case where you have one graph (A) with Conversation data and another graph (B) without Conversation data.
Select a node in graph A, see the Conversations displayed in the view.
Switch to graph B.
Deselect all nodes there.
Switch back to graph A.
The currently selected node in graph A is now not showing its Conversation data.
You need to select a different node to see any Conversation data again.

2024-08-01 04:51 UTC, antares1470 approved these changes

2024-08-01 23:57 UTC, Delphinus8821 approved these changes

2024-08-04 22:26 UTC, antares1470 approved these changes

2024-08-11 23:25 UTC, merged