Testable Graph Builder exception fix
constellation-app/constellation pull request #2178
Opened 2024-08-07 07:04 UTC by Auriga2

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
The exception was throwing if Experimental ->Developer ->Testable Graph Builder was clicked while there's a non empty graph open in constellation. Fixed it by opening the Testable Graph in a new analytic graph rather than just showing a warning message.

### Alternate Designs
Could have just shown a warning message, but opening it in a new graph with the same click make it even easier for developers. 

### Why Should This Be In Core?
Fix exception

### Benefits
Open Testable graph with one click

### Possible Drawbacks

### Verification Process
Select Experimental ->Developer ->Testable Graph Builder without opening any graphs and with any open graphs

### Applicable Issues
https://github.com/constellation-app/constellation/issues/2150

2024-08-08 01:41 UTC, Delphinus8821 approved these changes

2024-08-09 06:13 UTC, mimosa2 approved these changes

2024-08-11 23:33 UTC, antares1470 requested changes

2024-08-11 23:33 UTC, antares1470 commented on CoreTesting/src/au/gov/asd/tac/constellation/testing/construction/TestableGraphBuilderAction.java
> +import static org.geotools.referencing.factory.ReferencingFactory.LOGGER;
I assume this is actually meant to be a local instance of the java logger instead?

2024-08-12 03:37 UTC, antares1470 approved these changes

2024-08-12 03:37 UTC, merged