Update NotifyDisplayer to popup on same screen
constellation-app/constellation pull request #2193
Opened 2024-08-22 07:22 UTC by andromeda-224

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

- Added overloaded method for NotifyDisplayer.displayAlert and NotifyDisplayer.displayLargeAlert to be able to set the dialog to pop up at specified point. 
- Added new utility to obtain the main window's centre (ScreenWindowsHelper.getNewCentrePoint())
- Updated some actions to utilise the new utility to set the displayAlerts to be displayed on the same screen/monitor: Compare graph, template warning messages, test notifications
- Added 2 unit tests to test passing in the point parameter

### Alternate Designs

### Why Should This Be In Core?

### Benefits
To display Alerts on the same screen as the app.

### Possible Drawbacks

### Verification Process

1. Create a new Graph.
2. Select menu item Experimental -> Developer -> Test Notifications
All notifications/dialogs should be displayed on the same screen as the app.
3. Move the app to another screen and select menu item Experimental -> Developer -> Test Notifications.
All notifications/dialogs should be displayed on the same screen as the app.

1. Have just one graph open.
2. Select menu item Tools -> Compare Graph
The warning dialog should appear on the same screen as the app
Move the app to another screen and repeat the steps.
The warning dialog should appear on the same screen as the app

1. Select menu item File -> Import-> From File...
2. Click the "+" to add a file
3. In File Name textbox, enter a non-existent file eg. abcdefg
4. Click open
5. The warning dialog of "Invalid file(s) found" should appear on the same screen as the app.
Move the app to another screen and repeat the steps.
The warning dialog should appear on the same screen as the app

### Applicable Issues
#2159

2024-08-26 06:03 UTC, Delphinus8821 approved these changes

2024-08-26 09:02 UTC, andromeda-224 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/gui/ScreenWindowsHelper.java
> +                break;
Done!

2024-08-26 22:51 UTC, antares1470 requested changes

2024-08-26 22:51 UTC, antares1470 commented on CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/gui/ScreenWindowsHelperNGTest.java
> + * Copyright 2010-2024 Australian Signals Directorate
minor but could the license copyright be put at the top of the file?

2024-08-26 22:51 UTC, antares1470 commented on CoreUtilities/test/unit/src/au/gov/asd/tac/constellation/utilities/gui/ScreenWindowsHelperNGTest.java
> +    public void testGetMainWindowCentrePoint() {
Looks like there are potentially 3 different tests sitting in this one test method. Could these be split up into their own test methods (you wouldn't then need to use `fail()`)

2024-08-27 02:05 UTC, Quasar985 approved these changes

2024-08-27 02:29 UTC, antares1470 approved these changes

2024-08-27 02:29 UTC, merged