Update to wrap text
constellation-app/constellation pull request #2204
Opened 2024-09-09 01:45 UTC by andromeda-224

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Added code in TableCellFactory to wrap text within table column width.
Added appropriate selectors to set new Text node text colours to behave as before.

### Alternate Designs
Setting text wrap in css expanded the column width to the length of the text, which is not preferred behaviour.
This solution allowed text wrap within the table column width setting.

### Why Should This Be In Core?

### Benefits
To be able to view the text to be viewed easily (especially if it has no whitespace)

### Possible Drawbacks

### Verification Process

1. Open Constellation and open a graph
2. Create a node, make the identifier a really long name
3. Open Table View, switch to node view.
Observe that the identifier column holds the entire name wrapped within the column.

### Applicable Issues
#1983

2024-09-09 06:37 UTC, mimosa2 approved these changes

2024-09-10 03:57 UTC, OrionsGuardian requested changes

2024-09-10 03:57 UTC, OrionsGuardian commented on CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/factory/TableCellFactory.java
> +                Text text = getWrappingText(item);
`final`

2024-09-10 03:57 UTC, OrionsGuardian commented on CoreTableView/src/au/gov/asd/tac/constellation/views/tableview/factory/TableCellFactory.java
> +        Text text = new Text(item);
`final`

2024-09-10 04:34 UTC, Quasar985 approved these changes

2024-09-10 07:33 UTC, OrionsGuardian requested changes

2024-09-10 07:33 UTC, OrionsGuardian commented on CoreTableView/test/unit/src/au/gov/asd/tac/constellation/views/tableview/factory/TableCellFactoryNGTest.java
>  import static org.mockito.ArgumentMatchers.anyString;
This is now an unused import and can be removed.

2024-09-11 00:45 UTC, antares1470 approved these changes

2024-09-11 00:46 UTC, merged