Draft: Hierarchical arrangement enhancements
constellation-app/constellation pull request #2211
Opened 2024-09-29 23:43 UTC by OrionsGuardian

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

The hierarchical arrangement will now organise the nodes in a strict top-down arrangement.
It will no longer generate "pendants" that are placed in a non-hierarchical orientation (where links would often go back over the base hierarchy causing unnecessary overlapping lines)

An additional change has been made in the general usage of the hierarchical plugin.
You can now select one or more nodes, run the plugin, and choose to use the selected nodes as the root nodes in the hierarchy.
You can still use the former functionality to choose a Named Selection to identify the root nodes of the hierarchy, in which case, any selected nodes will limit which nodes have the arrangement performed on them.

### Alternate Designs

There are various parameters that can be tweaked to try and obtain the best arrangement with minimal lines crossing.
There are also fixed time limits imposed to control how much smoothing is done to an arrangement, and keep the system responsive.
Large graphs can take a long time to arrange nicely.
There is a cutoff of 10,000 graph elements, after which no smoothing will be performed, as it is a very time-consuming task.
For large graphs that are below 10,000 elements, there is a time allowance of 15 seconds of smoothing.

### Why Should This Be In Core?

Standard functionality for a hierarchical arrangement.

### Benefits

Improved hierarchical layout, no segments being placed in a way that goes against the layout arrangement.

### Possible Drawbacks

Excessively large graphs will not have an ideal arrangement.

### Verification Process

Create a sphere graph
Select a node
Run the hierarchy arrangement (Ctrl-H)
Press OK (using the selected node as the root of the hierarchy)
Confirm that connected segments are arranged into a hierarchy.

### Applicable Issues

#372

2024-10-14 02:28 UTC, antares1470 requested changes

2024-10-14 02:28 UTC, antares1470 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/ArrangeInHierarchyAction.java
> +        final int vxSelectedAttr = rg.getAttribute(GraphElementType.VERTEX, VisualConcept.VertexAttribute.SELECTED.getName());
`VisualConcept.VertexAttribute.SELECTED.get(rg)`

2024-10-14 02:28 UTC, antares1470 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/ArrangeInHierarchyAction.java
> +
remove the extra whitespace here

2024-10-14 02:28 UTC, antares1470 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/ArrangeInHierarchyAction.java
> +
same here

2024-10-14 02:28 UTC, antares1470 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/HierarchicalArranger.java
> +        int totalVertices = wg.getVertexCount();
final

2024-10-14 02:28 UTC, antares1470 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/HierarchicalArranger.java
> +        final int yId = wg.getAttribute(GraphElementType.VERTEX, VisualConcept.VertexAttribute.Y.getName());
`VisualConcept.VertexAttribute.X.get(wg)`, similar for `Y`

2024-10-14 02:28 UTC, antares1470 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/HierarchicalArranger.java
> +        final int yId = wg.getAttribute(GraphElementType.VERTEX, VisualConcept.VertexAttribute.Y.getName());
same case here

2024-10-14 02:28 UTC, antares1470 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/tree/ArrangeInBubbleTreeAction.java
> +        final int vxSelectedAttr = rg.getAttribute(GraphElementType.VERTEX, VisualConcept.VertexAttribute.SELECTED.getName());
same here

2024-10-14 02:28 UTC, antares1470 commented on CoreArrangementPlugins/test/unit/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/HierarchicalArrangerNGTest.java
> +        }
few instances like this one: given nothing happens after this, might be better to throw the exception here, rather than catch

2024-10-14 05:59 UTC, Quasar985 reviewed
Sonar is also complaining about the formatting of `HierarchicalArranger.java`. I think this could be fixed with netbeans' auto-formatting

2024-10-14 05:59 UTC, Quasar985 commented on CoreArrangementPlugins/test/unit/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/HierarchicalArrangerNGTest.java
> +        WritableGraph wg = graph.getWritableGraph("", true);
final

2024-10-14 05:59 UTC, Quasar985 commented on CoreArrangementPlugins/test/unit/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/HierarchicalArrangerNGTest.java
> +        String lastMessage = instance.getLastMessage();
`wg`, `instance` and `lastMessage` could be final

2024-10-14 05:59 UTC, Quasar985 commented on CoreArrangementPlugins/test/unit/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/HierarchicalArrangerNGTest.java
> +        ArrangeInHierarchyAction hierAction = new ArrangeInHierarchyAction(contextMock);
Variables declared here could all be final

2024-10-14 05:59 UTC, Quasar985 commented on CoreArrangementPlugins/test/unit/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/HierarchicalArrangerNGTest.java
> +        String lastMessage = instance.getLastMessage();
`wg`, `instance` and `lastMessage` could be final

2024-10-14 05:59 UTC, Quasar985 commented on CoreArrangementPlugins/test/unit/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/HierarchicalArrangerNGTest.java
> +        String lastMessage = instance.getLastMessage();
`wg`, `instance` and `lastMessage` could be final

2024-10-14 05:59 UTC, Quasar985 commented on CoreArrangementPlugins/test/unit/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/HierarchicalArrangerNGTest.java
> +        int vertexIdentifierAttribute = VisualConcept.VertexAttribute.IDENTIFIER.ensure(wg);
final

2024-10-14 05:59 UTC, Quasar985 commented on CoreArrangementPlugins/test/unit/src/au/gov/asd/tac/constellation/plugins/arrangements/hierarchical/HierarchicalArrangerNGTest.java
> +            int parentCount = parentLevel.size();
final

2024-10-14 22:31 UTC, Delphinus8821 approved these changes
Looks good once the other requested changes have been fixed.

2024-10-16 00:07 UTC, antares1470 approved these changes

2024-10-17 21:24 UTC, merged