Added plugin info from Data Access View plugins to plugin reporter
constellation-app/constellation pull request #2214
Opened 2024-10-10 07:41 UTC by andromeda-224

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Added time, parameters (if any), and selected items (nodes/transactions) if any, to the description sent to the plugin reporter from Data Access View plugins.

### Alternate Designs

### Why Should This Be In Core?

### Benefits

### Possible Drawbacks

### Verification Process

1. Run Constellation
2. Open a graph
3. Open Data Access View
4. Test with the various plugins

Time, parameters and in some cases selected nodes/transactions may be seen in the plugin reporter.

### Applicable Issues
#49

2024-10-16 03:32 UTC, mimosa2 reviewed
I did some testing on this change. Looks like the included information about the plugin run doesn't copied to the clipboard (right click on the plugin reporter pane -> Save Details To Clipboard). I am not sure this is within the scope of this change.

2024-10-16 06:31 UTC, andromeda-224 commented
> I did some testing on this change. Looks like the included information about the plugin run doesn't copied to the clipboard (right click on the plugin reporter pane -> Save Details To Clipboard). I am not sure this is within the scope of this change.

At the moment, it is only copying the last message that appears in the report, which is made up of multiple messages (as seen in the plugin reporter). How about if I add all the messages that appear in the plugin report?

2024-10-17 22:23 UTC, antares1470 requested changes

2024-10-17 22:23 UTC, antares1470 commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeNodesPlugin.java
> +            GraphRecordStore allSelectedNodes = GraphRecordStoreUtilities.getSelectedVertices(graph);
final

2024-10-17 22:23 UTC, antares1470 commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/MergeTransactionsPlugin.java
> +            RecordStore allSelectedTx = GraphRecordStoreUtilities.getSelectedTransactions(graph);
final

2024-10-17 22:23 UTC, antares1470 commented on CoreDataAccessView/src/au/gov/asd/tac/constellation/views/dataaccess/plugins/clean/SplitNodesPlugin.java
> +        GraphRecordStore allSelectedNodes = GraphRecordStoreUtilities.getSelectedVertices(graph);
final

2024-10-17 22:23 UTC, antares1470 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/PluginInteraction.java
> +    void setProgress(final int currentStep, final int totalSteps, final String message, final boolean cancellable, PluginParameters parameters, final int selected) throws InterruptedException;
`parameters` can be final

2024-10-17 22:23 UTC, antares1470 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/text/TextPluginInteraction.java
> +    public void setProgress(final int currentStep, final int totalSteps, final String message, final boolean cancellable, PluginParameters parameters) throws InterruptedException {
same here

2024-10-17 22:23 UTC, antares1470 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/text/TextPluginInteraction.java
> +        }
this can probably be reduced to a ternary statement and then can be made final

2024-10-17 22:23 UTC, antares1470 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/text/TextPluginInteraction.java
> +        }
sane case here

2024-10-17 22:23 UTC, antares1470 commented on CorePluginFramework/src/au/gov/asd/tac/constellation/plugins/text/TextPluginInteraction.java
> +    public void setProgress(int currentStep, int totalSteps, String message, boolean cancellable, PluginParameters parameters, int selected) throws InterruptedException {
parameters can be made final

2024-10-23 05:02 UTC, antares1470 requested changes
I think the timestamp is possibly being added more than need be. When I run split nodes for instance, it seems to add a mention of the time after every mention of nodes being split. e.g.
```
Time: ...
Node Vertex #0 split into 2 nodes
Time: ...
Node Vertex #1 split into 2 nodes
Time: ...
etc.
```
If we're just noting the time when the plugin was first executed, I think it should only need to be displayed once at the beginning (given we already also display the duration of the plugin execution)

2024-10-24 05:10 UTC, andromeda-224 commented
> I think the timestamp is possibly being added more than need be. When I run split nodes for instance, it seems to add a mention of the time after every mention of nodes being split. e.g.
> 
> ```
> Time: ...
> Node Vertex #0 split into 2 nodes
> Time: ...
> Node Vertex #1 split into 2 nodes
> Time: ...
> etc.
> ```
> 
> If we're just noting the time when the plugin was first executed, I think it should only need to be displayed once at the beginning (given we already also display the duration of the plugin execution)

I've added a setProgressTimestamp function which only adds the timestamp to the message. This can now be used wherever we want the timestamp in the plugin report.

2024-10-31 01:02 UTC, Quasar985 requested changes

2024-11-01 02:46 UTC, Delphinus8821 approved these changes

2024-11-03 23:49 UTC, OrionsGuardian requested changes

2024-11-06 01:42 UTC, mimosa2 approved these changes

2024-11-06 21:41 UTC, antares1470 approved these changes

2024-11-06 21:41 UTC, merged