Update help documentation in analytic view for questions
constellation-app/constellation pull request #2223
Opened 2024-10-30 02:01 UTC by Delphinus8821

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Updated the documentation pane in the Analytic View to also show the help documentation for questions. 

### Alternate Designs

### Why Should This Be In Core?
Makes more help available to be viewed from within the Analytic View 

### Benefits
Makes the help documentation easier to find by being available without having to open help

### Possible Drawbacks

### Verification Process
Open the Analytic View and the Documentation pane 
Select a question
See that the help pages display for the questions 

### Applicable Issues
#2222

2024-10-30 04:43 UTC, antares1470 reviewed
A couple of things found, which displaying the question pages has exposed:
1) The hyperlinks in the pages don't work when clicked in the documentation tab (but perhaps we want to keep it that way)
2) In dark mode, the link blue colour is difficult to read. Might be nice if we can make it lighter for dark mode (potentially even just make it white if the links don't work anyway, and black for light mode)
![analyticQuestionHelp](https://github.com/user-attachments/assets/ebb5d951-8c3e-4042-b416-b07d8f03801f)

2024-10-30 22:15 UTC, OrionsGuardian requested changes

2024-10-30 22:15 UTC, OrionsGuardian commented on CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/utilities/AnalyticUtilities.java
> +        final String sep = File.separator;
This could be moved out of the method and defined as a class member variable:
`private static final String SEP = File.separator;`

2024-10-30 22:29 UTC, OrionsGuardian requested changes
Functionality issue:
Click on a Question and it gives you the correct help page.
Click on an Analytic Entry and it gives you the detailed help for that Analytic.
Now click on a different Question and you get a `No documentation Available` message instead of the help page.

2024-10-31 00:26 UTC, Quasar985 approved these changes

2024-10-31 21:49 UTC, OrionsGuardian approved these changes

2024-10-31 22:15 UTC, antares1470 approved these changes

2024-10-31 22:15 UTC, merged