Module security updates and unit test fix.
constellation-app/constellation pull request #2236
Opened 2024-11-20 00:33 UTC by OrionsGuardian

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Fixed some module security issues found while running unit tests independently.

### Alternate Designs

### Why Should This Be In Core?

Unit tests should run without issues whichever way they are launched.

### Benefits

### Possible Drawbacks

### Verification Process

### Applicable Issues

2024-11-20 21:40 UTC, antares1470 requested changes

2024-11-20 21:40 UTC, antares1470 commented on CoreConversationView/test/unit/src/au/gov/asd/tac/constellation/views/conversationview/ConversationViewTopComponentNGTest.java
> +                System.out.println("\n**** UN-EXPECTED TEARDOWN ERROR: " + e.toString());
can these be converted to log entries?

2024-11-20 21:40 UTC, antares1470 commented on CoreConversationView/test/unit/src/au/gov/asd/tac/constellation/views/conversationview/ConversationViewTopComponentNGTest.java
> +            }
More for curiosity: is there a reason why need to include this extra condition in this case? Noting that we haven't needed to include this elsewhere so wondering what happens here that needs this extra catch?

2024-11-22 00:09 UTC, Quasar985 approved these changes

2024-11-22 03:33 UTC, Delphinus8821 approved these changes

2024-11-26 22:47 UTC, antares1470 approved these changes

2024-11-26 22:48 UTC, merged