Analytic Schema Cleanup
constellation-app/constellation pull request #2243
Opened 2024-11-28 05:18 UTC by antares1470

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

The original intention of this was to add unit tests to all of Core Analytic Schema but due to the number of other issues identified, I ended up deciding this will need to be done in a multiple parts.

This includes the following:
- Unit tests for AnalyticSchemaFactory, AnalyticDominanceCalculator, Compatibility classes, and Concept classes
- fixed a bug with transaction attributes in TemporalConcept created as vertex attributes (note there is no accompanying schema updater for this change as there is no way for the graph to distinguish between the what was meant to be the transaction type and the vertex type with the same name. Basically they ended up merging to be the same type and so effectively, the transaction type didn't exist)
- fixed a few other bugs identified along the way
- removed a few unused classes 
- other general code cleanup

### Alternate Designs

### Why Should This Be In Core?

More unit tests for core code, less bugs, easier to maintain

### Benefits

More unit tests for core code, less bugs, easier to maintain

### Possible Drawbacks

### Verification Process

### Applicable Issues

#413

2024-12-01 23:16 UTC, Delphinus8821 requested changes

2024-12-01 23:16 UTC, Delphinus8821 commented on CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/compatibility/AnalyticSchemaV5UpdateProvider.java
> +        final int oldInfomapColourAttributeIdVertex = graph.getAttribute(GraphElementType.VERTEX, INFOMAP_COLOUR);
Can we remove the u in the color part in this variable name for consistency?

2024-12-01 23:53 UTC, Quasar985 approved these changes

2024-12-02 03:00 UTC, OrionsGuardian requested changes

2024-12-02 21:08 UTC, antares1470 commented on CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/compatibility/AnalyticSchemaV2UpdateProviderNGTest.java
> +        typeTransactionAttribute = graph.getAttribute(GraphElementType.TRANSACTION, "Type");
Technically if you comment out these lines the test still passes as the ids end up being the same. But its worth noting that the schema updater actually deletes the old attribute and so doing this again ensures that we grab the correct id (and that it's not coincidence that the ids line up). I've added a comment to explain it.

2024-12-02 21:45 UTC, OrionsGuardian approved these changes

2024-12-02 22:16 UTC, Delphinus8821 approved these changes

2024-12-03 21:04 UTC, merged