More Analytic Schema Tests
constellation-app/constellation pull request #2247
Opened 2024-12-16 04:52 UTC by antares1470

### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Added unit tests for the remaining classes in Core Analytic Schema requiring testing. Also updated some tests from the previous PR.

Also like the last one, included a small amount of code cleanup.

### Alternate Designs

### Why Should This Be In Core?

More unit tests is better.

### Benefits

More unit tests

### Possible Drawbacks

### Verification Process

### Applicable Issues
#413

2024-12-16 05:37 UTC, OrionsGuardian requested changes

2024-12-16 05:37 UTC, OrionsGuardian commented on CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/objects/ContractedCompositeNodeState.java
> +        // Correct the x,y,z coordinates of the nodes in the consitutentNodeStore in case the composite node has been moved.
Typo: constituentNodeStore

2024-12-16 05:37 UTC, OrionsGuardian commented on CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/compatibility/AnalyticSchemaV5UpdateProvider.java
> -                final SchemaAttribute oldKTruss = graph.getObjectValue(oldKTrussColorAttributeIdTransaction, transactionId);
SchemaAttribute is now an unused import.

2024-12-16 05:37 UTC, OrionsGuardian commented on CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/TransactionTypeAttributeDescriptionNGTest.java
> +import static org.testng.Assert.fail;
unused import

2024-12-16 05:37 UTC, OrionsGuardian commented on CoreAnalyticSchema/test/unit/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/TransactionTypeAttributeDescriptionNGTest.java
> +import au.gov.asd.tac.constellation.graph.value.readables.IntReadable;
unused import

2024-12-17 04:09 UTC, OrionsGuardian requested changes

2024-12-17 04:09 UTC, OrionsGuardian commented on CoreAnalyticSchema/src/au/gov/asd/tac/constellation/graph/schema/analytic/attribute/objects/ContractedCompositeNodeState.java
> +        // Correct the x,y,z coordinates of the nodes in the constitutentNodeStore in case the composite node has been moved.
There's still a typo (an extra 't') in: `constituent`

2024-12-17 04:20 UTC, OrionsGuardian approved these changes

2024-12-17 04:35 UTC, Delphinus8821 approved these changes

2024-12-17 21:25 UTC, merged