Use custom class loaders to load Languagetool dependencies
constellation-app/constellation pull request #2248
Opened 2024-12-17 07:19 UTC by Auriga2

### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Custom class loaders are now used to load Languagetool dependencies, to avoid indriya version conflicts.

 languagetool requires indriya v1.3 or earlier while systems-common used by gt-opengis is not compatible with 1.3 and requires a later version. (v2.0.2 or latest v2.2) This caused https://github.com/constellation-app/constellation/issues/2054

All other approaches I've tried, like ivy configs,  Maven Shade Plugin and Relocation, only works for build-time conflicts. In our scenario we need to isolate 2 versions of the same library at runtime.  Using a Custom ClassLoader seems to be the only possibility.

I used ivy configs to isolate the languagetool libs into a separate folder, rather than listing all the transient dependencies of languagetool in the code. The latter could cause version conflicts, as Ivy might resolve to different versions than those we have hard-coded. On the other hand ivy configs duplicates the common  transient libraries.

I am loading only the Languagetool dependencies separately, keeping the rest of the constellation intact, to avoid too much complications, and when the Languagetool developers fix their issue we can easily revert the changes. (Usually both versions of the dependency is loaded using custom class loaders)

Know issues:
Undo after Ignore all doesn't work

To Do:
Find a way to reuse the common transient libraries.

### Alternate Designs

- Fix the bug in  org.languagetool
- Use a different spell check library

### Why Should This Be In Core?
Enables spell checking in enabled text fields

### Benefits

### Possible Drawbacks
Complex coding

### Verification Process
Verify spell checking works (in Data access view) as well as schema view loads without any exception.

### Applicable Issues
https://github.com/constellation-app/constellation/issues/870

2025-01-13 03:44 UTC, OrionsGuardian requested changes

2025-01-13 03:44 UTC, OrionsGuardian commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/LanguageToolDependencyUrlLoader.java
> +        ProtectionDomain domain = LanguageToolDependencyUrlLoader.class.getProtectionDomain();
`final`

2025-01-13 03:44 UTC, OrionsGuardian commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/LanguageToolDependencyUrlLoader.java
> +            File libLanguageToolFolder = new File(jarFolder, "ext/languagetoolconf");
`final`

2025-01-13 03:44 UTC, OrionsGuardian commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/LanguageToolDependencyUrlLoader.java
> +            File[] libLanguageToolFiles = libLanguageToolFolder.listFiles((dir, name) -> name.endsWith(".jar"));
`final`

2025-01-13 03:44 UTC, OrionsGuardian commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/LanguageToolDependencyUrlLoader.java
> +            URL[] libLanguageToolUrls = new URL[libLanguageToolFiles.length];
`final`

2025-01-13 03:44 UTC, OrionsGuardian commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/LanguagetoolClassLoader.java
> +    private LanguagetoolClassLoader(URL[] urls) {
`final`

2025-01-13 03:44 UTC, OrionsGuardian commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/LanguagetoolClassLoader.java
> +                URL[] urls = LanguageToolDependencyUrlLoader.loadUrls();
`final`

2025-01-13 03:44 UTC, OrionsGuardian commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> +                        Constructor<?> constructor = Languages.getDeclaredConstructor();
`final`

2025-01-13 03:44 UTC, OrionsGuardian commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> +                        Object languages = constructor.newInstance();
`final`

2025-01-13 03:44 UTC, OrionsGuardian commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> +                    } catch (NoSuchMethodException | SecurityException | InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
`final`

2025-01-13 03:44 UTC, OrionsGuardian commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> +            List<?> rules = (List<?>) JLanguagetool.getMethod("getAllRules").invoke(langTool);
`final`

2025-01-13 03:44 UTC, OrionsGuardian commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> +                    //langTool.get().disableRule(rule.getId());
remove commented code

2025-01-13 03:44 UTC, OrionsGuardian commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> +                        } catch (IllegalAccessException | InvocationTargetException | NoSuchMethodException | SecurityException ex) {
`final`

2025-01-13 03:44 UTC, OrionsGuardian commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> +            } catch (IllegalAccessException | InvocationTargetException | NoSuchMethodException | SecurityException ex) {
`final`

2025-01-13 03:44 UTC, OrionsGuardian commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> +            } catch (SecurityException | InvocationTargetException | NoSuchMethodException | IllegalAccessException ex) {
`final`

2025-01-20 00:12 UTC, antares1470 requested changes

2025-01-20 00:12 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/LanguageToolDependencyUrlLoader.java
> + * Copyright 2010-2024 Australian Signals Directorate
2025

2025-01-20 00:12 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/LanguageToolStartUpLoad.java
> + * Copyright 2010-2024 Australian Signals Directorate
same here

2025-01-20 00:12 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/LanguagetoolClassLoader.java
> + * Copyright 2010-2024 Australian Signals Directorate
and here

2025-01-20 00:12 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/LanguagetoolClassLoader.java
> +            } catch (MalformedURLException | ClassNotFoundException ex) {
final

2025-01-20 00:12 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/LanguagetoolClassLoader.java
> +    public static Class<?> SpellingCheckRule;
these variables should all start lowercase. Also can they be made private with getter functions

2025-01-20 00:12 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.css
> +Copyright 2010-2023 Australian Signals Directorate
2025

2025-01-20 00:12 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> + * Copyright 2010-2023 Australian Signals Directorate
same here

2025-01-20 00:12 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> +        }, Executors.newSingleThreadExecutor());
Should this be using the global thread pool? (answer could be no, but if yes, we should look to use that instead)

2025-01-20 00:12 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> +        } catch (IllegalAccessException | InvocationTargetException | NoSuchMethodException | InstantiationException | SecurityException ex) {
final

2025-01-20 00:12 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> +            return !newText.isEmpty() && (textArea.isWordUnderCursorHighlighted(caretPosition - 1) || !charAtCaret.matches("[a-zA-Z0-9']"));
for the regex here, can this pattern be pre-compiled? i.e. use a Pattern object for the regex

2025-01-20 00:12 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> +            } catch (IllegalAccessException | InvocationTargetException | NoSuchMethodException ex) {
final

2025-01-20 00:12 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> +    private static void logAndDisplayErrorMessage(String message, Exception ex) {
parameters final

2025-01-20 00:12 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellCheckingTextArea.java
> + * Copyright 2010-2023 Australian Signals Directorate
2025

2025-01-20 00:12 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellCheckingTextArea.java
> +        return (this.getStyleOfChar(index) != null ? this.getStyleOfChar(index).equals(UNDERLINE_AND_HIGHLIGHT_STYLE) : false);
`return this.getStyleOfChar(index) != null && this.getStyleOfChar(index).equals(UNDERLINE_AND_HIGHLIGHT_STYLE)`

2025-02-03 06:52 UTC, Auriga2 commented on CoreDependencies/src/ivy.xml
> +        <dependency org="tech.units" name="indriya" rev="2.2" conf="defaultconf"/>
Agree, not needed for both versions. Geotools actually brings in 2.0.2

2025-02-05 08:01 UTC, Auriga2 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> +        }, Executors.newSingleThreadExecutor());
Not quite sure, just did the same as other places a static initializer is used, i.e., RunPane.java and DataAccessPaneState.java.  A static initializer is executed only once when the class is first loaded into memory. I guess that's why a global thread pool is not necessary?

2025-04-04 07:16 UTC, Auriga2 commented
To reuse the common transient libraries I let ivy resolve all dependencies in the same location, which avoids duplication. Then in the code I am keeping a list of the jars used by Languagetool in a text file and load those jars from the common location, ignoring the version numbers. 

The conflicting library `Indriya` is resolved into a separate folder `languagetoolconf`. `Indiya 1.3`'s transient dependency `uom-lib-common-1.1.jar` was also coupled, that it didn't work with the version that Ivy downloaded for constellation. Hence it's also separately loaded from the `languagetoolconf` folder.

2025-04-08 04:00 UTC, Delphinus8821 requested changes
Its working well, just a few minor changes

2025-04-14 23:22 UTC, Delphinus8821 approved these changes

2025-04-15 23:27 UTC, OrionsGuardian requested changes
There seems to be a configuration issue when trying to build **constellation-adapters** with the spellcheck version of constellation as the base.
```
:: resolving dependencies :: au.gov.asd.tac#third-party-dependencies;working@ZZ-AABBCCDD
	confs: [defaultconf]

:: problems summary ::
:::: ERRORS
	requested configuration not found in au.gov.asd.tac#third-party-dependencies;working@ZZ-AABBCCDD: [ 'defaultconf' ]
```

2025-04-17 07:21 UTC, Auriga2 commented
Logged https://github.com/constellation-app/constellation/issues/2295 to fix the Undo after Ignore all

2025-04-30 05:29 UTC, Auriga2 commented
Fixed constellation-adapters in https://github.com/constellation-app/constellation-adaptors/pull/39

2025-04-30 05:34 UTC, Auriga2 commented
Also added a `defaultconf` here, to avoid specifying `conf` tag for future dependencies.

2025-05-05 23:28 UTC, Delphinus8821 commented
It it working well but in testing I found that it was making the Data Access View take almost a whole minute to open which is not ideal. This happened both with and without Adaptors built.
Steps I tested:
Created a sphere graph using the button on the Welcome Page
Attempted to open the Data Access View

2025-05-21 05:19 UTC, antares1470 reviewed
Minor but I think it might be worth adding a TODO comment to some of the custom class loader parts of the code, just to acknowledge that this is a workaround which can be removed once the dependency clash is no longer an issue. Having a reference in code will make it easier to track than remembering this PR

2025-05-21 05:19 UTC, antares1470 commented on CoreUtilities/src/au/gov/asd/tac/constellation/utilities/text/SpellChecker.java
> +//import static au.gov.asd.tac.constellation.utilities.text.LanguagetoolClassLoader.*;
this comment can be removed

2025-05-21 07:44 UTC, Auriga2 commented
I can recreate the slowness ~30-50s in the spellcheck branch. But it is quite random and I cannot pinpoint anywhere. The logs suggest the spellchecking actions are performed in less than a second. (Can we rely on time stamps?) When I could recreate, a considerable time was taken between discovering data access plugins:

spellcheck branch:
![image](https://github.com/user-attachments/assets/5edcb024-636a-4a17-9a98-2f2f29d975ee)

In fact when I merge the spellcheck branch into master, it's consistently faster. 
Master without spell checking ~9s
Master with spellcheck branch merged ~9-14s

As [Delphinus8821](https://github.com/Delphinus8821) suggested we should merge and see the performance in a built version before making any more effort?

I've removed the unnecessary while loop, although it didn't affect the slowness.

2025-05-23 02:30 UTC, antares1470 approved these changes

2025-05-27 05:18 UTC, merged