Feature/copy paste from histogram #741
constellation-app/constellation pull request #795
Opened 2020-08-19 06:33 UTC by sol695510

### Description of the Change

Added functionality to copy property values from a bar selection on the Histogram View to the clipboard via a right-click context menu or via ctrl+c. The context menu also provides an option to copy property values and their associated counts.

Also limited selections of bars to only left-click on the mouse instead of previously being activated by left-click, right-click or clicking the mouse wheel.

### Alternate Designs

N/A

### Why Should This Be In Core?

N/A

### Benefits

Copying values from the Histogram View will be more time efficient for users.

### Possible Drawbacks

N/A

### Verification Process

Tested by copying various bar selections, including both with shift held down or control held down, then either using ctrl+c or the right-click context menu to copy values to a text editor to verify whether the correct values were copied across.

### Applicable Issues

#741

2020-08-20 05:09 UTC, sol695510 commented
@antares1470 what's your call on the Code Smells detected? In my opinion the order of "if" statements provides better readability of the logic.

2020-08-20 05:57 UTC, antares1470 requested changes

2020-08-20 05:57 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +        JMenuItem copyValuesMenuItem = new JMenuItem("Copy Selected Property Values");
final

2020-08-20 05:57 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +        JMenuItem copyValuesAndCountsMenuItem = new JMenuItem("Copy Selected Property Values & Counts");
final

2020-08-20 05:57 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +            if (e.getButton() == MouseEvent.BUTTON3) {
merge this if statement with the above

2020-08-20 05:57 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +                Bin[] bins = binCollection.getBins();
final

2020-08-20 05:57 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +            if (e.getButton() == MouseEvent.BUTTON1) {
merge if statement with above

2020-08-20 05:57 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +                Bin[] bins = binCollection.getBins();
final

2020-08-20 05:57 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +                int newDragEnd = bar;
final

2020-08-20 05:57 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +            if (e.getButton() == MouseEvent.BUTTON1) {
merge if statement with above

2020-08-20 05:57 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +                if ((e.isControlDown()) && (e.getKeyCode() == KeyEvent.VK_C)) {
merge all these if statements together

2020-08-20 06:24 UTC, sol695510 commented
@antares1470 Why is the SonarCloud Code Analysis failing?

2020-08-20 22:40 UTC, antares1470 requested changes

2020-08-20 22:40 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +            e.getButton() == MouseEvent.BUTTON3) {
Minor but I think we prefer `&&` at the start of the newline rather than the end of the old line

2020-08-20 22:40 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +            e.getButton() == MouseEvent.BUTTON1) {
same here

2020-08-20 22:40 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +            e.getButton() == MouseEvent.BUTTON1) {
same here

2020-08-20 22:40 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +            e.getButton() == MouseEvent.BUTTON1) {
same here

2020-08-20 22:40 UTC, antares1470 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +            ((e.isControlDown()) && (e.getKeyCode() == KeyEvent.VK_C))) {
same here

2020-08-20 22:42 UTC, antares1470 commented
> 
> 
> @antares1470 Why is the SonarCloud Code Analysis failing?

My guess would be the code coverage but I'm not entirely sure. I wouldn't worry about it too much to be honest. You've cleared all the code smells which is fine

2020-08-21 03:09 UTC, formalhaut69 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +        for (Bin bin : binCollection.getBins()) {
Also can be final

2020-08-21 03:10 UTC, formalhaut69 commented on CoreHistogramView/src/au/gov/asd/tac/constellation/views/histogram/HistogramDisplay.java
> +    private void copySelectedToClipboard(boolean includeCounts) {
A little nitpicky but includeCounts can be final

2020-08-23 22:54 UTC, arcturus2 approved these changes
Nice work @sol695510

2020-08-23 22:54 UTC, merged