Bugfix for Layer By Time Visibility
constellation-app/constellation pull request #844
Opened 2020-09-14 02:27 UTC by Polaris5514

### Description of the Change
Visibility of Duplicate nodes was being set to 0, changed to 1

### Alternate Designs
N/A

### Why Should This Be In Core?
Bugfix

### Benefits
All nodes Visible 

### Possible Drawbacks
None realised

### Verification Process

### Applicable Issues
#830

2020-09-14 14:25 UTC, arcturus2 requested changes
@Polaris5514 thanks for this and what you have proposed will work. However I was also thinking about just not setting the `vxVisibilityAttr` attribute because it does default to `1`. This would mean that we could delete the definition of `vxVisibilityAttr` and any references to it. If you have tried this already and if that wasn't working then let me know and I'll be happy to approve this.

2020-09-14 23:25 UTC, Polaris5514 commented
@arcturus2 Apologies, I had attempted this yesterday but Node 0 was still invisible. Have now found that Node 0 is set to invisible on creation of the sphere graph, not within the Layer By Time plugin. 
Requested changes have now been properly implemented

2020-09-15 00:06 UTC, arcturus2 requested changes
All good @Polaris5514, you have nothing to apologies for. I think I've found a bit more code that could be deleted so let me know when you have a chance to review.

The advantage of removing code is that it potentially can uncover additional redundant code and takes a step towards removing technical debt which is a good thing 😄

2020-09-15 00:06 UTC, arcturus2 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/time/LayerByTimePlugin.java
>                  }
@Polaris5514 from my reading of the code I think this entire if block could be removed. What do you think?

2020-09-15 01:18 UTC, Polaris5514 commented
Thanks @arcturus2, I have removed the suggested if block. Have also looked through and found two more redundant sections of code and removed them as well.

2020-09-15 22:45 UTC, antares1470 requested changes

2020-09-15 22:45 UTC, antares1470 commented on CoreArrangementPlugins/src/au/gov/asd/tac/constellation/plugins/arrangements/time/LayerByTimePlugin.java
>              final int zAttr = wgcopy.addAttribute(GraphElementType.VERTEX, FloatAttributeDescription.ATTRIBUTE_NAME, "z", "z", 0, null);
this variable is apparently no longer being used. If you're able to remove it that would be great.

2020-09-16 00:41 UTC, antares1470 approved these changes

2020-09-16 00:42 UTC, merged