Performance/838 renderer speed
constellation-app/constellation pull request #848
Opened 2020-09-29 07:00 UTC by Nova-2119

### Description of the Change

### Applicable Issues

#838

2020-10-01 00:28 UTC, cygnus-x-1 requested changes

2020-10-01 00:28 UTC, cygnus-x-1 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/GLInteractiveVisualManagerFactory.java
> +        try(ReadableGraph rg = graph.getReadableGraph()) {
final ReadableGraph (also, whitespace).

2020-10-01 00:28 UTC, cygnus-x-1 commented on CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/framework/GraphVisualAccess.java
> +    private void recalculateVertexColorAttribute(ReadableGraph readGraph) {
final ReadableGraph (all throughout this file).

2020-10-07 02:30 UTC, antares1470 approved these changes

2020-10-15 14:11 UTC, arcturus2 approved these changes
With 30k nodes and 30k links the graph which took 2:47 seconds rendered in 1:02 seconds. Words cannot explain my gratitude for this improvement.

2020-10-15 14:12 UTC, merged