Create Show On Startup Checkbox
constellation-app/constellation pull request #854
Opened 2020-10-16 03:34 UTC by Polaris5514

### Description of the Change
Create a checkbox on Tutorial Page to toggle showing on start-up

### Alternate Designs
NA

### Why Should This Be In Core?
Easier way to turn off showing the tutorial page on start-up 

### Benefits
Easier way to turn off showing the tutorial page on start-up 

### Possible Drawbacks
None Realised

### Verification Process

### Applicable Issues
#808

2020-10-18 11:22 UTC, arcturus2 requested changes
Hi @Polaris5514,
I tested this locally (and did a clean-build) and I can see that the tutorial checkbox is not selected but it is in Tools -> Options. Can you check again?

![image](https://user-images.githubusercontent.com/39325530/96365933-f5658a00-118f-11eb-9e4f-556e0f668789.png)

2020-10-27 03:36 UTC, antares1470 requested changes
If you are able to. Could you also please add an entry to whatsnew.txt for this change?

2020-10-27 03:36 UTC, antares1470 commented on CoreFunctionality/src/au/gov/asd/tac/constellation/functionality/tutorial/TutorialViewPane.java
> +            CheckBox showOnStartUpCheckBox = new CheckBox("Show On Startup");
if you could add final, that would be great

2020-10-27 23:39 UTC, antares1470 approved these changes

2020-10-29 20:30 UTC, arcturus2 approved these changes

2020-10-29 21:20 UTC, aldebaran30701 approved these changes

2020-10-29 21:31 UTC, merged