Update to 'Whats New' Fontsize
constellation-app/constellation pull request #855
Opened 2020-10-16 05:17 UTC by Polaris5514

### Description of the Change
Changed the What's New font size to a set size instead of using preferred font size

### Alternate Designs
Different Font Size

### Why Should This Be In Core?
Bugfix

### Benefits
What's New text easier to read

### Possible Drawbacks
None Realised 

### Verification Process

### Applicable Issues
#712

2020-10-17 05:07 UTC, arcturus2 requested changes
Thanks for this @Polaris5514 but hard coding the font size isn't the right approach. We've taken steps to have our views dynamically update their font size when you change it from Setup -> Options -> Misc because different people will have different screen resolutions or preferences. 

Can you work with `FontUtilities.getOutputFontSize()` and see if you can maybe increase it by a factor like 1.5 to get it aligned with the rest of the views?

2020-10-27 03:26 UTC, antares1470 approved these changes

2020-10-29 20:25 UTC, arcturus2 approved these changes

2020-10-29 21:19 UTC, aldebaran30701 approved these changes

2020-10-29 21:30 UTC, merged