Performance/838 multi threading
constellation-app/constellation pull request #879
Opened 2020-10-27 02:56 UTC by Nova-2119

### Description of the Change

### Why Should This Be In Core?

### Benefits

Speed improvements to opening graphs and how quickly the graph resets after opening a view.

### Possible Drawbacks

There may still be a multithreading bug hanging around in there. Unable to confirm as I could not get it to occur again.
People will be unable to go and get a coffee while their larger graphs load.

### Verification Process

### Applicable Issues
#838

2020-10-28 22:05 UTC, antares1470 requested changes

2020-10-28 22:05 UTC, antares1470 commented on CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java
> +        Thread bottomLabelThread = new FillBottomLabels(access, bottomGlyphStream);
This and the thread above can be final

2020-10-28 22:05 UTC, antares1470 commented on CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java
> +        Thread topLabelThread = new FillTopLabels(access, glyphStream);
both final

2020-10-28 22:05 UTC, antares1470 commented on CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java
> +        Thread bottomLabelThread = new FillBottomLabels(access, glyphStream);
both final

2020-10-28 22:05 UTC, antares1470 commented on CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java
> +        ExecutorService pool = Executors.newFixedThreadPool(NUM_CORES);
final

2020-10-28 22:05 UTC, antares1470 commented on CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java
> +            Thread thread = new BufferTopLabel(pos, access, glyphStream);
final

2020-10-28 22:05 UTC, antares1470 commented on CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java
> +            Thread thread = new BufferBottomLabel(pos, access, glyphStream);
this and `pool` can be final

2020-10-28 22:05 UTC, antares1470 commented on CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java
> +        final private NodeGlyphStream glyphStream;
swap the modifiers around on both of these to be `private final`

2020-10-28 22:05 UTC, antares1470 commented on CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java
> +            final private NodeGlyphStream glyphStream;
same here

2020-10-28 22:05 UTC, antares1470 commented on CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java
> +        final private NodeGlyphStream glyphStream;
same here

2020-10-28 22:05 UTC, antares1470 commented on CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/renderer/batcher/NodeLabelBatcher.java
> +        final private NodeGlyphStream glyphStream;
same here

2020-10-28 22:05 UTC, antares1470 commented on CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/glyphs/ConnectionGlyphStream.java
> +            ConnectionGlyphStreamContext context = (ConnectionGlyphStreamContext) streamContext;
final

2020-10-28 22:05 UTC, antares1470 commented on CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/glyphs/ConnectionGlyphStream.java
> +            ConnectionGlyphStreamContext context = (ConnectionGlyphStreamContext) streamContext;
final

2020-10-28 22:05 UTC, antares1470 commented on CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/glyphs/NodeGlyphStream.java
> +            NodeGlyphStreamContext context = (NodeGlyphStreamContext) streamContext;
final

2020-10-28 22:05 UTC, antares1470 commented on CoreOpenGLDisplay/src/au/gov/asd/tac/constellation/visual/opengl/utilities/glyphs/NodeGlyphStream.java
> +            NodeGlyphStreamContext context = (NodeGlyphStreamContext) streamContext;
final

2020-10-29 20:23 UTC, arcturus2 approved these changes

2020-10-29 23:15 UTC, aldebaran30701 requested changes
I seem to have found a bug - the steps below are reproducers.
I followed the steps below quickly.
open new graph -> generate structured graph builder (1000) backbone size
open new graph -> generate sphere graph (10000)
open new graph -> generate sphere graph (1000)
While it was all trying to load, I switched between graphs and while it happened to try and load the sphere, I was on the structured graph. It loaded those elements onto that graph instead of the sphere graph. 
See the below gif for the behavior

![render glitch](https://user-images.githubusercontent.com/58677759/97642250-a0c9e500-1a94-11eb-92fc-43161eb3be51.gif)

EDIT: I managed to get this reproduced in the current master. I'll make a ticket for it.
I'm happy for the functionality of this to be approved, I haven't taken a look at the code yet but will be providing my suggestions there also if needed.

2020-10-30 04:10 UTC, aldebaran30701 approved these changes
Didn't find any usage problems, waaay faster!
I didn't find any extra code smells after @antares1470  review. 
Great work ~

2020-11-08 14:13 UTC, arcturus2 commented
@antares1470 I've addressed your comments in 43355e7 and some code warnings in 1aea839

2020-11-08 21:45 UTC, antares1470 approved these changes
I could probably get more picky with cleaning up more of the code smells but I think we can merge this in now

2020-11-08 21:46 UTC, merged