Bugfix/issue842 levenshtein single choice resets
constellation-app/constellation pull request #889
Opened 2020-11-06 00:30 UTC by Delphinus8821

### Description of the Change
Fix to the Levenshtein Distance Single Choice combo box so that it no longer updates every time part of the graph is selected.

### Alternate Designs
N/A

### Why Should This Be In Core?
Fixes the bug that makes the combo box change the currently selected item on selection on the graph.

### Benefits
The user won't have to update the combo box every time they make a new selection on the graph.

### Possible Drawbacks
None

### Verification Process
Created a new graph and tested that the Levenshtein combo box did not continue to change when different parts of the graph were selected.

### Applicable Issues
#842

2020-11-06 03:08 UTC, antares1470 approved these changes

2020-11-06 21:34 UTC, arcturus2 requested changes
Hi @Delphinus8821 
I managed to produce a bug. Reproducer is:

1. open a new graph
1. open analytic view -> categories -> similarity
1. tick levenshtein distance and select "min score" (for example) from the aggregation
1. draw mode and add a node

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1310)
	at javafx.base/com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
	at javafx.controls/javafx.scene.control.ListView$ListViewBitSetSelectionModel.getModelItem(ListView.java:1486)
	at javafx.controls/javafx.scene.control.MultipleSelectionModelBase.select(MultipleSelectionModelBase.java:432)
	at javafx.controls/javafx.scene.control.skin.ComboBoxListViewSkin.layoutChildren(ComboBoxListViewSkin.java:325)
	at javafx.controls/javafx.scene.control.Control.layoutChildren(Control.java:601)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1204)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:576)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2482)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
[catch] at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

2020-11-08 21:58 UTC, Delphinus8821 commented
Hi @arcturus2 
As @Polaris5514 mentioned in his comment on the ticket for this issue, he found that there is an additional bug with the aggregation method combo box in the analytic view. I am able to reproduce this bug on the master branch using both the levenshtein analytic and the other analytics by making a selection on a graph and then attempting to change the aggregation method combo box. Attached is the replication of the bug on the master branch.

I believe an additional issue should be created for the aggregation method combo box as the error is not directly related to the levenshtein bug. Would you like me to create a ticket for that bug?

![aggregationLevel2](https://user-images.githubusercontent.com/73083035/98485295-4df6e700-2265-11eb-87e4-27c529ceb581.gif)

2020-11-10 01:03 UTC, arcturus2 commented
>Would you like me to create a ticket for that bug?

yes please @Delphinus8821

2020-11-10 01:03 UTC, merged