Performance/878 zoom performance
constellation-app/constellation pull request #892
Opened 2020-11-11 02:44 UTC by Nova-2119

### Description of the Change

### Alternate Designs

### Why Should This Be In Core?

### Benefits
Improved scroll responsiveness

### Possible Drawbacks
Unknown

### Verification Process

### Applicable Issues

https://github.com/constellation-app/constellation/issues/878

2020-11-11 03:42 UTC, antares1470 requested changes

2020-11-11 03:42 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/InteractiveGLVisualProcessor.java
> +        NodeCameraDistance closest = nodeCameraDistances.parallel().reduce(new NodeCameraDistance(), (ncd1, ncd2) -> NodeCameraDistance.getClosestNode(ncd1, ncd2));
These 2 can be final

2020-11-11 03:42 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/InteractiveGLVisualProcessor.java
> +        Float distanceFromCamera;
These look like they could be final

2020-11-13 03:39 UTC, arcturus2 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/InteractiveGLVisualProcessor.java
> +        NodeCameraDistance closest = nodeCameraDistances.parallel().reduce(new NodeCameraDistance(), (ncd1, ncd2) -> NodeCameraDistance.getClosestNode(ncd1, ncd2));
Updated

2020-11-13 03:39 UTC, arcturus2 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/visual/InteractiveGLVisualProcessor.java
> +        Float distanceFromCamera;
Updated

2020-11-13 03:40 UTC, merged