Welcome Page Resize Issue
constellation-app/constellation pull request #933
Opened 2021-01-12 22:28 UTC by Delphinus8821

### Description of the Change
Added a scroll pane to the welcome page so that the content on the page is able to be seen without any buttons overlapping. The contents of the page now fill to the height and width of the current page and if the page size gets smaller than the layout of the contents of the page, scroll bars are added. This allows for the page keeps its formatting and allow all buttons to continue to be viewed using the scroll bar.

### Alternate Designs
None realised

### Why Should This Be In Core?
The current welcome page does not resize correctly so some of the buttons are unable to be reached. This change ensures that all of the content on the page is able to be viewed either by default or by using the scroll bars. 

### Benefits
Allows for all of the buttons on the welcome page to be reachable when the page is resized.

### Possible Drawbacks
None realised

### Verification Process
Tested by changing the size of the window and by adding additional views in constellation both to the side and bottom of the window. 

### Applicable Issues
#932 

Example of the change to the welcome page with views added to the side and bottom of the window.

![ScrollingWelcomePage](https://user-images.githubusercontent.com/73083035/104381916-25e57600-557d-11eb-834e-1a445e3980b8.PNG)

2021-01-12 23:02 UTC, antares1470 requested changes

2021-01-12 23:02 UTC, antares1470 commented on CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/WelcomeViewPane.java
> +            Rectangle2D visualBounds = Screen.getPrimary().getVisualBounds();
final

2021-01-12 23:16 UTC, antares1470 approved these changes

2021-01-13 03:02 UTC, arcturus2 approved these changes

2021-01-13 03:03 UTC, merged