Performance/28 aggregation speed
constellation-app/constellation pull request #935
Opened 2021-01-13 02:01 UTC by Nova-2119

### Description of the Change

### Why Should This Be In Core?

### Benefits

Speed benefits when using analytic aggregators. Example speed difference:
When running all centrality analytics and using the append aggregator:
1000/1000 Graph: 14,000 ms -> 300 ms
5000/5000 Graph: 525,475ms -> 442 ms

### Possible Drawbacks

Side effect: More results are now shown, previousl when aggregating the result would not be shown if any of the analytic produced a null/o result. Now they show as long as atleast one analytic has a non null/0 result.

### Verification Process

### Applicable Issues

https://github.com/constellation-app/constellation/issues/28

2021-01-13 02:41 UTC, antares1470 requested changes

2021-01-13 02:41 UTC, antares1470 commented on CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/aggregators/MaxScoreAggregator.java
> +        combinedResults.getResult().forEach((IdentificationData key, ElementScore value) -> {
omit types from the lambda parameters if possible

2021-01-13 02:41 UTC, antares1470 commented on CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/aggregators/MaxScoreAggregator.java
> +            aggregateScores.put(SCORE_NAME, value.getNamedScores().values().stream().reduce(Math::max).orElse((float) 0.0));
noting you didn't add this but if you're able to change `(float) 0.0` to `0.0f`, that would be great

2021-01-13 02:41 UTC, antares1470 commented on CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/aggregators/MeanScoreAggregator.java
> +        combinedResults.getResult().forEach((IdentificationData key, ElementScore value) -> {
omit types from lambda parameters if possible

2021-01-13 02:41 UTC, antares1470 commented on CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/aggregators/MeanScoreAggregator.java
> +            aggregateScores.put(SCORE_NAME, value.getNamedScores().values().stream().reduce((x,y) -> x+y).orElse((float) 0.0) / value.getNamedScores().size());
`0.0f`

2021-01-13 02:41 UTC, antares1470 commented on CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/aggregators/MinScoreAggregator.java
> +        combinedResults.getResult().forEach((IdentificationData key, ElementScore value) -> {
omit lambda parameter types if possible

2021-01-13 02:41 UTC, antares1470 commented on CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/aggregators/MinScoreAggregator.java
> +            aggregateScores.put(SCORE_NAME, value.getNamedScores().values().stream().reduce(Math::min).orElse((float) 0.0));
`0.0f`

2021-01-13 02:41 UTC, antares1470 commented on CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/aggregators/SumScoreAggregator.java
> +        combinedResults.getResult().forEach((IdentificationData key, ElementScore value) -> {
omit parameter types if possible

2021-01-13 02:41 UTC, antares1470 commented on CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/aggregators/SumScoreAggregator.java
> +            aggregateScores.put(SCORE_NAME, value.getNamedScores().values().stream().reduce((x,y) -> x+y).orElse((float) 0.0));
`0.0f`

2021-01-13 02:41 UTC, antares1470 commented on CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/results/IdentificationData.java
> +    public boolean equals(Object obj) {
obj can be final

2021-01-13 02:41 UTC, antares1470 commented on CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/results/ScoreResult.java
> +        static public ElementScore combineReplace(ElementScore es1, ElementScore es2) {
parameters can be final. Also change `static public` to `public static`

2021-01-13 02:41 UTC, antares1470 commented on CoreAnalyticView/src/au/gov/asd/tac/constellation/views/analyticview/results/ScoreResult.java
> +            Map<String, Float> combinedNamedScores = new HashMap<>(es1.getNamedScores());
final

2021-01-13 03:16 UTC, antares1470 approved these changes

2021-03-17 04:28 UTC, arcturus2 approved these changes

2021-03-17 04:32 UTC, merged