Welcome Tab Updates
constellation-app/constellation pull request #944
Opened 2021-01-22 04:07 UTC by Delphinus8821

### Description of the Change
The following suggestions in the ticket #943 have been updated and added:
- Only the welcome page launches on start-up of Constellation instead of both the welcome page and tutorial page. The checkbox option for the tutorial page to open on start-up has been moved to the welcome page and the option to display the tutorial page on start-up in the options menu has been converted to the welcome page. The tutorial page has also been updated to mostly contain the "what's new" content with a change to styling for readability.
- The welcome page resize issue has been fixed using a scroll pane.
- The option to start a new graph in selection mode has been added to the welcome page.
- The option to import from JDBC has been added to the welcome page. 

### Alternate Designs
None realised

### Why Should This Be In Core?
These additional options for the welcome page have been added to reflect what has recently been added into Constellation that might be useful for users to have easy access to. 
The tutorial page update to the what's new page reflects what the page is now being used for.

### Benefits

### Possible Drawbacks
None realised

### Verification Process

### Applicable Issues
#943

2021-01-27 00:32 UTC, antares1470 requested changes
If you're able to update the changelog and whatsnew with update to tutorial page (notably that it isn't the tutorial page anymore) that would be good also

2021-01-27 00:32 UTC, antares1470 commented on CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/WelcomeViewPane.java
> +            });
should be able to make this a lambda (remove the types of the parameters when you do)

2021-01-27 00:32 UTC, antares1470 commented on CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/WelcomeViewPane.java
> +            });
should be able to make this a lambda (remove the type of the parameter when you do)

2021-01-27 00:32 UTC, antares1470 commented on CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/plugins/WhatsNewWelcomePlugin.java
> +            final TopComponent tutorial = WindowManager.getDefault().findTopComponent(WhatsNewTopComponent.class.getSimpleName());
Should change the name of this variable to reflect the change in class name

2021-01-27 00:32 UTC, antares1470 commented on CorePreferences/src/au/gov/asd/tac/constellation/preferences/Bundle.properties
> +ApplicationOptionsPanel.startupTutorialCheckbox.text=Display welcome page on startup
should look to rename `startupTutorialCheckbox`

2021-01-28 09:53 UTC, arcturus2 reviewed
I wrote this on Monday but forgot to press submit. Some minor UI tweaks if you can look at them @Delphinus8821? If it becomes fiddly to solve don't worry about it - there are more important issues to get your help with.

![Screenshot from 2021-01-23 10-06-57](https://user-images.githubusercontent.com/39325530/106120369-6adaf080-61aa-11eb-8704-a8f2b84e4a0d.png)

2021-01-29 00:08 UTC, Delphinus8821 commented
@arcturus2 The scroll bars aren't easily able to be changed. In order for the background colour of the welcome tab to take up the whole window when expanded to full size the pane needs to be set to the size of the screen it's currently on. This will lead to the scroll bars having that excess when shrinking the window.

2021-02-01 22:21 UTC, antares1470 requested changes

2021-02-01 22:21 UTC, antares1470 commented on CoreWelcomeView/src/au/gov/asd/tac/constellation/views/welcome/WelcomeViewPane.java
> +                recentGraphButtons[i].setOnAction((ActionEvent e) -> {
same here

2021-02-01 22:21 UTC, antares1470 commented on CoreWhatsNewView/nbproject/project.xml
> +                        <specification-version>9.15.1</specification-version>
Are you able to downgrade this to 9.15? 9.15.1 is only available with netbeans 12.1 (12 is the current LTS)

2021-02-01 22:21 UTC, antares1470 commented on CoreWhatsNewView/nbproject/project.xml
> +                        <specification-version>8.41.1</specification-version>
similar here (8.41)

2021-02-01 22:21 UTC, antares1470 commented on CoreWhatsNewView/nbproject/project.xml
> +                        <specification-version>9.16.1</specification-version>
similar here (9.16)

2021-02-01 22:21 UTC, antares1470 commented on CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/WhatsNewViewPane.java
> +            VBox leftVBox = new VBox();
final

2021-02-01 22:21 UTC, antares1470 commented on CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/WhatsNewViewPane.java
> +            VBox rightVBox = new VBox(10);
final

2021-02-01 22:21 UTC, antares1470 commented on CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/WhatsNewViewPane.java
> +            ImageView menuImage = new ImageView(new Image(WhatsNewTopComponent.class.getResourceAsStream(MENU_IMAGE)));
final

2021-02-01 22:21 UTC, antares1470 commented on CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/WhatsNewViewPane.java
> +            ImageView mouseImage = new ImageView(new Image(WhatsNewTopComponent.class.getResourceAsStream(MOUSE_IMAGE)));
final

2021-02-02 02:36 UTC, cygnus-x-1 commented
Love the changes :)

2021-02-02 02:36 UTC, cygnus-x-1 approved these changes

2021-02-02 23:09 UTC, antares1470 requested changes
I think some of the constants and fields may be unnecessary in the Welcome Page Pane. It's going to be a bit difficult for me to explain though so I'll create a PR outlining my thoughts.

Also if you're able to resolve the merge conflict that would be great

2021-02-03 21:29 UTC, antares1470 approved these changes
This should be good once the merge conflict is resolved

2021-02-03 22:10 UTC, merged