Modified menu display to ensure it is visible.
constellation-app/constellation pull request #948
Opened 2021-01-27 04:28 UTC by serpens24

### Description of the Change

Modified menu display settings for several views to give a consistant feel as well as shading any menu options to make the menu identifyable.

### Alternate Designs

nil
### Why Should This Be In Core?

Requested ticket highlighted that in some cases this top menu wasnt easily identifed as cselectable.

### Benefits

Ensure menu is selectable - and identifiable by the user. Note - the issue in this case is that the top bar is a menubar, which normally doesn't have shading for each menu option, this however is having other buttons overlaid so it requires a slightly different look and feel.

### Possible Drawbacks

None identified

### Verification Process

Go through all views and ensure any with menus have the same look and feel - in particualr any menu (ie Options menu for Data
Access View) is shaded differently to identify it as a button.

### Applicable Issues

N/A

2021-01-28 05:00 UTC, antares1470 requested changes
Looking at the changes, I think the menu button could really benefit from having a border around it (even a thin one). I can tell that the Options buttons are a different colour, but only because I'm looking for it. I think this may be because the menu button colour itself isn't that much different from the bar it sits on (especially for the Delimited File Importer). I think the colour scheme can be kept, just needs a outline.

Also, I noticed the help button in the Delimited File Importer is still a darker colour to the one you've been applying to some of the other views. Not sure if that was intended or was simply missed but I think the colour change should be applied there also.

2021-01-28 10:01 UTC, arcturus2 approved these changes
Thanks for going through this and trying to make it more consistent. It is definitely a step in the right direction. As @antares1470 mentioned, it would be interesting to see what an outline would look like.

2021-01-28 21:44 UTC, serpens24 commented
Thanks both. I had missed the delimited importer help color so will fix.

The color I used for menus was based on the button color of the other overlay buttons - ie the + and * buttons for Data Access View. These do stand out better because they have borders. I cannot replicate those border styles AFAIK, but I can add a plain rectangular border. Doing so certainly makes it more obvious .... I will experiment with colour, I suspect a light silver rather than white may be the best option.

![image](https://user-images.githubusercontent.com/58677108/106202557-0485ba80-620a-11eb-87a3-bd8926cb695e.png)

2021-02-01 01:12 UTC, antares1470 approved these changes

2021-02-01 01:12 UTC, merged