Plugin Reporter Deselect Ignored Checkbox Value by Default
constellation-app/constellation pull request #975
Opened 2021-02-16 23:00 UTC by Delphinus8821

### Description of the Change
The Plugin Reporter ignored plugins currently displays the value "LOW LEVEL" as being selected by default but when opening the drop-down list it is not ticked. The change clears the combo-box value so that nothing is selected by default.

### Alternate Designs
None realised

### Why Should This Be In Core?

### Benefits
Clearly shows what is currently selected in the Plugin Reporter ignored plugins combo-box.

### Possible Drawbacks

### Verification Process
On a clean build of Constellation, the plugin reporter ignored plugins show none are selected by default. 

### Applicable Issues
#906

2021-02-17 00:22 UTC, aldebaran30701 approved these changes

2021-02-18 21:50 UTC, antares1470 requested changes

2021-02-18 21:50 UTC, antares1470 commented on CorePluginReporterView/src/au/gov/asd/tac/constellation/views/pluginreporter/panes/PluginReporterPane.java
> +        for (String checked: checkedIndices){
final

2021-02-18 22:42 UTC, antares1470 approved these changes

2021-02-22 22:11 UTC, merged