Bugfix/issue365 select box
constellation-app/constellation pull request #992
Opened 2021-03-18 00:28 UTC by Nova-2119

### Description of the Change

### Why Should This Be In Core?

### Benefits

-->
Easier to select nodes using a selection box, application is more intuitive to use.

### Applicable Issues

2021-03-19 02:35 UTC, antares1470 requested changes

2021-03-19 02:35 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/BoxSelectionPlugin.java
> +            float r = graph.getFloatValue(rAttr, vxId);
All 3 can be final

2021-03-19 02:35 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/BoxSelectionPlugin.java
> +                boolean vertexAboveBox = top < bottomMostPoint;
All 4 can be final

2021-03-19 02:35 UTC, antares1470 commented on CoreInteractiveGraph/src/au/gov/asd/tac/constellation/graph/interaction/plugins/select/BoxSelectionPlugin.java
> +                if (!(vertexLeftOfBox || vertexRightOfBox || vertexBelowBox || vertexAboveBox)) {
Are you able to propagate the `!`?
i.e. `!vertexLeftOfBox && !vertexRightOfBox && !vertexBelowBox && !vertexAboveBox`

2021-03-22 14:56 UTC, arcturus2 approved these changes

2021-03-23 23:10 UTC, aldebaran30701 commented
I've just added those code changes to this PR incase it was waiting on @Nova-2119

2021-03-23 23:36 UTC, antares1470 approved these changes

2021-03-23 23:36 UTC, merged